### ISSUE TITLE
unknown Statement of type "ForOfStatement"

### ISSUE THREAD

**Issue by harshal2030** [ammarahm-ed/react-native-mmkv-storage#101]
I'm using react-native-mmkv-storage: 0.5.8 and react native 0.63.3
and I got the following error in my console.
```
error: node_modules\react-native-mmkv-storage\src\hooks\useMMKV.js: C:\Users\Harshal\Desktop\EasyTeach\node_modules\react-native-mmkv-storage\src\hooks\useMMKV.js: unknown Statement of type "ForOfStatement"
```

**Comment by ammarahm-ed** [comment]
I will fix it.

**Comment by harshal2030** [comment]
Yeah and thank you for this great package. It's really very fast🚀

**Comment by ammarahm-ed** [comment]
> Yeah and thank you for this great package. It's really very fast🚀

Can you test using master. I have fixed the issue you were having.

**Comment by harshal2030** [comment]
okk! I will get back to you

**Comment by harshal2030** [comment]
Yeah! It's fixed now. Not getting any error.
Please release this new fix on npm

**Comment by ammarahm-ed** [comment]
I will release soon. closing issue
