### ISSUE TITLE
[Feature Request] does RN-MMKV-S already support dynamic data types?

### ISSUE THREAD

**Issue by flixyudh** [ammarahm-ed/react-native-mmkv-storage#102]
currently i see there's an API that support for specific data types (e.g `set/get String, set/get Boolean, set/get Int and many more`), but should it be simplify by using `set/get` only without specified data types?

something like:
```js
import MMKVStorage from "react-native-mmkv-storage";

MMKV = new MMKVStorage.Loader().initialize();
MMKV.set(key, {foo:'is an object'})

MMKV.get(key) //output: {foo:'is an object'}

MMKV.set(key, false)

MMKV.get(key) //output: false
```

**Comment by ammarahm-ed** [comment]
> currently i see there's an API that support for specific data types (e.g `set/get String, set/get Boolean, set/get Int and many more`), but should it be simplify by using `set/get` only without specified data types?
> 
> something like:
> ```js
> import MMKVStorage from "react-native-mmkv-storage";
> 
> MMKV = new MMKVStorage.Loader().initialize();
> MMKV.set(key, {foo:'is an object'})
> 
> MMKV.get(key) //output: {foo:'is an object'}
> 
> MMKV.set(key, false)
> 
> MMKV.get(key) //output: false
> ```
> 

There is no plan for such abstraction.
