### ISSUE TITLE
Add lifecycle hooks to operations

### ISSUE THREAD

**Issue by SaltedBlowfish** [ammarahm-ed/react-native-mmkv-storage#104]
The purpose of this issue is to propose and discuss the benefits (or drawbacks) of adding lifecycle hooks to this library.

### What

Add lifecycle hooks that can react to (and possibly mutate data for) various storage operations.

### Why

As a developer, I often need the ability to monitor changes to my data structure and respond to specific events against my storage system.

Having the ability to register event-based hooks with custom callbacks would:

1. Enable Developer Tooling
  - We could write developer tools that show the state of storage and operations against storage.
2. Enable Custom Indexing
  - Developers would be able to build dynamic, reactive indexes on their data to suit their needs.
3. Enable Lower-Level Data Management
  - Cleanup operations, statistical calculations, data aggregations, and background data syncing would all be made possible without layers of wrapper functions.
4. Enable On-the-Fly Mutations
  - Having the power to perform simple transformations on specific data on its way into and out of storage is a handy tool. It can be argued that it's outside the scope of this library though.

#### 1. Enable Developer Tooling

This one is super broad but here's a simple transaction logger example that would drastically help debug larger apps without relying on custom wrappers:

```
MMKV.onTransaction(({ type, key, value }) => {
  console.log('MMKV Transaction:', type, key, value)
})
```

#### 2. Enable Custom Indexing

```
MMKV.onTransaction(({ type, key, value }) => {
  if (type !== 'setMapAsync') return; // look for specific MMKV transaction types
  if (!key.startsWith('posts.')) return; // only look at "posts." namespace
  // TODO: developer determines if it's a new record or not

  // custom index posts by tags and id for searching without fetching ALL post records
  MMKV.setArrayAsync('postsIndex', [...oldValue, { id: 'posts.abc', [tags: 'react', 'typescript' }])
})

// then the developer can simply use the useMMKVStorage hook to listen to changes 
// to the index and react to changes
...
const [postsIndex, setPostsIndex] = useMMKVStorage('postsIndex', MMKV)
...
```

#### 3. Enable Lower-Level Data Management

```
MMKV.onTransaction(({ type, key, value }) => {
  if (type !== 'setMapAsync') return; // look for specific MMKV transaction types
  if (!key.startsWith('posts.')) return; // only look at "posts." namespace

  // developer can update other fields based on this transaction
  MMKV.setIntAsync('userPostCount', oldValue + 1)
})
```

4. Enable On-the-Fly Mutations

```
const injectTimestamp = (record) => ({ ...record, timestamp: Date.now() })

MMKV.beforeTransaction(({ type, key, value, cancel }) => {
  if (type !== 'setMapAsync') return; // look for specific MMKV transaction types
  if (!key.startsWith('posts.')) return; // only look at "posts." namespace
  if (!!value.timestamp) return; // only run if timestamp is not in record already
  
  // function that can be called to cancel the original transaction
  cancel();

  // setup new transaction with properly structured data
  MMKV.setMapAsync(key, injectTimestamp(value))
})
```

#### Example Footnotes

Obviously these are contrived examples with the intention showing what is possible with the core ideology of this feature. The functions would probably be branched more uniquely (e.g., instead of `MMKV.onTransaction` we would make it more convenient with `MMKV.onSetMapAsync`. Also, the data mutation example is somewhat wasteful considering the transaction cancellation and respawn. It's likely that utilizing a specific key mutator function on the MMKV hook would be more performant. E.g., `MMKV.mutateOnSetMapAsync(key: string, mutator: (value: any) => mutatedValue)`.

### Pitfalls / Arguments Against

- This library has the `useMMKVStorage` which ([soon enough](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/98)) can be used to compare previous versus current states to react to data. It can be argued that this is a more React-y way to handle this problem. The problem is that it requires both states to exist in memory for the comparison to happen, and this can be an expensive operation.

**Comment by ammarahm-ed** [comment]
Can you elaborate on this more with some rough examples?

**Comment by SaltedBlowfish** [comment]
@ammarahm-ed Thanks for taking the time to think through this with me. I've updated my original issue with examples.

**Comment by ammarahm-ed** [comment]
@SaltedBlowfish Thanks for helping me understand this better. The proposal here is good and the way I have written the library could possibly help us do this easily. But before that, we need to look at the current state of the library and investigate any possible ways by which we could optimize the performance of read/write further. 

This way we can possibly do more than an average `key-value` storage that puts all the burden to manage data on the developer. So we need more control over the data. A basic api could be like this without creating an event for each data type separately?

For example:
```js

function beforeTransaction(key,mutator) {

let eventName = `ontransaction:${key}`

storage.eventManager.subscribe(eventName,mutator);

return () => storage.eventManager.unsubscribe(eventName,mutator);
}

// And later

let unsub = storage.beforeTransaction("key", ({key,value}) => {{
// Here we can manipulate the data
// How shall we return the new value to the original function to be set?
// How can we possibly cancel the original call and replace it with a new one
// and return the value back to where original function was called synchronously?
// What if user has subscribed for the same key in two different places, how will the data be handled?

// Also it would be great if instead of canceling the original function call, we could just return the value
// and check on our end if the value has changed from what was sent and update it accordingly?

return value // Or a mutated value?
})


```
Instead of an event based approach, maybe we can just register mutator functions. The way we can keep it synchronous and at a time there can only exist one function for a type of transaction in storage which make sense because no one wants to mutate the data in different places in an application.

```js

// register our function
storage.transactions.register('key','ontranscation',mutator);

// our function to register

register(key,type,mutator) {

transactions[`${type}:${key}`] = mutator

}

function setString(key, value) {
if (transactions[`ontransaction:${key}`]) {
 value = transactions[`ontransaction:${key}`](key,value)
}
return global.setStringMMKV(instance,key,value)
}
```

In the mutator function we could pass more information such as `type`, `value`, storage etc. We also need to see how we can change values on the fly while using these events.

**Comment by SaltedBlowfish** [comment]
@ammarahm-ed 

I'll address the points you raised item by item so it's easier for me to track them:

### 1. Performance Optimizations

> But before that, we need to look at the current state of the library and investigate any possible ways by which we could optimize the performance of read/write further.

Is this a general statement about the library's priorities right now or is it a prerequisite to implementing these hooks?

### 2. Developer Data Burden

> This way we can possibly do more than an average key-value storage that puts all the burden to manage data on the developer.

I understand what you're saying. Providing a simple registration system with unsub functions is the most _familiar_ way to me in React, since it's easy to simply subscribe in a hook and unsubscribe in the hook cleanup (like you've written).

I agree with not creating events for each data type. If we register these hooks internally to RNMMKV so that RNMMKV can make the decisions on when to call each one, that's a win for developer maintainability.

### 3. Mutator-Only

> Instead of an event based approach, maybe we can just register mutator functions. The way we can keep it synchronous and at a time there can only exist one function for a type of transaction in storage which make sense because no one wants to mutate the data in different places in an application.

I need to think about the lifecycle here a bit more. I feel like responding to data changes right now in RNMMKV is not easy for large quantities of records that cannot be stored in the array type. Using events was kind of a shortcut method to solve this problem (so that RNMMKV can just say, "Hey. I'm doing something to this data.")

You raise a good point though. I think we should limit the API as much as possible to preserve a pure reactive sort of architecture here...

Now I'm just typing and thinking so bear with me...

The biggest pain point that caused me to raise this issue is that I cannot store the quantity of specific records my app needs in a single array (because 1MB of data being retrieved every time the `useMMKVStorage` hook gets called is way too intense), but when I split it into key:value entries, then I cannot use the `useMMKVStorage` hook to listen to them. 

Here's a data schema as an example:

```
type Post = { title: string; tags: string[]; body: string; attachments: string[] }
...
posts.ID001: Post
posts.ID002: Post
posts.ID003: Post
posts.ID004: Post
```

Now, for me to retrieve all posts under this schema:

```

// option 1: get all keys and retrieve by IDs
const postKeys = (await MMKV.indexer.maps.getKeys()).filter(k => k.startsWith('posts.')
const posts = await MMKV.getMultipleItemsAsync(postKeys, 'map');

// option 2: get all map items and filter by posts
const posts = (await MMKV.indexer.maps.getAll()).filter(([key, item]) => key.starsWith('posts.'))

// either way at this point, to listen to all of these records I'd have to `useMMKVStorage` on each item's key if I didn't want static data
```

-- 

Now, you said:

> This way we can possibly do more than an average key-value storage that puts all the burden to manage data on the developer. 

This could be a separate library on top of yours but making a system where developers can define "collections" (e.g., `posts`) that are internally stored as K:V but surface to them in an easy to use API would be the easiest. Then they can subscribe to changes to said collection, get latest writes, and react to data changes. Not unlike a traditional document database I suppose... Now that I typed this out, I realize that this is perhaps overkill.

**Comment by ammarahm-ed** [comment]
Indeed we cannot watch for instance, a 1000 keys with useMMKVStorage hook since it only can watch one key. Adding all items to a single key-value would be bad for performance and scalability. So let me propose this:

1. We update a value in storage.
2. The key of that value goes into a defined index. say `postsIndex` using `beforeTransaction`
3. Based on the updated index we update data with a hook. For this purpose we can come up with seperate hook/events that will give you all the values of keys in that specified index when it is updated. We can update the existing hook we have or make a seperate one just for this purpose?

```js

storage.setMap("post1xushaf",{...data});
```
We update the index
```js
storage.transactions.register('key','ontranscation',(key,value) => {
     if (key.startsWith("post") {
        // We must keep the index in memory so we don't have to read from storage again and again but only write.
        storage.setArray("postsIndex", prevPostsIndex.push(key)])
    }
});
```
In the component where we are rendering posts based on the index. the following hook gives us all the posts whenever there is an update in postIndex.

```js

const posts = usePostsIndex("postIndex");

```
We can also attach simple operations with the hook:
```js
const  [posts,update,remove] = usePostsIndex("postIndex");

// and later
update(postId, newPost}
remove(postId)
```
During this, we will read from memory and write to storage.

**Comment by SaltedBlowfish** [comment]
> the following hook gives us all the posts whenever there is an update in postIndex

We will need a way of limiting records and / or querying. I can see arrays of thousands being loaded into memory and forcing a rerender. Either that or we simplify it and add a multi-key subscriber to support listening to an array of IDs. Then it's the developers responsibility to use the new hooks to manage the index and subscribe to the IDs they want.

This solution is simpler IMO and leaves more flexibility on the developers. Here's a simple usage example:

#### Step 1: Register "mutator" or "hook" or whatever it ends up being called for managing indexed data
```
storage.transactions.register('key', 'ontransaction', (key, value) => {
  // developer manages index so they can control which fields they care about 
  // in the index and how they want the data structured
});
```

#### Step 2: Developer subscribes to their index for changes, instead of the entire collection
```
type Id = string;
type PostIndexItem = {
  id: Id;
  tags: string[];
  excerpt: string;
  created_at: string;
}

export const SomeReactComponent = ({}: Props) => {
  const [postsIndex, setPostsIndex] = useMMKVStorage<PostIndexItem[]>('postsIndex', MMKV)
  const [filteredPosts, setFilteredPosts] = React.useState<Post[]>([])

  React.useEffect(() => {
    const postIdsToSubscribeTo: Id[] = postsIndex
      .map(({ id, tags }) => tags.includes('typescript') ? id : null)
      .filter(id => id !== null)
    
    const mmkvUnsubscribe = MMKV.subscribeToKeys(postIdsToSubscribeTo, MMKV, (error, result) => {
      if (error) {
        console.error(error)
        return
      }
      
      setFilteredPosts(result)
    })

    return () => mmkvUnsubscribe()
  }, [postsIndex, setFilteredPosts])

  return null
};
```

**Comment by ammarahm-ed** [comment]
```ts
//Here are our two registers.


const beforeTransactionRegistery:{[key:string]:(key:string,value:any) => void} = {}
const onTranscationRegistery:{[key:string]:(key:string,value:any) => void} = {}


/**
 * This is how we register them. A point to note here is that these are not events but functions
 * that will mutate a value. There can only one one function for a key in the whole app so even if 
 * they are registered outside a component it would work well.
 * 
 * @param key The key here can be a key in storage or a key matcher, for example, any key starting with postxxx
 * can have one mutator function and other keys starting with userxxx can have another mutator function. This way we don't have to register a many functions for similar data.
 * 
 */

function register(key:string,type: "on" | "before",mutator:(key:string,value:any) => void) {
    if (type === "on") {
        onTranscationRegistery[key] = mutator
    } else {
        beforeTransactionRegistery[key] = mutator
    }
}

/**
 * We can remove a mutator function from registery like this. This can be improved.
 * @param key 
 * @param type 
 */
function remove(key:string,type: "on" | "before") {
    if (type === "on") {
        onTranscationRegistery[key] = null
    } else {
        beforeTransactionRegistery[key] = null
    }   
}


/**
 * Using the below function we can create a hook. We recieve a list of ids which we use to 
 * subscribe to events. This can be improved. Maybe result can include the key/value pair which was changed and developer can then update the filterPosts accordingly
 */



const mmkvUnsubscribe = MMKV.subscribeToKeys(postIdsToSubscribeTo, MMKV, (error, result) => {
    if (error) {
      console.error(error)
      return
    }
    setFilteredPosts(result)
  })

```

**Comment by ammarahm-ed** [comment]
This feature was added in `v0.6.1`
