### ISSUE TITLE
[Question] persistency of Map properties

### ISSUE THREAD

**Issue by jeromegout** [ammarahm-ed/react-native-mmkv-storage#106]
- OS: iOS
 - React Native Version: 0.64
 - Library Version: 0.5.8

Hi,

I would like to persist the data model of my iOS app with react-native-mmkv-storage.
My model is a javascript object with several properties containing Map.
I would like to know if this kind of data are handled at the moment or not.
I've tried to use the useStorage custom hook as it is described in the documentation but it seems that my object remains empty when application restart.

My custom hook:

```javascript
const MMKV = new MMKVStorage.Loader().withEncryption().initialize();

export const useStorage = key => {
  const [value, setValue] = useMMKVStorage(key, MMKV);
  return [value, setValue];
};

```
usage of my hook:

```javascript
  const [model, setModel] = useStorage('model');
```

at the beginning I'm checking if this is not the first launch the application (no persisted state of the model):
```javascript

 const initModel = () => ({
    classes: new Map(), // Map<ClassID, Class>
    students: new Map(), // Map<StudentID, Student>
    grades: new Map(), // Map<GradeID, Grade>
    studentIdsByClassId: new Map(), // Map<ClassID, StudentID[]>
    gradeIdsByStudentId: new Map(), // Map<StudentID, GradeID[]>
    nextImage: 0, // index of the next image to use for a class
  });

  useEffect(() => {
    if (!model) {
      const m = initModel();
      console.log('init model', m);
      setModel(m);
    }
  }, []);
```
It seems that when I fill my model with some new elements they are not persisted. I can't see them the next time I launch the app.

Any advice will be appreciated.

Thanks in advance
Jerome

**Comment by ammarahm-ed** [comment]
It is supposed to work with all data types. Maybe the issue is because you are using Map instead of simple object? Because behind the scenes, the library uses `JSON.stringify` to store the objects/arrays in storage.

**Comment by jeromegout** [comment]
Thanks for you reply.

I've changed the way I use mmkv-storage. Instead of a single object containing Maps, I've used several arrays each one using useStorage hook separately from others.
It seems this time all is persisted properly.
I will try to continue this way.
Thanks

**Comment by ammarahm-ed** [comment]
> Thanks for you reply.
> 
> I've changed the way I use mmkv-storage. Instead of a single object containing Maps, I've used several arrays each one using useStorage hook separately from others.
> It seems this time all is persisted properly.
> I will try to continue this way.
> Thanks

Indeed that is a better approach!
