### ISSUE TITLE
Initial state

### ISSUE THREAD

**Issue by konradgalczynski07** [ammarahm-ed/react-native-mmkv-storage#107]
What is the proper way to set values with inital value other than null using `useMMKVStorage` hook?

**Comment by ammarahm-ed** [comment]
Right now, you need to set the initial value manually for the first time. However it is possible to add support to give an initial value when hook is attached. I will add it in the next release. I propose something as follows:

```js
const [value,setValue] = useMMKVStorage(key,storage,defaultvalue);
```
But what will happen if the value was removed? Should the hook again reset the value to defaultValue or be null?

**Comment by konradgalczynski07** [comment]
If the value was removed it should be null. I'm trying to create Context with saved state. 

```js
export const useStorage = (key, initial_value = null) => {
  const [value, setValue] = useMMKVStorage(key, MMKV);
  if (!value && initial_value !== null) {
    setValue(initial_value);
  }
  return [value, setValue];
};

export const WorkoutProvider = ({children}) => {
  const [exerciseTime, setExerciseTime] = useStorage('exerciseTime', 40);
```

But it ends up giving me the same value over and over

**Comment by ammarahm-ed** [comment]
Maybe you need to do something like this:

```js
export const useStorage = (key, initial_value = null) => {
  const [value, setValue] = useMMKVStorage(key, MMKV);

useEffect(() => {
  if (!value && initial_value !== null) {
    setValue(initial_value);
  }
},[value])
  return [value, setValue];
};
```
or maybe:

```js
export const useStorage = (key, initial_value = null) => {
  const [value, setValue] = useMMKVStorage(key, MMKV);
 
  return [value || initial_value, setValue];
};
```

**Comment by konradgalczynski07** [comment]
Thank you, that's it. Closing but still please do consider adding initial_value param to original `useMMKVStorage` hook. I think that would be great.
