### ISSUE TITLE
Trying to set a map value to hook for type string is not allowed.

### ISSUE THREAD

**Issue by ubaidjs** [ammarahm-ed/react-native-mmkv-storage#108]
How can I store and retrieve an object in useMMKVStorage hook? Is it even possible or not?
I tried doing so but it throws this error 'Trying to set a map value to hook for type string is not allowed.'

**Comment by ammarahm-ed** [comment]
> How can I store and retrieve an object in useMMKVStorage hook? Is it even possible or not?
> I tried doing so but it throws this error 'Trying to set a map value to hook for type string is not allowed.'
> 
> 

It's possible. The error means that you are trying to change data type of value in storage that is already a string on the fly. Clear your database and try again. For example:

```js
// Setting value of key "hello" to "world"
setValue("world")

// Then updating the value to some object for the same key

setValue({hello:"world"})

```
This is not allowed for the hook

**Comment by ammarahm-ed** [comment]
> How can I store and retrieve an object in useMMKVStorage hook? Is it even possible or not?
> I tried doing so but it throws this error 'Trying to set a map value to hook for type string is not allowed.'
> 
> 

It's possible. The error means that you are trying to change data type of value in storage that is already a string on the fly. Clear your database and try again.

**Comment by ubaidjs** [comment]
Thanks for clarification

**Comment by adesh-nsurely** [comment]
Hi, I'm facing a similar issue. 

I've used `useStorage(MMKV);` to persist the state change.

My code is as follows:

```js
// If object named locationPermission is not present in MMKV, then set a default value
MMKV.getMap('locationPermission') == null  ? 
      MMKV.setMap('locationPermission', {
          asked: false,
          granted: false,
      }) : '';

// Create a hook
const [locationPermission, setLocationPermission] = useStorage('locationPermission');

// Log type of MMKV.getMap('locationPermission') 
console.log(typeof MMKV.getMap('locationPermission')); // object
console.log(MKV.getMap('locationPermission')); // {"asked": false, "granted": false}

// Log type of locationPermission
console.log(typeof locationPermission); // string
console.log(locationPermission); // {"asked":false,"granted":false}

setLocationPermission({
      asked: true,
      granted: true,
}); // Throws 'Trying to set a object value to hook for type string is not allowed.'
```

When I try to update `locationPermission` using `setLocationPermission`, I get following error `Trying to set a object value to hook for type string is not allowed.`. The error is understandable, because it is considering previous value as string. 

I have checked my codebase, and the key `locationPermission` is being used only one place. Just to make sure, I also tried changing the key to some other key and still facing the same issue.

**Comment by adesh-nsurely** [comment]
Ok, I solved it by changing the following:

```js
MMKV.getMap('locationPermission') == null  ? 
      MMKV.setMap('locationPermission', {
          asked: false,
          granted: false,
      }) : '';

const [locationPermission, setLocationPermission] = useStorage('locationPermission');
```

I changed the above code to:

```js
const [locationPermission, setLocationPermission] = useStorage('locationPermission', 
      MMKV.getMap('locationPermission') || {
          asked: false,
          granted: false,
      });
```

However, I believe the old method should work as well, which isn't
