### ISSUE TITLE
[Question] clearStore does raise an error on ios

### ISSUE THREAD

**Issue by jeromegout** [ammarahm-ed/react-native-mmkv-storage#109]
**Platform Information:**
 - OS:  iOS
 - React Native Version:  0.64
 - Library Version: 0.5.8

Hi 

I'm encountering an issue trying to clear my store.
I did use the custom hook to store some data as it is suggested in the documentation. 
I can see my stored elements after application relaunch.

Once I want to clear the store using the global function MMKV.clearStore(), i receive the following error:

 ERROR  TypeError: global.setBoolMMKV is not a function. (In 'global.setBoolMMKV(this.instanceID, true, this.instanceID)', 'global.setBoolMMKV' is undefined)

```javascript
  clearStore() {
    let cleared = handleAction(global.clearMMKV, this.instanceID);
    global.setBoolMMKV(this.instanceID,true,this.instanceID)
    return cleared;
  }
```
Should I use something else to clear the store?

Thanks in advance
Jerome

**Comment by ammarahm-ed** [comment]
@jeromegout That is strange. I will investigate this. This should be working normally. On app launch, maybe you want to check if the function is available. just call `console.log(global.setBoolMMKV)` and see if it returns undefined or `Function`. Also make sure that you are not using chrome debugger to debug the app.

**Comment by ammarahm-ed** [comment]
@jeromegout  I was not able to reproduce this issue.

**Comment by jeromegout** [comment]
Hi Ammar

Here is what I did tried:

I created a file call modelStore.js with the following content:

```javascript
import MMKVStorage, {useMMKVStorage} from 'react-native-mmkv-storage';

const MMKV = new MMKVStorage.Loader().withEncryption().initialize();

export const useStorage = key => {
  const [value, setValue] = useMMKVStorage(key, MMKV);
  return [value, setValue];
};

export default useStorage;
```

then I imported it in another file:

```javascript
import useStorage from './modelStore';

export const someComponent = () => {
  const [data, setData] = useStorage('mydata');

  console.log(global.setBoolMMKV);
  return ....
}
```

I see **undefined** in the shell where I ran 'npm start' (metro console).
I'm using ios simulator and I checked in the React Native Debug Menu that I was not currently debugging with Chrome.
'global' var can be seen since console.log(global) displays [Object].

Do you want me to test something?

Thanks in advance
Jerome

**Comment by thibmaek** [comment]
Yep exactly the same over here, happening on Android, latest RN stable, Hermes. Reproducable using code from @jeromegout 

- global logs [Object]
- global.setBoolMMKV logs undefined

Worth noting: MMKV does not work at all for me aside from this issue, every call to getMapAsync after setMapAsync returns null for me outside of the iOS simulator.

Maybe as a side question: why is setBoolMMKV bound to the global scope and not just to the native module?

**Comment by ammarahm-ed** [comment]
> why is setBoolMMKV bound to the global scope and not just to the native module?

Because this library doesn't use the native bridge, instead methods are registered in js runtime level.

Try running the example app. Make sure you did not miss any steps in the installation guide. Recheck. @thibmaek 

Also check what below method logs too:

```
console.log(global.getStringMMKV)
```

**Comment by ammarahm-ed** [comment]
@jeromegout There is nothing wrong with your code. It looks ok. Can you run the example app and see if the same is happening there?

**Comment by jeromegout** [comment]
```javascript
console.log(global.getStringMMKV)
```

returns [Function getStringMMKV]

**Comment by ammarahm-ed** [comment]
can you log both together and see what it says

```
console.log(global.setBoolMMKV);
console.log(global.getStringMMKV);
```

**Comment by jeromegout** [comment]
I don't know what I did but actually now it is working fine.
Both functions are there:

```
 LOG  [Function getStringMMKV]
 LOG  [Function setBoolMMKV]
````

**Comment by ammarahm-ed** [comment]
@jeromegout Sometimes in debug mode, the functions might not be registered although I have tried best that It does not happen, especially when you refresh app by shaking device. This will not happen in release mode. You can test just to be sure.

**Comment by ZephD** [comment]
I too am having this issue trying to clearStore(). What was the solution in the end?
The global function(s) return undefined in the application on a real Android device.

EDIT:
I followed the installation for android precisely, added the two imports and the override, and now the application crashes due to the java side of things (not the js side of things). However, i can see that the global function now exists before it crashes.
Now I just need to find out why the installation changes are crashing the app.

EDIT:
logcat logs:
```
07-02 13:40:24.699 17505 17563 F libc    : [...]react-native/ReactCommon/jsi\jsi/jsi.h:1074: facebook::jsi::String facebook::jsi::Value::getString(facebook::jsi::Runtime &) const &: assertion "isString()" failed
07-02 13:40:24.699 17505 17563 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17563 (mqt_js), pid 17505 (com.myApp)
```

EDIT:
Occurs due to using setMapAsync(key, value). The function exists, but when called with the key, it crashed the application.

EDIT:
Ah I was using a number (timestamp) as the key.
So my original problem was not following the install instructions for android. After that, i just was not using the api correctly.

A couple of suggestions:
 1) Check the existence of the global variables. If they do not exist, warn the developer to follow the install instructions.
 2) Check the key is a string and throw a (js) error if not.

**Comment by ammarahm-ed** [comment]
> I too am having this issue trying to clearStore(). What was the solution in the end?
> The global function(s) return undefined in the application on a real Android device.
> 
> EDIT:
> I followed the installation for android precisely, added the two imports and the override, and now the application crashes due to the java side of things (not the js side of things). However, i can see that the global function now exists before it crashes.
> Now I just need to find out why the installation changes are crashing the app.
> 
> EDIT:
> logcat logs:
> ```
> 07-02 13:40:24.699 17505 17563 F libc    : [...]react-native/ReactCommon/jsi\jsi/jsi.h:1074: facebook::jsi::String facebook::jsi::Value::getString(facebook::jsi::Runtime &) const &: assertion "isString()" failed
> 07-02 13:40:24.699 17505 17563 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17563 (mqt_js), pid 17505 (com.myApp)
> ```
> 
> EDIT:
> Occurs due to using setMapAsync(key, value). The function exists, but when called with the key, it crashed the application.
> 
> EDIT:
> Ah I was using a number (timestamp) as the key.
> So my original problem was not following the install instructions for android. After that, i just was not using the api correctly.
> 
> A couple of suggestions:
>  1) Check the existence of the global variables. If they do not exist, warn the developer to follow the install instructions.
>  2) Check the key is a string and throw a (js) error if not. 
> 

I will add some conditions to check that the data type is correct.
