### ISSUE TITLE
Package Name?

### ISSUE THREAD

**Issue by 8BallBomBom** [ammarahm-ed/react-native-mmkv-storage#11]
I'm looking at using this as an alternative to [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info).
Would you say this could be a good secure alternative once the encryption supports in?
Also i noticed the package name you are using is the same as the fast-storage module that you used as a base, any reason for not changing it?

**Comment by ammarahm-ed** [comment]
The package name is react-native-mmkv-storage....  On npm.  Its not react-native-fast-storage. I have changed it. On the backend, similar naming is used but it does not matter i think. .. 

And yes It will be a secure solution once encryption is added i think. MMKV is used by wechat app.. So its reliable and well mantained also.

**Comment by ammarahm-ed** [comment]
Can you explain on the package name? I still dont understand where it appeard to be same?

**Comment by 8BallBomBom** [comment]
haha no worries i was refering to the backend package name.
Only really an issue if this package along with the old package are used at the same time.
But i figured you'd probably want to change the name as this is now your project.
Just seemed odd really :)

**Comment by ammarahm-ed** [comment]
Hmm that makes sense now, I will change the names in the next release so that such a problem does not appear for someone. Good point 🌟

**Comment by ammarahm-ed** [comment]
The big question about encryption is whether to handle all the encryption from key creation to its storage etc in the library or give the users of this library a simple api to encrypt storage using a password, storage of which, "securely" would be their problem to solve. Like using something such as "react-native-keychain".

**Comment by 8BallBomBom** [comment]
A lot of people might appreciate an all inclusive package that does everything.
But you could essentially do both, maybe allow the ability to store your own keys elsewhere and just feed that into your functions on demand.
So then if you don't hand over keys it would just generate, store and use its own maybe?

**Comment by ammarahm-ed** [comment]
And what if we used react-native-keychain as a dependancy to this library and handle everything ourselves in the library? That would do the job. 

Actually implementing the logic wont be a problem but mantaining it and addressing the bugs etc would be and since react-native-keychain is well mantained maybe it could be used or a part of code from it implemented here. 

Because encryption will be a very crucial part of the library hence a robust and stable solution that does not break at some point is required. 

Hence i think more detailed survey is needed to see the available options and what might fully fulfill the purpose...

**Comment by 8BallBomBom** [comment]
It would be possible to go that route yes.
The only issue is that library expects a username and password.
Where as [this one](https://github.com/mCodex/react-native-sensitive-info) allows storing information by key + value.

**Comment by ammarahm-ed** [comment]
So are you suggesting to use https://github.com/mCodex/react-native-sensitive-info instead?  Or use part of code from it instead of the above mentioned library?

**Comment by 8BallBomBom** [comment]
An all inclusive setup would probably be a lot better but also means more maintenance.
Taking a few sections and implementing would be a nice solution.

Realm Database handles encryptions and they expect the developer to store the key themselves.
Making it that way is generally considered the norm and if you do that then you could just suggest what other modules people can use to store the encryption key if they care about security.

**Comment by ammarahm-ed** [comment]
Thats good information. Well lets see what fits in best in the current scenario.

**Comment by 8BallBomBom** [comment]
No worries, i hope to use this soon :)
