### ISSUE TITLE
[Bug] ld: library not found for -lreact-native-mmkv-storage

### ISSUE THREAD

**Issue by sejoDjoseon** [ammarahm-ed/react-native-mmkv-storage#114]
**Describe the bug**
Creating a beta or release build with Fastlane, getting this error.

**Platform Information:**
 - OS: iOS
 - React Native Version: 0.64.1
 - Library Version: 0.5.8

**Additional context**
```
gym(
        scheme: 'awesome_app',
        workspace: "./ios/awesome_app.xcworkspace",
        configuration: "Release",
        export_method:"development",
        output_directory:'./ios',
      )
```

**Comment by sejoDjoseon** [comment]
Finally I found solution to my problem. I was need to set the deployment info to iOS 11.0.
<img width="622" alt="Screenshot 2021-06-03 at 22 15 56" src="https://user-images.githubusercontent.com/19385762/120706362-47f27d00-c4b9-11eb-9908-edee53341d28.png">

**Comment by ammarahm-ed** [comment]
Glad that you fixed it.
