### ISSUE TITLE
Launch Apps Crash - dlopen failed: library "libgnustl_shared.so" not found

### ISSUE THREAD

**Issue by ththugues44** [ammarahm-ed/react-native-mmkv-storage#115]
Hello

Having followed the installation procedure according to the installation guide with react-native-reanimated. the build is going very well but when launching the application it crashes and I have an error in my console flipper 
 
 `java.lang.UnsatisfiedLinkError: dlopen failed: library" libgnustl_shared.so "not found: needed by / data / app / ~ ~ fNOxfkQGvp_GlBw51n-TjA == / com.yamoo.dating-CnarR3Xw-qZAWCud3b9VqQ == / lib / x86 / libjsc.so in namespace classloader-namespace`
 
 Have you ever had to deal with this, how did you solve it?

Thanks

**Comment by ammarahm-ed** [comment]
I haven't seen this error before. You can run the example. its on the latest RN version it works perfectly fine. Usually this error `java.lang.UnsatisfiedLinkError` has to do with proguard rules and unused code being removed.
