### ISSUE TITLE
[COMMENT] Should getAllMMKVInstanceIDs return the ID_STORE as well

### ISSUE THREAD

**Issue by netshade** [ammarahm-ed/react-native-mmkv-storage#117]
RE:
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/master/src/api.js#L276
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/4e9ecf237a11f12875dd088ab5f64c68a68dcaa5/src/mmkv/IDStore.js#L65

Sorry if this isn't the appropriate place to raise this issue, just asking questions about the code.

Should the IDStore also have its ID returned in calls to `getAllMMKVInstanceIDs`? 

Also, should `getAllMMKVInstanceIDs` be static, not instance level? It seems like this function has nothing to do with instance level data, and more to do with "all instances of MMKV stores", which seems more appropriate at the class level.

Happy to PR with either of those suggestions if deemed useful, but would want to know if that works with your plans before doing so.

**Comment by ammarahm-ed** [comment]
> Should the IDStore also have its ID returned in calls to getAllMMKVInstanceIDs?

@netshade No it should not.

> Also, should getAllMMKVInstanceIDs be static, not instance level? It seems like this function has nothing to do with instance level data, and more to do with "all instances of MMKV stores", which seems more appropriate at the class level.

If it doesn't break anything then yes, it should be moved. `MMKVStorage.getAllMMKVInstanceIDs` would be better.

> Happy to PR with either of those suggestions if deemed useful, but would want to know if that works with your plans before doing so.

You can send in a PR.
