### ISSUE TITLE
[Bug]Storage gets cleared while on custom hook. 

### ISSUE THREAD

**Issue by florind-ens** [ammarahm-ed/react-native-mmkv-storage#119]
**Describe the bug**
Hello, 
I'm encountering this issue where I can't decide it's me or the library. 
I got this tested using a CTA and worked perfectly but for what I require it I have mixed results. 

I want to cache some data via an event listener callback, so my code goes something like this. 

```
const MMKV: MMKVStorage.API = new MMKVStorage.Loader().initialize();
type T = any;
export function useStorage<S>(
  key: string
): [T | S, (value?: S | ((prevValue: S) => S)) => void] {
  const [value, setValue] = useMMKVStorage(key, MMKV) as [
    T | S,
    (value?: S | ((prevValue: S) => S)) => void
  ];
  return [value, setValue];
}

const [test, setTest] = useStorage<Map<string, string>>("CACHE_KEY");


const testing = (p) => {
    setTest((prev) =>
    //prev always is null
      prev instanceof Map ? prev.set(p.id, "never") : new Map().set(p.sid, "everytime")
    );
  };

React.useEffect(() => {
client.on("myevent", testing);
},[client])

```
So this code will end up adding only 1 element to the map, on each event. Strangely I have no issues if I execute the same code using a button click instead of a listener.

With a different approach, using the MMKV.setMap(), I'm getting different results. 
Same code as above: 

```
const testing = (p) => {
    MMKV.getMap("KEY", (error, result) => {
      console.log("result", result);
      if (result) {
        MMKV.setMap("KEY", (result as Map<string, string>).set(p.id, "never"));
      } else {
        MMKV.setMap("KEY", new Map().set(p.id, "always"));
      }
    });
  };
```
  
This will always print "result null"
Strangely enough, I have positive results setting Array values, 

```
  const testing = (p) => {
    MMKV.getArray("KEY_ARRAY", (error, result) => {
      console.log("result", result);
      if (result) {
        MMKV.setArray("KEY_ARRAY", [result, p.sid]);
      } else {
        MMKV.setArray("KEY_ARRAY", [p.sid]);
      }
    });
  };
```
This will print an array with all the ids. 

It seems like using hooks I am able to store es6 Maps but using the setMap method, I am not able to store an es6 Map.
So, setArray works as expected but the others don't. Am I missing something? 

Thanks. 

**Platform Information:**
 - OS: [e.g. iOS/Android] (IOS)
 - React Native Version [0.63.4]
 - Library Version [0.5.9 && 0.6.0] (same issue with both)

**Additional context**

**Comment by ammarahm-ed** [comment]
@florind12 Use simple objects instead of maps. Maps cannot be serialized/deserialized directly. I know it says `setMap` but it actually accepts objects
