### ISSUE TITLE
[feature request] How does one set a default value?

### ISSUE THREAD

**Issue by MasterMedo** [ammarahm-ed/react-native-mmkv-storage#121]
Normally when using the `useState` hook, one provides a default value. Can we achieve a similar behaviour with `useStorage`?

I managed to make it work like this, but it's not very elegant:
```jsx
export default function App() {
  const [categories, setCategories] = useStorage('categories');
  useEffect(() => {
    if (!categories) setCategories(['hello']);
  })
  return (
    <View style={styles.container}>
      <Text>{(categories || []).join()}</Text>
    </View>
  );
}
```

It would be better if I could do something like:
```jsx
const [categories, setCategories] = useStorage('categories', []);
```

**Comment by ammarahm-ed** [comment]
Right now you cannot set a default value because I haven't figured out how it would work if the value was deleted.

**Comment by ammarahm-ed** [comment]
Added in `v0.6.1`
