### ISSUE TITLE
[Jest] Mock the storage

### ISSUE THREAD

**Issue by alekseiSevryukov** [ammarahm-ed/react-native-mmkv-storage#124]
Hi!
I'm switching from react-native-async-storage and for unit tests I used @react-native-community/async-storage/jest/async-storage-mock. I haven't found similar approach in react-native-mmkv-storage. So what is the right way to mock it?

**Comment by ammarahm-ed** [comment]
I did not had the time to write mock tests. You can easily write mock tests for the functions that you are using in the library and send in a PR.

**Comment by alekseiSevryukov** [comment]
Ok, got it, thanks!

**Comment by Hajan39** [comment]
Do you have any examples, please? @alekseiSevryukov you did some, can you paste here a solution, please?
