### ISSUE TITLE
[Bug] Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x74ff2c183d in tid 3613 (mqt_js), pid 3455

### ISSUE THREAD

**Issue by NguyenPhatBG** [ammarahm-ed/react-native-mmkv-storage#129]
**Describe the bug**
Crash on Android devices

**To Reproduce**
iOS build and archive fine, but android crash

**Platform Information:**
"react": "17.0.1",
"react-native": "0.64.2",
 "react-native-reanimated": "^2.2.0",
  "@react-navigation/native": "^5.9.4",
"react-native-mmkv-storage": "^0.6.0"

**Comment by ammarahm-ed** [comment]
Where are you seeing the crash on android? release or debug on android? Did you follow the steps properly? Can you try and run the example in this repo and see if you can reproduce the issue there?

**Comment by NguyenPhatBG** [comment]
In my project has using react-native-reanimated library, in example is not same, I'm successful iOS platform for both debug and release mode, android seeing here to config (https://rnmmkv.vercel.app/#/?id=react-native-mmkv-storage) not work for me, I'll try in new project and hope so it's work =)). If it's not working hope you can support me! Thanks @ammarahm-ed

**Comment by ammarahm-ed** [comment]
> In my project has using react-native-reanimated library, in example is not same, I'm successful iOS platform for both debug and release mode, android seeing here to config (https://rnmmkv.vercel.app/#/?id=react-native-mmkv-storage) not work for me, I'll try in new project and hope so it's work =)). If it's not working hope you can support me! Thanks @ammarahm-ed 

If you are using reanimated, you have to take extra steps as mentioned in the installation guide to make it work.
