### ISSUE TITLE
Does not persist anything

### ISSUE THREAD

**Issue by zuhair-naqvi** [ammarahm-ed/react-native-mmkv-storage#130]
I can set and use values in the store but the stored values are set to null on reload.

```typescript
import MMKVStorage, {create} from 'react-native-mmkv-storage'

const storage = new MMKVStorage.Loader().withEncryption().initialize()
const useStorage = create(storage)

const App = (): React.ReactElement => {

  const [auth, setAuth] = useStorage('auth')

  const signIn = async () => {
    try {
      const authResult = await authorize(config.android.google)
      setAuth(authResult)
    } catch (error) {
      console.error(error)
    }
  }
...
}
```
sets the auth object but on reload it returns null.

I'm on react-native-mmkv-storage@0.6.0, rn 0.64.2 and Android Emulator on Windows

tried with both chrome debugging enabled and disabled, no effect.

Here's JSON strigified storage instance, notice `initialized `is `false` and `global.setupMMKVInstance` doesn't exist

```json
{
  "instanceID": "default",
  "initWithEncryption": true,
  "accessibleMode": "AccessibleWhenUnlocked",
  "processingMode": 1,
  "secureKeyStorage": true,
  "alias": "636f6d2e4d4d4b562e64656661756c74",
  "aliasPrefix": "com.MMKV.",
  "key": "wnqXuROe96IhWL2",
  "initialized": false,
  "options": {
    "instanceID": "default",
    "initWithEncryption": true,
    "secureKeyStorage": true,
    "accessibleMode": "AccessibleWhenUnlocked",
    "processingMode": 1,
    "aliasPrefix": "com.MMKV.",
    "alias": "636f6d2e4d4d4b562e64656661756c74",
    "key": "wnqXuROe96IhWL2",
    "initialized": false
  },
  "encryption": {
    "instanceID": "default",
    "alias": "636f6d2e4d4d4b562e64656661756c74",
    "aliasPrefix": "com.MMKV.",
    "key": "wnqXuROe96IhWL2",
    "accessibleMode": "AccessibleWhenUnlocked",
    "initialized": false,
    "options": {
      "instanceID": "default",
      "initWithEncryption": true,
      "secureKeyStorage": true,
      "accessibleMode": "AccessibleWhenUnlocked",
      "processingMode": 1,
      "aliasPrefix": "com.MMKV.",
      "alias": "636f6d2e4d4d4b562e64656661756c74",
      "key": "wnqXuROe96IhWL2",
      "initialized": false
    }
  },
  "indexer": {
    "instanceID": "default",
    "options": {
      "instanceID": "default",
      "initWithEncryption": true,
      "secureKeyStorage": true,
      "accessibleMode": "AccessibleWhenUnlocked",
      "processingMode": 1,
      "aliasPrefix": "com.MMKV.",
      "alias": "636f6d2e4d4d4b562e64656661756c74",
      "key": "wnqXuROe96IhWL2",
      "initialized": false
    },
    "strings": {
      "instanceID": "default",
      "options": {
        "instanceID": "default",
        "initWithEncryption": true,
        "secureKeyStorage": true,
        "accessibleMode": "AccessibleWhenUnlocked",
        "processingMode": 1,
        "aliasPrefix": "com.MMKV.",
        "alias": "636f6d2e4d4d4b562e64656661756c74",
        "key": "wnqXuROe96IhWL2",
        "initialized": false
      }
    },
    "numbers": {
      "instanceID": "default",
      "options": {
        "instanceID": "default",
        "initWithEncryption": true,
        "secureKeyStorage": true,
        "accessibleMode": "AccessibleWhenUnlocked",
        "processingMode": 1,
        "aliasPrefix": "com.MMKV.",
        "alias": "636f6d2e4d4d4b562e64656661756c74",
        "key": "wnqXuROe96IhWL2",
        "initialized": false
      }
    },
    "booleans": {
      "instanceID": "default",
      "options": {
        "instanceID": "default",
        "initWithEncryption": true,
        "secureKeyStorage": true,
        "accessibleMode": "AccessibleWhenUnlocked",
        "processingMode": 1,
        "aliasPrefix": "com.MMKV.",
        "alias": "636f6d2e4d4d4b562e64656661756c74",
        "key": "wnqXuROe96IhWL2",
        "initialized": false
      }
    },
    "maps": {
      "instanceID": "default",
      "options": {
        "instanceID": "default",
        "initWithEncryption": true,
        "secureKeyStorage": true,
        "accessibleMode": "AccessibleWhenUnlocked",
        "processingMode": 1,
        "aliasPrefix": "com.MMKV.",
        "alias": "636f6d2e4d4d4b562e64656661756c74",
        "key": "wnqXuROe96IhWL2",
        "initialized": false
      }
    },
    "arrays": {
      "instanceID": "default",
      "options": {
        "instanceID": "default",
        "initWithEncryption": true,
        "secureKeyStorage": true,
        "accessibleMode": "AccessibleWhenUnlocked",
        "processingMode": 1,
        "aliasPrefix": "com.MMKV.",
        "alias": "636f6d2e4d4d4b562e64656661756c74",
        "key": "wnqXuROe96IhWL2",
        "initialized": false
      }
    }
  },
  "ev": { "_registry": { "auth:onwrite": [null] } }
}

```

@icecapp any pointers on how you got it to work?

**Comment by ammarahm-ed** [comment]
> I can set and use values in the store but the stored values are set to null on reload.
> 
> ```typescript
> import MMKVStorage, {create} from 'react-native-mmkv-storage'
> 
> const storage = new MMKVStorage.Loader().withEncryption().initialize()
> const useStorage = create(storage)
> 
> const App = (): React.ReactElement => {
> 
>   const [auth, setAuth] = useStorage('auth')
> 
>   const signIn = async () => {
>     try {
>       const authResult = await authorize(config.android.google)
>       setAuth(authResult)
>     } catch (error) {
>       console.error(error)
>     }
>   }
> ...
> }
> ```
> sets the auth object but on reload it returns null.
> 
> I'm on react-native-mmkv-storage@0.6.0, rn 0.64.2 and Android Emulator on Windows
> 
> tried with both chrome debugging enabled and disabled, no effect.
> 
> Here's JSON strigified storage instance, notice `initialized `is `false` and `global.setupMMKVInstance` doesn't exist
> 
> ```json
> {
>   "instanceID": "default",
>   "initWithEncryption": true,
>   "accessibleMode": "AccessibleWhenUnlocked",
>   "processingMode": 1,
>   "secureKeyStorage": true,
>   "alias": "636f6d2e4d4d4b562e64656661756c74",
>   "aliasPrefix": "com.MMKV.",
>   "key": "wnqXuROe96IhWL2",
>   "initialized": false,
>   "options": {
>     "instanceID": "default",
>     "initWithEncryption": true,
>     "secureKeyStorage": true,
>     "accessibleMode": "AccessibleWhenUnlocked",
>     "processingMode": 1,
>     "aliasPrefix": "com.MMKV.",
>     "alias": "636f6d2e4d4d4b562e64656661756c74",
>     "key": "wnqXuROe96IhWL2",
>     "initialized": false
>   },
>   "encryption": {
>     "instanceID": "default",
>     "alias": "636f6d2e4d4d4b562e64656661756c74",
>     "aliasPrefix": "com.MMKV.",
>     "key": "wnqXuROe96IhWL2",
>     "accessibleMode": "AccessibleWhenUnlocked",
>     "initialized": false,
>     "options": {
>       "instanceID": "default",
>       "initWithEncryption": true,
>       "secureKeyStorage": true,
>       "accessibleMode": "AccessibleWhenUnlocked",
>       "processingMode": 1,
>       "aliasPrefix": "com.MMKV.",
>       "alias": "636f6d2e4d4d4b562e64656661756c74",
>       "key": "wnqXuROe96IhWL2",
>       "initialized": false
>     }
>   },
>   "indexer": {
>     "instanceID": "default",
>     "options": {
>       "instanceID": "default",
>       "initWithEncryption": true,
>       "secureKeyStorage": true,
>       "accessibleMode": "AccessibleWhenUnlocked",
>       "processingMode": 1,
>       "aliasPrefix": "com.MMKV.",
>       "alias": "636f6d2e4d4d4b562e64656661756c74",
>       "key": "wnqXuROe96IhWL2",
>       "initialized": false
>     },
>     "strings": {
>       "instanceID": "default",
>       "options": {
>         "instanceID": "default",
>         "initWithEncryption": true,
>         "secureKeyStorage": true,
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "processingMode": 1,
>         "aliasPrefix": "com.MMKV.",
>         "alias": "636f6d2e4d4d4b562e64656661756c74",
>         "key": "wnqXuROe96IhWL2",
>         "initialized": false
>       }
>     },
>     "numbers": {
>       "instanceID": "default",
>       "options": {
>         "instanceID": "default",
>         "initWithEncryption": true,
>         "secureKeyStorage": true,
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "processingMode": 1,
>         "aliasPrefix": "com.MMKV.",
>         "alias": "636f6d2e4d4d4b562e64656661756c74",
>         "key": "wnqXuROe96IhWL2",
>         "initialized": false
>       }
>     },
>     "booleans": {
>       "instanceID": "default",
>       "options": {
>         "instanceID": "default",
>         "initWithEncryption": true,
>         "secureKeyStorage": true,
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "processingMode": 1,
>         "aliasPrefix": "com.MMKV.",
>         "alias": "636f6d2e4d4d4b562e64656661756c74",
>         "key": "wnqXuROe96IhWL2",
>         "initialized": false
>       }
>     },
>     "maps": {
>       "instanceID": "default",
>       "options": {
>         "instanceID": "default",
>         "initWithEncryption": true,
>         "secureKeyStorage": true,
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "processingMode": 1,
>         "aliasPrefix": "com.MMKV.",
>         "alias": "636f6d2e4d4d4b562e64656661756c74",
>         "key": "wnqXuROe96IhWL2",
>         "initialized": false
>       }
>     },
>     "arrays": {
>       "instanceID": "default",
>       "options": {
>         "instanceID": "default",
>         "initWithEncryption": true,
>         "secureKeyStorage": true,
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "processingMode": 1,
>         "aliasPrefix": "com.MMKV.",
>         "alias": "636f6d2e4d4d4b562e64656661756c74",
>         "key": "wnqXuROe96IhWL2",
>         "initialized": false
>       }
>     }
>   },
>   "ev": { "_registry": { "auth:onwrite": [null] } }
> }
> 
> ```
> 
> @icecapp any pointers on how you got it to work?
> 
> 
If you are using expo, this library will not work.
You have not installed the library correctly. Check the docs and follow the guide there for installation on Android.

**Comment by zuhair-naqvi** [comment]
I can confirm this has been resolved. It was my bad I had assumed that the android manual instructions were not needed when autolinking.
