### ISSUE TITLE
[iOS] App group/Share extension support?

### ISSUE THREAD

**Issue by humaidk2** [ammarahm-ed/react-native-mmkv-storage#131]
Hi,

I wanted to know if there is support for sharing storage between app groups. I'm trying to share storage between
the main target and share extension target.

From what I found, it looks like the library is using /Library to store which is not accessible by both the main target and share extension.

Do you have any ideas on how to get this to work?

**Comment by ammarahm-ed** [comment]
> Hi,
> 
> I wanted to know if there is support for sharing storage between app groups. I'm trying to share storage between
> the main target and share extension target.
> 
> From what I found, it looks like the library is using /Library to store which is not accessible by both the main target and share extension.
> 
> Do you have any ideas on how to get this to work?

I will add support for it in the next release using app groups.

**Comment by humaidk2** [comment]
Question for you,

To access mmkv data from some extension, I  initialized mmkv natively using your suggestion [here](https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/54#issuecomment-758433805)

which is also mentioned in mmkv's [docs](https://github.com/Tencent/MMKV/wiki/iOS_tutorial)

But I was still unable to access the same storage as the main app

I'm guessing the issue is that I need to use <MMKVAppExtension/MMKV.h> as mentioned in their docs
[https://github.com/Tencent/MMKV/wiki/iOS_setup#installation](https://github.com/Tencent/MMKV/wiki/iOS_setup#installation)

Which means I somehow need a copy of this library that uses MMKVAppExtension for the extension part.

Is there a better way of doing this?

**Comment by ammarahm-ed** [comment]
> Question for you,
> 
> To access mmkv data from some extension, I  initialized mmkv natively using your suggestion [here](https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/54#issuecomment-758433805)
> 
> which is also mentioned in mmkv's [docs](https://github.com/Tencent/MMKV/wiki/iOS_tutorial)
> 
> But I was still unable to access the same storage as the main app
> 
> I'm guessing the issue is that I need to use <MMKVAppExtension/MMKV.h> as mentioned in their docs
> [https://github.com/Tencent/MMKV/wiki/iOS_setup#installation](https://github.com/Tencent/MMKV/wiki/iOS_setup#installation)
> 
> Which means I somehow need a copy of this library that uses MMKVAppExtension for the extension part.
> 
> Is there a better way of doing this?
> 
> 

I am using it in my App in Share Extension so it does work although I am on older version 0.4 of this library. I will let you know what I did. Basically you need to set the correct path which can be accessed by extension and the app.

**Comment by ammarahm-ed** [comment]
Here's how you can do it:

```objc
NSString *myGroupID = @"your.group.id"; // the group dir that can be accessed by App & extensions

NSString *groupDir = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:myGroupID].path;
NSString *rootDir = [groupDir stringByAppendingPathComponent:@"mmkv"];
      
// Do not include this directory in cloud backups.
NSError *error = nil;
NSURL *url = [NSURL fileURLWithPath:rootDir isDirectory:YES];
[url setResourceValue:[NSNumber numberWithBool:YES] forKey:NSURLIsExcludedFromBackupKey error:&error];
        
// Set the groupDir
[MMKV initializeMMKV:nil groupDir:rootDir logLevel:MMKVLogInfo];
    
```
And update the `migrate` function in the same file as follows:

```objc
- (void)migrate {
    MMKV *kv = [MMKV mmkvWithID:@"mmkvIdStore" mode:MMKVMultiProcess];

```

You have to make these changes here: 
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/67eaf54bd0d4b5a99c9ed15c389606600e32021f/ios/MMKVNative.mm#L71

And in JS

```
new MMKVStorage.Loader().setProcessingMode(MODES.MULTI_PROCESS).initialize();
```

**Comment by ammarahm-ed** [comment]
Did the app compile normally without errors after you made the changes. You don't need to use MMKVAppExtension. Can you read/write in extension and in app separately? Do the values persist in both App and Extension after restarting?

**Comment by humaidk2** [comment]
Thanks a lot, really appreciate the answer.

 I did intialize it the same way but I didn't append the "mmkv" to the path.

Also, I did it in a separate native module, since I thought mmkv uses a single instance (singleton), which did kinda work but kept erasing all my data.

I'll try it out asap, thanks for the help and the awesome library.

**Comment by humaidk2** [comment]
HI, 

I've just tested it and it doesn't seem to be working.

Maybe it has something to do with redux-persist or encryption.

I did share connect the extension by app group and keychain.

**Comment by r3vsan** [comment]
I'm interested too for my react-native app extension! any news? 

I'm trying to write a custom (swift) ViewController extending the ReactShareViewController of 'react-native-share-menu' library (https://https://github.com/meedan/react-native-share-menu) in order to properly initialize MMKV with the same group directory of the main app.

I think that the correct way is overrid the viewDidLoad method and insert here the mmkv initialization instructions. But i don't know which instructions to use in swift and what import...

**Comment by humaidk2** [comment]
I used the same stuff, got it to work with keychain for now, but I think I'll plugin mmkv later(not sure about encryption support).

You can put it in ShareMenuManager.m

Small notes: be-careful of 120mb limit, only load the data you need, debug is more consuming so it might not work as well as release,  rn-share-menu does not work with some apps like telegram, rn-share-menu hasn't had a release for a year

I think a plugin library for all the share stuff would be really good, something that combines rn-share-menu/rn-share-extension with rn-mmkv-storage and has support for encryption, multi share, and share sheet support. If I get the time, I might give it a go.

**Comment by ammarahm-ed** [comment]
@humaidk2  Were you using MMKV in both app and extension with encryption when you tried it out? You are saying that it worked to some level but your data kept getting erased, so basically it worked but when you would write data on app, it would not appear in extension and when you would write data in extension, it would not appear in the app?

**Comment by humaidk2** [comment]
Yeah exactly,

I use redux and the store would persist in both, but i could never load the data from one to the other. I an definitely using app groups and they were connected.

Whenever I launched the share extension,  it would erase the mmkv store of my main app.

**Comment by ammarahm-ed** [comment]
> Yeah exactly,
> 
> I use redux and the store would persist in both, but i could never load the data from one to the other. I an definitely using app groups and they were connected.
> 
> Whenever I launched the share extension, it would erase the mmkv store of my main app.

I understand now why that happened. Actually the library uses an `IDStore` internally which needs to initialize on `multi process` if it is to be accessed between app and the extension. Since the `IDStore` is initialized on a single process mode at the moment, it cannot be accessed in both app and extension simultaneously. The IDStore` consists the information about each instance and how to decrypt it. 

To fix this, all that needs to be done is to init the `IDStore` on multi process mode so both app and share extension can access it and decrypt the storage instance.

**Comment by r3vsan** [comment]
> To fix this, all that needs to be done is to init the `IDStore` on multi process mode so both app and share extension can access it and decrypt the storage instance.

Thanks, what is the correct way to do this initialization? During initializeMMKV in MMKVNative.mm or directly from js code?

**Comment by ammarahm-ed** [comment]
@r3vsan  See the updated comment above for instructions. Let me know here if it works properly so I can close this issue.
