### ISSUE TITLE
[Bug] Build fails in AppCenter - ':react-native-mmkv-storage:generateJsonModelRelease'. > java.lang.NullPointerException 

### ISSUE THREAD

**Issue by kyle-ssg** [ammarahm-ed/react-native-mmkv-storage#132]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8608314/124462728-e3f9f780-dd89-11eb-8a3b-32aaca91464f.png)

**To Reproduce**
Attempt to build an application using mmkv in appcenter

**Expected behavior**
The app builds

**Screenshots**
![image](https://user-images.githubusercontent.com/8608314/124462954-186db380-dd8a-11eb-8c62-6875cf1164d7.png)

**Platform Information:**
 - OS: Android
 - React Native Version 0.64
 - Library Version 0.6.0

This may be due to the fact that AppCenter is attempting to build the application from a parent directory and perhaps the above task is using a relative directory?

**Comment by ammarahm-ed** [comment]
> **Describe the bug**
> ![image](https://user-images.githubusercontent.com/8608314/124462728-e3f9f780-dd89-11eb-8a3b-32aaca91464f.png)
> 
> 
> **To Reproduce**
> Attempt to build an application using mmkv in appcenter
> 
> **Expected behavior**
> The app builds
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/8608314/124462954-186db380-dd8a-11eb-8c62-6875cf1164d7.png)
> 
> **Platform Information:**
>  - OS: Android
>  - React Native Version 0.64
>  - Library Version 0.6.0
> 
> This may be due to the fact that AppCenter is attempting to build the application from a parent directory and perhaps the above task is using a relative directory?

 I haven't used Appcenter before. There is some configuration problem causing this to happen. The library uses relative paths for all files/directories.

**Comment by kyle-ssg** [comment]
Unfortunately there's nothing you can really configure in appcenter, it runs something along the lines of 

```
[command]/Users/runner/work/1/s/mobile/android/gradlew -DAPPCENTER_KEYSTORE_PASSWORD=*** -DMOBILECENTER_KEYSTORE_PASSWORD=*** -DAPPCENTER_KEYSTORE_FILE_ID=pw-key.keystore -DMOBILECENTER_KEYSTORE_FILE_ID=pw-key.keystore -DAPPCENTER_KEY_ALIAS=*** -DMOBILECENTER_KEY_ALIAS=*** -DAPPCENTER_KEY_PASSWORD=*** -DMOBILECENTER_KEY_PASSWORD=*** -DAPPCENTER_BUILD_VERSION=*** -DMOBILECENTER_BUILD_VERSION=*** -p mobile/android clean :app:assembleProdRelease

```

The weird thing is it seems I can run the following locally fine:

```
-p mobile/android clean :app:assembleProdRelease
```

I can't actually see it running a generateJsonModelRelease task when doing this though, just 

```
Task :react-native-mmkv-storage:externalNativeBuildRelease
```

If you point me in the direction to where / how generateJsonModelRelease is run I could perhaps try and figure it out.

**Comment by ammarahm-ed** [comment]
> Unfortunately there's nothing you can really configure in appcenter, it runs something along the lines of 
> 
> ```
> [command]/Users/runner/work/1/s/mobile/android/gradlew -DAPPCENTER_KEYSTORE_PASSWORD=*** -DMOBILECENTER_KEYSTORE_PASSWORD=*** -DAPPCENTER_KEYSTORE_FILE_ID=pw-key.keystore -DMOBILECENTER_KEYSTORE_FILE_ID=pw-key.keystore -DAPPCENTER_KEY_ALIAS=*** -DMOBILECENTER_KEY_ALIAS=*** -DAPPCENTER_KEY_PASSWORD=*** -DMOBILECENTER_KEY_PASSWORD=*** -DAPPCENTER_BUILD_VERSION=*** -DMOBILECENTER_BUILD_VERSION=*** -p mobile/android clean :app:assembleProdRelease
> 
> ```
> 
> The weird thing is it seems I can run the following locally fine:
> 
> ```
> -p mobile/android clean :app:assembleProdRelease
> ```
> 
> I can't actually see it running a generateJsonModelRelease task when doing this though, just 
> 
> ```
> Task :react-native-mmkv-storage:externalNativeBuildRelease
> ```
> 
> If you point me in the direction to where / how generateJsonModelRelease is run I could perhaps try and figure it out.

Try running gradlew with `--no-daemon --no-parallel` flags and see if that fixes the problem

**Comment by kyle-ssg** [comment]
Unfortunately you can't configure how gradlew is called with appcenter, I think adding the following to build.gradle may match that though ?

```
org.gradle.daemon=false
org.gradle.parallel=false
```

**Comment by ammarahm-ed** [comment]
> Unfortunately you can't configure how gradlew is called with appcenter, I think adding the following to build.gradle may match that though ?
> 
> ```
> org.gradle.daemon=false
> org.gradle.parallel=false
> ```

Yes, along with that, you can look at the `build.gradle` file of the library to see if there is some path or anything that is causing the problem.

**Comment by ammarahm-ed** [comment]
The issue might also be because the library is using older version of gradle. You can fork and update the version to 4.1.0 in build.gradle to see if that would help

**Comment by kyle-ssg** [comment]
I can see reference to cmake in the build.gradle
```
  externalNativeBuild {
      cmake {
          path "./src/main/rnmmkv/CMakeLists.txt"
          version "3.8.0+"
      }
  } 
```

This url seems to suggest updating this : https://gitlab.kitware.com/cmake/cmake/-/issues/22021


I wonder whether that's it?'


I'll do a quick patch and try in appcenter to see if updating to .18+ solves it, the error seems very similar to what I reported.

**Comment by ammarahm-ed** [comment]
> I can see reference to cmake in the build.gradle
> ```
>   externalNativeBuild {
>       cmake {
>           path "./src/main/rnmmkv/CMakeLists.txt"
>           version "3.8.0+"
>       }
>   } 
> ```
> 
> This url seems to suggest updating this : https://gitlab.kitware.com/cmake/cmake/-/issues/22021
> 
> 
> I wonder whether that's it?

I guess so but I can not confirm. You can try to change cmake version and see if that helps. It surely is some incompatibility issue between cmake and the ndk version being used in appcenter

**Comment by kyle-ssg** [comment]
Hmm thats a bit strange if so, because both locally and in appcenter it's forced to 22.1.7171670, ill run a build now and see what happens.

**Comment by ammarahm-ed** [comment]
> > I can see reference to cmake in the build.gradle
> > ```
> >   externalNativeBuild {
> >       cmake {
> >           path "./src/main/rnmmkv/CMakeLists.txt"
> >           version "3.8.0+"
> >       }
> >   } 
> > ```
> > 
> > This url seems to suggest updating this : https://gitlab.kitware.com/cmake/cmake/-/issues/22021
> > 
> > 
> > I wonder whether that's it?
> 
> I guess so but I can not confirm. You can try to change cmake version and see if that helps. It surely is some incompatibility issue between cmake and the ndk version being used in appcenter.

It might be due to version of gradle used in library which is old. Try using 4.1.0 along with newer version of cmake.

**Comment by kyle-ssg** [comment]
Unfortunately none of the above worked:

- I've tried upping the gradle version to 4.1.0
- Attempting to update cmake in build gradle throws an error about versions
- I've tried adjusting the ndk version to 20.1.5948944 to match the example app

**Comment by kyle-ssg** [comment]
One Thing I notice is that https://github.com/actions/virtual-environments/blob/macOS-10.15/20210626.1/images/macos/macos-10.15-Readme.md The VM seems to be have a very new version of cmake, I wonder if this is being used over the one that's defined in Android/sdk ?

**Comment by ammarahm-ed** [comment]
I think that android studio uses it's own cmake version unless you give a path in root project to another cmake installation

**Comment by kyle-ssg** [comment]
Wow! Ok I'm getting somewhere, I brew installed cmake and can now reporoduce the error locally!

![image](https://user-images.githubusercontent.com/8608314/124484889-e23d2d80-dda3-11eb-9800-37cf3ed4e0b2.png)

**Comment by ammarahm-ed** [comment]
> Wow! Ok I'm getting somewhere, I brew installed cmake and can now reporoduce the error locally!
> 
> ![image](https://user-images.githubusercontent.com/8608314/124484889-e23d2d80-dda3-11eb-9800-37cf3ed4e0b2.png)
> 
I think you need to point to the correct cmake version by using `cmake.dir` in project `gradle.properties` file

**Comment by kyle-ssg** [comment]
Hmm, the problem with that is that I don't really know what version they have installed. I guess I could trigger a build in appcenter and do ls ~/Library/Android/sdk/cmake then set it in a followup build

**Comment by kyle-ssg** [comment]
I can confirm now that if a machine has cmake ~3.20.0 installed it will interfere with this lib from working.

For reference (as im sure people will use AppCenter)

As a quick and dirty way of sorting this, I brew uninstall cmake on the appcenter osx VM on postinstall via a shell script (I don't think it's even used, at least for react-native builds).

```
#!/bin/bash
if [ -z "$APPCENTER_BUILD_ID" ]
then
else
    echo "APPCENTER_BUILD_ID is defined"
    brew uninstall cmake
fi
```

**Comment by amk-cb** [comment]
I am this error too in App center, please guide how to use this script.

**Comment by andrei-tofan** [comment]
I can confirm that `brew uninstall cmake` fixes the issue.

**Comment by kyle-ssg** [comment]
Note on this, in 0.70 this issue is resolved but you have to remove the brew uninstall cmake fix. Keeping this in brings up the issue again
