### ISSUE TITLE
[Feature Request] getAllKeys method

### ISSUE THREAD

**Issue by bombillazo** [ammarahm-ed/react-native-mmkv-storage#134]
Various storage libraries give you a method to retrieve an array of the store keys. This is useful for doing things like data syncing in an app when you don't have the keys known upfront. 
```js
let storeKeys= MMKV.getAllKeys() // ['envData', 'performanceId', 'myapp.userSecret', 'myapp.userName']
```

A great feature would also be to pass in a prefix to fetch only keys I know have a prefix set
```js
const APP_KEY_PREFIX = 'myapp.';
let storeKeys= MMKV.getAllKeys(APP_KEY_PREFIX) // ['myapp.userSecret', 'myapp.userName']
```

**Comment by ammarahm-ed** [comment]
> Various storage libraries give you a method to retrieve an array of the store keys. This is useful for doing things like data syncing in an app when you don't have the keys known upfront. 
> ```js
> let storeKeys= MMKV.getAllKeys() // ['envData', 'performanceId', 'myapp.userSecret', 'myapp.userName']
> ```
> 
> A great feature would also be to pass in a prefix to fetch only keys I know have a prefix set
> ```js
> const APP_KEY_PREFIX = 'myapp.';
> let storeKeys= MMKV.getAllKeys(APP_KEY_PREFIX) // ['myapp.userSecret', 'myapp.userName']
> ```
> 

Check the docs.

**Comment by bombillazo** [comment]
Ok, I had checked but the name Querying and Indexing threw me off. Just what I was looking for, thanks.
