### ISSUE TITLE
[Question] Is iOS11 required?

### ISSUE THREAD

**Issue by ClayC-WeatherBug** [ammarahm-ed/react-native-mmkv-storage#135]
Is iOS11 required for usage with this library? I have to support iOS10 on my current project and would like to use this library. It seems that after patching the podspec that everything works fine, but does anyone know why the change was made to require iOS11? I'm hoping to avoid having something blow up in production if iOS11 is required.

**Comment by ammarahm-ed** [comment]
> Is iOS11 required for usage with this library? I have to support iOS10 on my current project and would like to use this library. It seems that after patching the podspec that everything works fine, but does anyone know why the change was made to require iOS11? I'm hoping to avoid having something blow up in production if iOS11 is required.

Some symbols are not resolved when targeting iOS 10 or lower. You can target iOS 10 and trying building. It should work technically although you will get a warning that mmkv library is targeting iOS 11 which should not cause any problem in runtime

**Comment by ClayC-WeatherBug** [comment]
Thanks - I modified the podfile to target 10 and got things building. Was the upgrade done to fix any specific bug, or was it just that the underlying MMKV library targets 11?

**Comment by ammarahm-ed** [comment]
> Thanks - I modified the podfile to target 10 and got things building. Was the upgrade done to fix any specific bug, or was it just that the underlying MMKV library targets 11?

It is required by JSI.

**Comment by ClayC-WeatherBug** [comment]
It is? I was able to run on a react-native app with 0.63.3 and use the JSI with iOS 10 and this package. I haven't seen anything in the JSI thread or docs specifying that iOS 11 is required?

**Comment by ammarahm-ed** [comment]
> It is? I was able to run on a react-native app with 0.63.3 and use the JSI with iOS 10 and this package. I haven't seen anything in the JSI thread or docs specifying that iOS 11 is required?

The build fails if I target iOS 10 or lower on iOS. I will still look into it.

**Comment by ammarahm-ed** [comment]
> > It is? I was able to run on a react-native app with 0.63.3 and use the JSI with iOS 10 and this package. I haven't seen anything in the JSI thread or docs specifying that iOS 11 is required?
> 
> The build fails if I target iOS 10 or lower on iOS in the library. I will still look into it.

**Comment by ClayC-WeatherBug** [comment]
Oh okay, thanks for looking into it. Please let me know if I can be of any help. It seems to work for me without issues. I did see that on GitHub the main react-native repo now claims to only support iOS11+, but on NPM they say they are still supporting iOS10+. I imagine that they will be dropping 10 support soon or have already begun the process, but it seems like things do still build in some cases.

**Comment by ammarahm-ed** [comment]
> Oh okay, thanks for looking into it. Please let me know if I can be of any help. It seems to work for me without issues. I did see that on GitHub the main react-native repo now claims to only support iOS11+, but on NPM they say they are still supporting iOS10+. I imagine that they will be dropping 10 support soon or have already begun the process, but it seems like things do still build in some cases.

Yes they do but react native does not expect you to use JSI at the moment. There is no documentation and it's not stable yet. If you downgrade the iOS version in the library, the app will stop building. The error comes from jsi.cpp file so that's the only solution for now.
