### ISSUE TITLE
[Question] is it possible to restore backup without restarting?

### ISSUE THREAD

**Issue by Kiura** [ammarahm-ed/react-native-mmkv-storage#136]
[Question] is it possible to restore backup without restarting?

Currently, it is not possible to manually restart an application, so it is annoying to ask the users to restart the app after a backup is restored, can this be done without restarting the app?

**Comment by ammarahm-ed** [comment]
> [Question] is it possible to restore backup without restarting?
> 
> Currently, it is not possible to manually restart an application, so it is annoying to ask the users to restart the app after a backup is restored, can this be done without restarting the app?

What do you mean by restoring a backup? How are you doing it?

**Comment by Kiura** [comment]
> What do you mean by restoring a backup? How are you doing it?

I mean restoring a backup on another device, this is useful when a user wants to restore all data on a new phone.

I back up a database (zip the mmkv folder) and restore it on another device (unzip all files to the mmkv folder). After unzipping I need to restart the application so the data is fetched and the MMKV DB has data from the backup.

Ideally, I would like to avoid restarting the application. The code could be something like this:

```js
let loader = new MMKVStorage.Loader()
this.db = loader
      .withEncryption()
      .initialize();
```

and once the backup is restored, I can simply run `this.db.reinitialize()`

**Comment by ammarahm-ed** [comment]
> > What do you mean by restoring a backup? How are you doing it?
> 
> I mean restoring a backup on another device, this is useful when a user wants to restore all data on a new phone.
> 
> I back up a database (zip the mmkv folder) and restore it on another device (unzip all files to the mmkv folder). After unzipping I need to restart the application so the data is fetched and the MMKV DB has data from the backup.
> 
> Ideally, I would like to avoid restarting the application. The code could be something like this:
> 
> ```js
> let loader = new MMKVStorage.Loader()
> this.db = loader
>       .withEncryption()
>       .initialize();
> ```
> 
> and once the backup is restored, I can simply run `this.db.reinitialize()`

I think there is a way to do this. Not implemented yet though. We need to implement a `clearMemoryCache` method which will fix the problem.

**Comment by Kiura** [comment]
> I think there is a way to do this. Not implemented yet though. We need to implement a `clearMemoryCache` method which will fix the problem.

This is great, we are releasing our app as it is in a month. I don't expect this to be fixed by then, but do you think this will be implemented any time soon? Like in 3-4 months? 😅

BTW, the library is great, works very well with mobx and the ONLY secure storage that works well with it. Thank you for making it :)

**Comment by ammarahm-ed** [comment]
> > I think there is a way to do this. Not implemented yet though. We need to implement a `clearMemoryCache` method which will fix the problem.
> 
> This is great, we are releasing our app as it is in a month. I don't expect this to be fixed by then, but do you think this will be implemented any time soon? Like in 3-4 months? 😅
> 
> BTW, the library is great, works very well with mobx and the ONLY secure storage that works well with it. Thank you for making it :)
> 
> 

I will add it soon. Maybe in a few days.

**Comment by Kiura** [comment]
Oh, this is great, thank you 😊

**Comment by ammarahm-ed** [comment]
@Kiura You can test using master branch. There is a new method, `storage.clearMemoryCache` which you can use to reset the database.

**Comment by Kiura** [comment]
Oh, this is great, I will test it this evening after work :) thank you for adding the feature in a super-fast manner

**Comment by Kiura** [comment]
Hey Ahmed,
Unfortunately, it is not working for me, here is an example of how I restore the backup:
```js

const loader = new MMKVStorage.Loader();
const MMKV = loader
  .withEncryption()
  .encryptWithCustomKey("key", true, "key2")
  .initialize()

// restore backup (replace the mmkv folder with the backed up one)
await  MMKV.clearMemoryCache(); // returns true
await MMKV.indexer.getKeys(); // returns {}

**Comment by ammarahm-ed** [comment]
> Hey Ahmed,
> Unfortunately, it is not working for me, here is an example of how I restore the backup:
> 
> ```js
> const loader = new MMKVStorage.Loader();
> const MMKV = loader
>   .withEncryption()
>   .encryptWithCustomKey("key", true, "key2")
>   .initialize()
> 
> // restore backup (replace the mmkv folder with the backed up one)
> await  MMKV.clearMemoryCache(); // returns true
> await MMKV.indexer.getKeys(); // returns {}
> ```
Well, does it work if you only refresh the app (by shaking in debug mode), not restart the app?

**Comment by Kiura** [comment]
> Well, does it work if you only refresh the app (by shaking in debug mode), not restart the app?

No, it only works if I fully quit the application and open it again

**Comment by ammarahm-ed** [comment]
> > Well, does it work if you only refresh the app (by shaking in debug mode), not restart the app?
> 
> No, it only works if I fully quit the application and open it again

Then it might not be possible to achieve what you need without restarting the app. Another way would be that you backup the db to a json file via JavaScript instead of copying the mmkv folder and making a zip file.

**Comment by Kiura** [comment]
Thank you for the time you spent on it, I really appreciate it :)
And the `json` approach is brilliant! I will probably go this way, export as `json` to a password-protected zip for security.

**Comment by ammarahm-ed** [comment]
@Kiura although there might be a possible way. Try this:

```js

c@Kiura although there might be a possible way.onst loader = new MMKVStorage.Loader();
const MMKV = loader
  .withEncryption()
  .encryptWithCustomKey("key", true, "key2")
  .initialize()

// restore backup (replace the mmkv folder with the backed up one)
await  MMKV.clearMemoryCache(); // returns true
global.initializeMMKV();
await MMKV.indexer.getKeys(); // returns {}

**Comment by Kiura** [comment]
> @Kiura although there might be a possible way. Try this:

I will try this approach and report back, if this doesn't work we can close the issue :)

**Comment by ammarahm-ed** [comment]
If it does not work, finally try this:

```js
const loader = new MMKVStorage.Loader();
const MMKV = loader
  .withEncryption()
  .encryptWithCustomKey("key", true, "key2")
  .initialize()

// restore backup (replace the mmkv folder with the backed up one)
await  MMKV.clearMemoryCache(); // returns true
global.initializeMMKV();
global.setupMMKVInstance("default", 1, "YOUR_KEY", "");
await MMKV.indexer.getKeys(); // returns {}

```

**Comment by Kiura** [comment]
tried both, doesn't work unfortunately, maybe it is not possible?:
https://github.com/Tencent/MMKV/issues/656

I will open an issue there to see if it possible, currently I will use a JSON file as you suggested :)

**Comment by Kiura** [comment]
I created an issue for anyone who wants to follow up on this, I created an issue: https://github.com/Tencent/MMKV/issues/720
