### ISSUE TITLE
[Bug] global.setBoolMMKV is not a function while using clearStore()

### ISSUE THREAD

**Issue by kuraydev** [ammarahm-ed/react-native-mmkv-storage#137]
**Describe the bug**
While using `clearStore` just throws the error. However, `removeItem` function is working well without problem.

**To Reproduce**
1. While using `clearStore()` function simply throws a crash (look at the screenshots)
2. On the console its error is: 
```jsx
Error: EISDIR: illegal operation on a directory, read at Object.readSync
```

**Screenshots**

### The Crash
![CleanShot 2021-07-13 at 10 47 22@2x](https://user-images.githubusercontent.com/6813862/125515752-bba1bee4-0d76-47c8-8e25-3e0795bc98a1.png)

### Console Error
<img width="384" alt="CleanShot 2021-07-13 at 10 49 45@2x" src="https://user-images.githubusercontent.com/6813862/125515904-56fc327f-a1ba-4131-99b8-757fbeea0f44.png">

**Comment by ammarahm-ed** [comment]
I will investigate this. Are you on the latest version. Did you try to call `storage.setBool`, does it also cause a crash for you?

Update: i tested and the `clearStore` function is working correctly for me. No issues caused.

**Comment by kuraydev** [comment]
@ammarahm-ed I will try to create a reproducible example for you. 

It was working for me but with the latest version, it just crashes on my project. Also, we use all of the functions from the library but just the `clearStore` function makes the crush. Maybe it is only on dev mode but I did not test it on production/release mode.

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed I will try to create a reproducible example for you. 
> 
> It was working for me but with the latest version, it just crashes on my project. Also, we use all of the functions from the library but just the `clearStore` function makes the crush. Maybe it is only on dev mode but I did not test it on production/release mode.

An example would be great

**Comment by kuraydev** [comment]
@ammarahm-ed Do you have any idea that I could broke it with a saved data or any use-case like that?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed Do you have any idea that I could broke it with a saved data or any use-case like that?

No I don't think so. It should not break like that. You can test by calling `console.log(global.setBoolMMKV)` to check if you are getting a function or not then call clearStore function.

Maybe try it on real device. It could be an error only happening in simulator?

You can also run `rm -rf node_modules` then run yarn/npm. Clean your ios project and pod files. Run pod install.

**Comment by ammarahm-ed** [comment]
Your this error `Error: EISDIR: illegal operation on a directory, read at Object.readSync` is related to npm and your node_modules folder. Not the library or your app.

Read here: https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a

**Comment by kuraydev** [comment]
@ammarahm-ed You're right. I guess this is a wrong cache error. I simply clean the everything; `watchman`, `node_modules`, `bundle reset cache` and it works.
Thank you so much sir!
Awesome library, literally I replaced MMKV instead of AsyncStorage.
