### ISSUE TITLE
[Bug]  MMKV not working in React Native 0.64.2

### ISSUE THREAD

**Issue by jgalianoz** [ammarahm-ed/react-native-mmkv-storage#138]
**Describe the bug**
I updated the react version to 0.64.2 but when I try to get value using for example MMKV.getBoolAsync("myBooleanValue"); I don't receive the data and my app obtain a blank screen because my variable doesn't exist/

**Screenshots**
![image](https://user-images.githubusercontent.com/12010942/125536997-a771773d-3c6e-49ab-8e6f-5d3106832464.png)

**Platform Information:**
"react": "17.0.1",
"react-native": "0.64.2",
"react-native-mmkv-storage": "^0.6.0"

**Comment by bombillazo** [comment]
I think something big inside MMKV broke because NOTHING regarding the API functions works for me now. I can initialize the store with the Loader but nothing else seems to work, _except_ the hooks. I even tried running 1 previous version of the mmkv package to see if it worked.

![image](https://user-images.githubusercontent.com/44002321/125547955-151564aa-7345-46c9-92ba-c2eb926790f2.png)

Console Output
```
API {
  "accessibleMode": "AccessibleWhenUnlocked",
  "alias": null,
  "aliasPrefix": "com.MMKV.",
  "encryption": encryption {
    "accessibleMode": "AccessibleWhenUnlocked",
    "alias": null,
    "aliasPrefix": "com.MMKV.",
    "initialized": false,
    "instanceID": "default",
    "key": null,
    "options": Object {
      "accessibleMode": "AccessibleWhenUnlocked",
      "alias": null,
      "aliasPrefix": "com.MMKV.",
      "initWithEncryption": false,
      "initialized": false,
      "instanceID": "default",
      "key": null,
      "processingMode": 1,
      "secureKeyStorage": false,
    },
  },
  "ev": EventManager {
    "_registry": Object {},
  },
  "getArray": [Function anonymous],
  "getBool": [Function anonymous],
  "getInt": [Function anonymous],
  "getMap": [Function anonymous],
  "getMultipleItems": [Function anonymous],
  "getString": [Function anonymous],
  "indexer": indexer {
    "MMKV": undefined,
    "arrays": arrayIndex {
      "MMKV": undefined,
      "instanceID": "default",
      "options": Object {
        "accessibleMode": "AccessibleWhenUnlocked",
        "alias": null,
        "aliasPrefix": "com.MMKV.",
        "initWithEncryption": false,
        "initialized": false,
        "instanceID": "default",
        "key": null,
        "processingMode": 1,
        "secureKeyStorage": false,
      },
    },
    "booleans": boolIndex {
      "MMKV": undefined,
      "instanceID": "default",
      "options": Object {
        "accessibleMode": "AccessibleWhenUnlocked",
        "alias": null,
        "aliasPrefix": "com.MMKV.",
        "initWithEncryption": false,
        "initialized": false,
        "instanceID": "default",
        "key": null,
        "processingMode": 1,
        "secureKeyStorage": false,
      },
    },
    "instanceID": "default",
    "maps": mapsIndex {
      "MMKV": undefined,
      "instanceID": "default",
      "options": Object {
        "accessibleMode": "AccessibleWhenUnlocked",
        "alias": null,
        "aliasPrefix": "com.MMKV.",
        "initWithEncryption": false,
        "initialized": false,
        "instanceID": "default",
        "key": null,
        "processingMode": 1,
        "secureKeyStorage": false,
      },
    },
    "numbers": numbersIndex {
      "MMKV": undefined,
      "instanceID": "default",
      "options": Object {
        "accessibleMode": "AccessibleWhenUnlocked",
        "alias": null,
        "aliasPrefix": "com.MMKV.",
        "initWithEncryption": false,
        "initialized": false,
        "instanceID": "default",
        "key": null,
        "processingMode": 1,
        "secureKeyStorage": false,
      },
    },
    "options": Object {
      "accessibleMode": "AccessibleWhenUnlocked",
      "alias": null,
      "aliasPrefix": "com.MMKV.",
      "initWithEncryption": false,
      "initialized": false,
      "instanceID": "default",
      "key": null,
      "processingMode": 1,
      "secureKeyStorage": false,
    },
    "strings": stringsIndex {
      "MMKV": undefined,
      "instanceID": "default",
      "options": Object {
        "accessibleMode": "AccessibleWhenUnlocked",
        "alias": null,
        "aliasPrefix": "com.MMKV.",
        "initWithEncryption": false,
        "initialized": false,
        "instanceID": "default",
        "key": null,
        "processingMode": 1,
        "secureKeyStorage": false,
      },
    },
  },
  "initWithEncryption": false,
  "initialized": false,
  "instanceID": "default",
  "key": null,
  "options": Object {
    "accessibleMode": "AccessibleWhenUnlocked",
    "alias": null,
    "aliasPrefix": "com.MMKV.",
    "initWithEncryption": false,
    "initialized": false,
    "instanceID": "default",
    "key": null,
    "processingMode": 1,
    "secureKeyStorage": false,
  },
  "processingMode": 1,
  "secureKeyStorage": false,
  "setArray": [Function anonymous],
  "setBool": [Function anonymous],
  "setInt": [Function anonymous],
  "setMap": [Function anonymous],
  "setString": [Function anonymous],
}
SET RESULT -- undefined
KEY VALUE -- undefined
```

Platform Information:
"react": "16.13.1",
"react-native": "0.63.4"
"react-native-mmkv-storage": "^0.6.0"

**Comment by ammarahm-ed** [comment]
> **Describe the bug**
> I updated the react version to 0.64.2 but when I try to get value using for example MMKV.getBoolAsync("myBooleanValue"); I don't receive the data and my app obtain a blank screen because my variable doesn't exist/
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/12010942/125536997-a771773d-3c6e-49ab-8e6f-5d3106832464.png)
> 
> **Platform Information:**
> "react": "17.0.1",
> "react-native": "0.64.2",
> "react-native-mmkv-storage": "^0.6.0"
> 

The example app in the library is on RN 0.64 and it works normally. 0.64.2 is a minor release so it should work the same. Check your configuration. Disable chrome debugging.

**Comment by ammarahm-ed** [comment]
> I think something big inside MMKV broke because NOTHING regarding the API functions works for me now. I can initialize the store with the Loader but nothing else seems to work, _except_ the hooks. I even tired running 1 previous version of the mmkv package to see if it worked.
> 
> ![image](https://user-images.githubusercontent.com/44002321/125547955-151564aa-7345-46c9-92ba-c2eb926790f2.png)
> 
> Console Output
> ```
> API {
>   "accessibleMode": "AccessibleWhenUnlocked",
>   "alias": null,
>   "aliasPrefix": "com.MMKV.",
>   "encryption": encryption {
>     "accessibleMode": "AccessibleWhenUnlocked",
>     "alias": null,
>     "aliasPrefix": "com.MMKV.",
>     "initialized": false,
>     "instanceID": "default",
>     "key": null,
>     "options": Object {
>       "accessibleMode": "AccessibleWhenUnlocked",
>       "alias": null,
>       "aliasPrefix": "com.MMKV.",
>       "initWithEncryption": false,
>       "initialized": false,
>       "instanceID": "default",
>       "key": null,
>       "processingMode": 1,
>       "secureKeyStorage": false,
>     },
>   },
>   "ev": EventManager {
>     "_registry": Object {},
>   },
>   "getArray": [Function anonymous],
>   "getBool": [Function anonymous],
>   "getInt": [Function anonymous],
>   "getMap": [Function anonymous],
>   "getMultipleItems": [Function anonymous],
>   "getString": [Function anonymous],
>   "indexer": indexer {
>     "MMKV": undefined,
>     "arrays": arrayIndex {
>       "MMKV": undefined,
>       "instanceID": "default",
>       "options": Object {
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "alias": null,
>         "aliasPrefix": "com.MMKV.",
>         "initWithEncryption": false,
>         "initialized": false,
>         "instanceID": "default",
>         "key": null,
>         "processingMode": 1,
>         "secureKeyStorage": false,
>       },
>     },
>     "booleans": boolIndex {
>       "MMKV": undefined,
>       "instanceID": "default",
>       "options": Object {
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "alias": null,
>         "aliasPrefix": "com.MMKV.",
>         "initWithEncryption": false,
>         "initialized": false,
>         "instanceID": "default",
>         "key": null,
>         "processingMode": 1,
>         "secureKeyStorage": false,
>       },
>     },
>     "instanceID": "default",
>     "maps": mapsIndex {
>       "MMKV": undefined,
>       "instanceID": "default",
>       "options": Object {
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "alias": null,
>         "aliasPrefix": "com.MMKV.",
>         "initWithEncryption": false,
>         "initialized": false,
>         "instanceID": "default",
>         "key": null,
>         "processingMode": 1,
>         "secureKeyStorage": false,
>       },
>     },
>     "numbers": numbersIndex {
>       "MMKV": undefined,
>       "instanceID": "default",
>       "options": Object {
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "alias": null,
>         "aliasPrefix": "com.MMKV.",
>         "initWithEncryption": false,
>         "initialized": false,
>         "instanceID": "default",
>         "key": null,
>         "processingMode": 1,
>         "secureKeyStorage": false,
>       },
>     },
>     "options": Object {
>       "accessibleMode": "AccessibleWhenUnlocked",
>       "alias": null,
>       "aliasPrefix": "com.MMKV.",
>       "initWithEncryption": false,
>       "initialized": false,
>       "instanceID": "default",
>       "key": null,
>       "processingMode": 1,
>       "secureKeyStorage": false,
>     },
>     "strings": stringsIndex {
>       "MMKV": undefined,
>       "instanceID": "default",
>       "options": Object {
>         "accessibleMode": "AccessibleWhenUnlocked",
>         "alias": null,
>         "aliasPrefix": "com.MMKV.",
>         "initWithEncryption": false,
>         "initialized": false,
>         "instanceID": "default",
>         "key": null,
>         "processingMode": 1,
>         "secureKeyStorage": false,
>       },
>     },
>   },
>   "initWithEncryption": false,
>   "initialized": false,
>   "instanceID": "default",
>   "key": null,
>   "options": Object {
>     "accessibleMode": "AccessibleWhenUnlocked",
>     "alias": null,
>     "aliasPrefix": "com.MMKV.",
>     "initWithEncryption": false,
>     "initialized": false,
>     "instanceID": "default",
>     "key": null,
>     "processingMode": 1,
>     "secureKeyStorage": false,
>   },
>   "processingMode": 1,
>   "secureKeyStorage": false,
>   "setArray": [Function anonymous],
>   "setBool": [Function anonymous],
>   "setInt": [Function anonymous],
>   "setMap": [Function anonymous],
>   "setString": [Function anonymous],
> }
> SET RESULT -- undefined
> KEY VALUE -- undefined
> ```
> 
> Platform Information:
> "react": "16.13.1",
> "react-native": "0.63.4"
> "react-native-mmkv-storage": "^0.6.0"

What do you mean by "now". Was it working before? What did you change? Is chrome debugger on or off?

**Comment by bombillazo** [comment]
I was working but for some reason, I can't get anything related to setting, fetching, and indexer calls to work. How do I check the chrome debugger?

**Comment by bombillazo** [comment]
It does seem to work with the hooks though, that is what is so strange. Using MMKV yields nothing though. not even errors, it simply returns undefined. I tried to get into the cpp code with the global functions implemented in JSI but I'm not familiar with how those work.

**Comment by bombillazo** [comment]
I tried the example and it doesnt seem to store and ferch the data once the application resets. 
https://user-images.githubusercontent.com/44002321/125648949-b1019b18-e95f-49a9-b2f6-289aa930a6c4.mp4

**Comment by ammarahm-ed** [comment]
@jgalianoz So today I tested the example app in the master branch. I updated the example app to RN 0.64.2 and then ran the example. It works normally. Everything is stored correctly even after the app is restarted/killed/force stopped. I tested on Android at the moment. 

It works normally with or without hooks. The indexer works too as expected @bombillazo

**Comment by jgalianoz** [comment]
@ammarahm-ed Thanks I continue to present problems but I think that the problem is my config after the update.

This is my Podfile
![image](https://user-images.githubusercontent.com/12010942/125656657-4b61e7fa-866a-4b88-93df-67fa96f85576.png)

**Comment by ammarahm-ed** [comment]
@jgalianoz Do you have the same problem on android? or is it happening only on iOS?

The pod file looks okay though. There is nothing strange happening. Maybe try commenting out use_flipper() and see if that helps?

Another thing would be that you clone the master branch. Run the example after updating the RN version to 0.64.2.

here's the podfile from example app that works fine, the only difference i see is that hermes is enabled. Which version did you upgrade from?
```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```
Also try clearing the pods and reinstalling them.  Delete `node_modules` folder. Run `yarn/npm install`. Run `pod install`. Run the app.

**Comment by jgalianoz** [comment]
@ammarahm-ed Yes, yesterday I test in Android and I had the same problem. Before updated all worked perfectly. I will try commenting use_flipper().

I had the 0.63.4 version and all worked without any problem.

**Comment by ammarahm-ed** [comment]
@jgalianoz Maybe there are some old cached files that are causing the problem. 

1. Delete `ios/Pods`
2. Delete `node_modules`
3. Run `npm install/yarn`
4. Run `cd android && ./gradlew clean` for android
5. Run `pod install`
6. Run clean Project from xcode.
7. Run the app

**Comment by jgalianoz** [comment]
@ammarahm-ed Do you use Xcode 12.5 ?

**Comment by Kiura** [comment]
I also have 0.64.2, works perfectly fine on Android, haven't tested on iOS yet

**Comment by jgalianoz** [comment]
@Kiura Do you use async or sycn methods?

**Comment by Kiura** [comment]
@jgalianoz I use async methods within async function:

```js
async getString(key: string): Promise<string> {
  const data = await this.MMKV.getStringAsync(key);
  ...
  return data;
}
```

**Comment by jgalianoz** [comment]
@ammarahm-ed Yesterday finally I could run my app and MMKV worked perfectly, my problem was my metro configuration. Thanks for the help. 🧡
