### ISSUE TITLE
[Question] General package questions

### ISSUE THREAD

**Issue by bombillazo** [ammarahm-ed/react-native-mmkv-storage#139]
Hello, I have a few questions about this package:

1. From what I understand, if one uses `.withEncryption()` in the initializer, an encrypted storage instance is created to store and retrieve data. But how is this handled when the app is closed and opened again if I don't supply a key? Is a key stored somewhere to unencrypt the stored data?
2. How are conflicts between existing and new instances resolved? If I create a new instance without an ID will it overwrite the previous instance (with default ID) created?
3. Are instance initiators async? Right now no instance API call is working for me (posted in this issue [#138](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/138)), but wanted to make sure it was not related to improper setup. Although I have tries both sync and async ...

Thanks in advance for the time and answers.

**Comment by ammarahm-ed** [comment]
> Hello, I have a few questions about this package:
> 
> 1. From what I understand, if one uses `.withEncryption()` in the initializer, an encrypted storage instance is created to store and retrieve data. But how is this handled when the app is closed and opened again if I don't supply a key? Is a key stored somewhere to unencrypt the stored data?
> 2. How are conflicts between existing and new instances resolved? If I create a new instance without an ID will it overwrite the previous instance (with default ID) created?
> 3. Are instance initiators async? Right now no instance API call is working for me (posted in this issue [#138](https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/138)), but wanted to make sure it was not related to improper setup. Although I have tries both sync and async ...
> 
> Thanks in advance for the time and answers.

1. The key is stored securely in Keychain o iOS and Keystore on Android. That is how it works internally. It generates a random password then stores it in Keychain/Keystore.

2. Instances do not overwrite eachother. If you create an instance in two places with the same id. The will work on the same storage. However it's best to make only one instance.

2. They are not async. You should clone the repo and run the example app. It works normally then compare your code. You must have missed something.

**Comment by bombillazo** [comment]
I tried the example and it doesnt seem to store and ferch the data once the application resets.
[Screen Recording](https://user-images.githubusercontent.com/44002321/125648949-b1019b18-e95f-49a9-b2f6-289aa930a6c4.mp4)

**Comment by ammarahm-ed** [comment]
> I tried the example and it doesnt seem to store and ferch the data once the application resets.
> [Screen Recording](https://user-images.githubusercontent.com/44002321/125648949-b1019b18-e95f-49a9-b2f6-289aa930a6c4.mp4)

Did you clone master and run the example or just copied code inside App.js?

Because I just ran the example code after cloning from master just now and it is working as expected. i killed/restarted the app and everything is stored.

I tested on Android 11 Phone.

Try running the following anywhere inside the component:
```js
console.log(global.setStringMMKV,global.setBoolMMKV)
```
It should log ` [Function setStringMMKV] [Function setBoolMMKV]`  which means the functions are registered correctly.

**Comment by bombillazo** [comment]
I had to copy the code since I was using Expo, how does one test the app without expo? I use npm start but not sure how to access the app from there.

**Comment by ammarahm-ed** [comment]
@bombillazo The library does not work with expo projects if you have not ejected.

**Comment by bombillazo** [comment]
Oh wow, ok that is good to know!

My apologies, I am new to React Native. Thanks for the patience and the prompt responses. I will check how ejecting my project works so I can add this library. It truly is the best option for secured local storage and I want to use it!

If you have any guide recommend an article on how to eject to add dependencies, I would greatly appreciate it.

**Comment by bombillazo** [comment]
Im thinking this is the process? https://rnmmkv.vercel.app/#/gettingstarted?id=gt050-installation-steps

**Comment by ammarahm-ed** [comment]
@bombillazo You can follow the guide here by the expo guys: https://docs.expo.io/expokit/eject/

You can read the docs to know what limitations etc ejecting will cause for your expo app. Once you have ejected, you can install native modules such as my library any many others.

**Comment by ammarahm-ed** [comment]
Actually you should follow this guide: https://docs.expo.io/workflow/customizing/

**Comment by bombillazo** [comment]
So running it without expo I am getting this error in both my project and the example project:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-mmkv-storage'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in 
your project's local properties file at 'D:\user\projects\react-native-mmkv-storage\example\android\local.properties'.

```

**Comment by bombillazo** [comment]
Got it to work, took me some tries but FINALLY! Now ill be able to answer some questions myself about the package. Thanks!

**Comment by Kiura** [comment]
Oh, I somehow missed this part.
> The key is stored securely in Keychain o iOS and Keystore on Android. That is how it works internally. It generates a random password then stores it in Keychain/Keystore.

Any way to get the password like a method `MMKV.getPassword`?

**Comment by ammarahm-ed** [comment]
> > I tried the example and it doesnt seem to store and ferch the data once the application resets.
> > [Screen Recording](https://user-images.githubusercontent.com/44002321/125648949-b1019b18-e95f-49a9-b2f6-289aa930a6c4.mp4)
> 
> I just ran the example code after cloning from master and it is working as expected.

If you are using your own password then it will use that password. If you are not. It will generate a password.

You can use `MMKV.options.key` to get the current key for now. I will add a method to get key later.

**Comment by Kiura** [comment]
`MMKV.options.key` 
This is good enough for my needs, thank you :)

**Comment by ammarahm-ed** [comment]
> `MMKV.options.key` 
> This is good enough for my needs, thank you :)

It doesn't work correctly and gives the wrong key so don't use it.

**Comment by Kiura** [comment]
Oh, okay, I will be storing the key then, thank you
