### ISSUE TITLE
Warning Require cycle: node_modules/react-native-mmkv-storage/index.js

### ISSUE THREAD

**Issue by rpCal** [ammarahm-ed/react-native-mmkv-storage#14]
I've instaled lib ( "react-native-mmkv-storage": "^0.3.0", ) and first that I've notice when I use it in my code is

```
Require cycle: node_modules/react-native-mmkv-storage/index.js -> node_modules/react-native-mmkv-storage/src/loader.js -> node_modules/react-native-mmkv-storage/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

![Screenshot from 2020-04-11 08-15-50](https://user-images.githubusercontent.com/1282091/79036868-b2b56a80-7bcc-11ea-8737-139c3d64a1a8.png)

I think this is something that should fixed and you may need to know 

BTW. Great work with this library! Thank you!

**Comment by ammarahm-ed** [comment]
Thank you for creating this issue, I will fix this ASAP and upload a point release just now.

**Comment by ammarahm-ed** [comment]
I have pused the new version with the fix. Thanks again for using this library. I am closing this issue now. Feel free to open it again if you still face the issue.

**Comment by rpCal** [comment]
Wow! That's was quick!
I've pull  v0.3.1 and warning has gone. Thank you

**Comment by ammarahm-ed** [comment]
Well thats good news. Tell me if you face any other issue.
