### ISSUE TITLE
[Question] Mock the Storage

### ISSUE THREAD

**Issue by jgalianoz** [ammarahm-ed/react-native-mmkv-storage#140]
**Describe the bug**
My tests are breaking because of react-native-mmkv-storage.
Is there an example of how to correct this problem?

**Screenshots**

![image](https://user-images.githubusercontent.com/12010942/125850958-4efaf8f5-2bfb-4d04-8ed9-7b90fed73567.png)

**Platform Information:**
 - OS: [iOS/Android]
 - React Native Version [0.64]
 - Library Version [0.6.0]

**Comment by ammarahm-ed** [comment]
Read this: https://stackoverflow.com/questions/41725796/jest-test-suite-failed-to-run-syntaxerror-unexpected-token-import
