### ISSUE TITLE
[TypeError: global.setBoolMMKV is not a function]

### ISSUE THREAD

**Issue by amk-cb** [ammarahm-ed/react-native-mmkv-storage#143]
**Describe the bug**
clearStore is throwing error [TypeError: global.setBoolMMKV is not a function].

**Platform Information:**
 - OS: [ iOS/Android]
 - React Native Version [ 0.64]
 - Library Version [e.g. 0.6.0]

**Additional context**

**Comment by ammarahm-ed** [comment]
> **Describe the bug**
> clearStore is throwing error [TypeError: global.setBoolMMKV is not a function].
> 
> 
> 
> **Platform Information:**
>  - OS: [ iOS/Android]
>  - React Native Version [ 0.64]
>  - Library Version [e.g. 0.6.0]
> 
> **Additional context**
> Add any other context about the problem here.
> 

Check #137
