### ISSUE TITLE
[It should have a non-async HasKey function]

### ISSUE THREAD

**Issue by amk-cb** [ammarahm-ed/react-native-mmkv-storage#144]

**Comment by ammarahm-ed** [comment]
It's not async already. I think the type definitions are incorrect.

**Comment by amk-cb** [comment]
very nice library bro. Great work... :)

Here return type is `Promise<boolean>`

`storage.indexer.hasKey(key)`

**Comment by yfunk** [comment]
@ammarahm-ed What about `indexer.getKeys()` and `indexer.[x].getAll()`? Are they also synchronous already or would it be possible / make sense to make them synchronous?

**Comment by ammarahm-ed** [comment]
> @ammarahm-ed What about `indexer.getKeys()` and `indexer.[x].getAll()`? Are they also synchronous already or would it be possible / make sense to make them synchronous?

They are async for now.
