### ISSUE TITLE
useStorage without a key is making app to crash

### ISSUE THREAD

**Issue by mydesweb** [ammarahm-ed/react-native-mmkv-storage#145]
It would be nice to see an error or warning if we try to useStorage without the required parameter. On Android the app is just crashing.
 
`useStorage = create(MMKV);`

latest mmkv version 0.6.0

**Comment by ammarahm-ed** [comment]
@mydesweb I will fix it.

**Comment by ammarahm-ed** [comment]
Fixed on master
