### ISSUE TITLE
[Bug] App startup crash on physical Android device

### ISSUE THREAD

**Issue by bombillazo** [ammarahm-ed/react-native-mmkv-storage#146]
**Describe the bug**
When running my app on an Android physical device , the app immediately crashes. Running it on an emulator works fine. Used `adb logcat` to monitor activity while app is running, here seems to be the moment it crashes:

```
07-29 15:03:23.127  1374  1833 W InputDispatcher: channel '751c9ca com.myapp.mobileapp/com.myapp.mobileapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=370
```
Googling the error brought me to [this Expo issue](https://forums.expo.dev/t/android-crashing-without-error-message/18919) which seems to be related to async storage. But I am using this library for storage so perhaps it is related.

**To Reproduce**
1. Connect device to test laptop
2. Install client using `react-native run-android`
3. Run expo server with dev client using `expo r --dev-client`
4. App splash screen appears and craches

**Expected behavior**

**Logs**
```

07-29 15:03:23.084 24568 29026 I Process : Sending signal. PID: 24568 SIG: 9
07-29 15:03:23.127  1374  1833 W InputDispatcher: channel '751c9ca com.myapp.mobileapp/com.myapp.mobileapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=370
07-29 15:03:23.127  1374  1833 E InputDispatcher: channel '751c9ca com.myapp.mobileapp/com.myapp.mobileapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-29 15:03:23.140  1374  5531 D InputTransport: Input channel destroyed: 'ClientS', fd=488
07-29 15:03:23.140  1045  1045 I Zygote  : Process 24568 exited due to signal 9 (Killed)
07-29 15:03:23.140 25398 25398 D InputTransport: Input channel destroyed: 'ClientS', fd=77
07-29 15:03:23.140  1374  2404 I ActivityManager: Process com.myapp.mobileapp (pid 24568) has died: fore TOP (633,1837)
07-29 15:03:23.140  1374  2402 I WindowManager: WIN DEATH: Window{751c9ca u0 com.myapp.mobileapp/com.myapp.mobileapp.MainActivity}
07-29 15:03:23.141  1374  2402 W InputDispatcher: Attempted to unregister already unregistered input channel '751c9ca com.myapp.mobileapp/com.myapp.mobileapp.MainActivity (server)'
07-29 15:03:23.141  1374  2402 D InputTransport: Input channel destroyed: '751c9ca', fd=370
07-29 15:03:23.141  1374  1540 I libprocessgroup: Successfully killed process cgroup uid 10520 pid 24568 in 0ms
07-29 15:03:23.141  1374  2402 I WindowManager: Destroying surface Surface(name=com.myapp.mobileapp/com.myapp.mobileapp.MainActivity$_24568)/@0x4940bdf called by com.android.server.wm.WindowStateAnimator.destroySurface:1834 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:733 com.android.server.wm.WindowState.removeImmediately:2402 com.android.server.wm.WindowState.removeIfPossible:2546 com.android.server.wm.WindowState.access$300:264 com.android.server.wm.WindowState$DeathRecipient.binderDied:3149 android.os.BinderProxy.sendDeathNotice:685 <bottom of call stack>
07-29 15:03:23.142   915  1068 I Layer   : id=73292 removeFromCurrentState com.myapp.mobileapp/com.myapp.mobileapp.MainActivity$_24568#0 (57)
07-29 15:03:23.143   825   886 I sensors-hal: batch:276, android.sensor.accelerometer/28, period=200000000, max_latency=0 request completed
07-29 15:03:23.143  1374  3855 D SensorService: Calling activate off
```

**Platform Information:**
 - OS: Android 30
 - React Native Version 0.63.4
 - Expo 42.0.0
 - Library Version 0.6.0

**Comment by bombillazo** [comment]
Ive isolated the problem to this:
`const MMKV = new MMKVStorage.Loader().withInstanceID('MyId').withEncryption().initialize();`

The app crashes upon calling this line on a physical device. The problem is when I use `.withInstanceID('MyId')`

**Comment by bombillazo** [comment]
BTW there is a typo in the documentation:
![image](https://user-images.githubusercontent.com/44002321/127621360-20e6e3c5-30cd-4072-b8f9-69a4ff2e74c4.png)

It's neither of those, its actually `getAllMMKVInstanceIDs`

I also see clearMemoryCache in the docs but not in the source code. What would be the difference between that and clearStore? or is that a deprecated method?

**Comment by bombillazo** [comment]
I also see `clearMemoryCache` in the docs but not in the source code. What would be the difference between that and `clearStore`? or is that a deprecated method?

**Comment by bombillazo** [comment]
Hmmm, deleting my app and re-installing resolved the issue apparently. All that store had was a single key and String value, perhaps I was somehow corrupted.

Is there a way to delete all stored instance data without loading it? This is useful in these cases when the actual act of loading an instance is erroring out. I'm not sure why it was failing, the app was simply crashing upon running the Loader function.  It was crashing in the native code so I can't capture the error.

One potential way to solve this is having a way to destroy any MMKV data associated with my app without uninstalling/deleting.

**Comment by ammarahm-ed** [comment]
The `clearMemoryCache` is for clearing the storage from RAM, not the actual file. There is not better way than calling clearStore. 

What you faced might also be due to old or corrupt cache files in node_modules or gradle which cause issues sometimes. 

However you can delete all data by deleting the /mmkv folder in the app directory. 

The issue with docs, I will update it.

**Comment by bombillazo** [comment]
How does one delete the /mmkv folder? I am not familiar with app directory. Where is this directory located?

**Comment by bombillazo** [comment]
I figured it out, thanks for the help!
