### ISSUE TITLE
Multiple JSI module

### ISSUE THREAD

**Issue by dancixx** [ammarahm-ed/react-native-mmkv-storage#151]
Hi, my question is not a bug actually prefer I need a bit of help. I am totally new to JSI modules. So how can I plug more JSI modules on Android because I use `reanimated2` but the installation of reanimated2 is the same as this library and I get an error that the `getJSIModulePackage` is called when I put it twice.

So I think I should create a list of JSI modules in MainApplication.java

```
@Override
    protected JSIModulePackage getJSIModulePackage() {
      return new RNMMKVJSIModulePackage();
    }
```

**Comment by ammarahm-ed** [comment]
> Hi, my question is not a bug actually prefer I need a bit of help. I am totally new to JSI modules. So how can I plug more JSI modules on Android because I use `reanimated2` but the installation of reanimated2 is the same as this library and I get an error that the `getJSIModulePackage` is called when I put it twice.
> 
> So I think I should create a list of JSI modules in MainApplication.java
> 
> ```
> @Override
>     protected JSIModulePackage getJSIModulePackage() {
>       return new RNMMKVJSIModulePackage();
>     }
> ```

Check the documentation. It guides you on how to install with reanimated.

**Comment by dancixx** [comment]
Thanks. I remember now. Sorry for the unnecessary question.
