### ISSUE TITLE
Expo: Newbie question. How install for use with Expo?

### ISSUE THREAD

**Issue by gfmoore** [ammarahm-ed/react-native-mmkv-storage#152]
Hi, newbie to React-Native and have managed to get async-storage working on previous tests so thought I'd give this a go.

I did the install using yarn (as using npm to create a new app hangs forever on my machine?)

However, I could not do the step:
>=0.5.0 Installation Steps
Android
Plug MMKV in MainApplication.java

as the android folder doesn't exist in Expo (all hidden away.)

Here is my App.js

```
import React from 'react'
import { StyleSheet, Text, View } from 'react-native'
import MMKVStorage from 'react-native-mmkv-storage'


const App = () => {

  const MMKV = new MMKVStorage.Loader().initialize();

  const test = async  () => {
    try {
      await MMKV.setStringAsync('myString','helloworld')
    }
    catch (e) {
      console.log( `write error ${e}`)
    }

    try {
      let myString = await MMKV.getStringAsync('myString')
      console.log(myString)
    }
    catch (e) {
      console.log( `read error ${e}`)
    }


  }

  test()

  return (
    <>
      <Text style={styles.header}>Hello G!</Text>
    </>
  )
}

const styles = StyleSheet.create({
  header: {
    marginTop: 40,
    marginLeft: 10,
    fontSize: 20,
  },
});

export default App

```

The result is that app works, but the console output is (with no errors or warnings)

undefined

btw I also tried the simpler code from your blog, but I assume this is outdated now:

```
import MMKV from "react-native-mmkv-storage;
await MMKV.setString('myString','helloworld');
let myString = await MMKV.getString('myString');
```

Could I also request that you show a working simple App.js in your documentation as some people like me are not used to the structure of async await?

Many thanks for any advice or help.

Gordon

**Comment by ammarahm-ed** [comment]
You need to eject from expo to use this library.

**Comment by gfmoore** [comment]
Ok, figured that might be the case. Appreciated the response :)

**Comment by darlanjunior** [comment]
You can also fork and write a plugin for custom Expo client, see https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8

I am actually considering it

**Comment by i-mighty** [comment]
Hey would love to see the plugins you make for this. 
it is something my team would be interested in.
