### ISSUE TITLE
Task :react-native-mmkv-storage:generateJsonModelDebug FAILED

### ISSUE THREAD

**Issue by hzhurauski** [ammarahm-ed/react-native-mmkv-storage#155]
Hi, I set up the project with https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/67#issuecomment-801467636, but the following error crashes:

```
Execution failed for task ':react-native-mmkv-storage:generateJsonModelDebug'
C/C++ debug|armeabi-v7a : CMake Error at C:/Users/PC/android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
Failed to open

Permission denied
Call Stack (most recent call first):
CMakeLists.txt
```

Platform Information:
 - OS: windows
 - React Native Version: 0.64.1
 - React-native-mmkv-storage: 0.6.0

**Comment by ammarahm-ed** [comment]
Try the unreleased version on master branch.

**Comment by cjianhui** [comment]
How do I pull the latest unreleased version from npm?

**Comment by ammarahm-ed** [comment]
@cjianhui I will release the new version today on npm

**Comment by hzhurauski** [comment]
> Try the unreleased version on master branch.

Updated version to 0.61 - the error is the same. What to do?

**Comment by ammarahm-ed** [comment]
> > Try the unreleased version on master branch.
> 
> Updated version to 0.61 - the error is the same. What to do?

Can you try to clone the example app and run it? Also in your project, delete node_modules folder, run yarn or npm install. Clear gradle cache by running `./gradlew clean` in android folder and run the project again. 

From what I have researched just now, the error seems to be coming from system not giving permissions to certain files while building. Maybe you have an antivirus program or something that is causing the problem.

**Comment by hzhurauski** [comment]
Disabling antivirus - solving the problem. Thank you!

**Comment by DiegoBM** [comment]
I also get the same error

`> Task :react-native-mmkv-storage:generateJsonModelDebug FAILED`

"react-native": "0.65.1",
"react-native-mmkv-storage": "^0.6.0",

I could not see any bigger versions in npm. Disabling the antivirus does nothing in my case
