### ISSUE TITLE
[Bug] useMMKVStorage setValue is not stable

### ISSUE THREAD

**Issue by andreialecu** [ammarahm-ed/react-native-mmkv-storage#157]
This code will create an infinite loop:

```ts
  const [value, setValue] = useMMKVStorage(...);

  useFocusEffect(
    useCallback(() => {
      if (isFocused) {
        setNewsFeedLastSeen(new Date().toISOString());
      }
    }, [isFocused, setNewsFeedLastSeen]),
  );


```

`setValue` is not stable, it changes its reference each time `value` is changed. This is unexpected, I think `setValue` should never change its reference.

The problem is that the dependencies include the value here:
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/3f2777078704b94f565dfb7ac092b95fce29f884/src/hooks/useMMKV.js#L98

**Comment by ammarahm-ed** [comment]
@andreialecu hmm I think you are right. Did you try to remove `value` from dependencies of `setNewValue` and try again? Did it work as expected?

**Comment by andreialecu** [comment]
Yes, the current workaround is this:

<img width="726" alt="Screenshot 2021-09-12 at 23 00 47" src="https://user-images.githubusercontent.com/697707/133001120-1dda6053-ba27-45f5-bb62-aa5ec529358e.png">

**Comment by andreialecu** [comment]
It can probably be fixed in the library by wrapping the value in an additional `useRef`, and using `ref.current` instead as a parameter to the callback here:

https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/3f2777078704b94f565dfb7ac092b95fce29f884/src/hooks/useMMKV.js#L71

**Comment by ammarahm-ed** [comment]
Can you send a PR to fix this?

**Comment by andreialecu** [comment]
I took a quick look and the proper way to fix this would be to rewrite the hook entirely to use `useReducer` because its `dispatch` is stable. Also using `useReducer` would simplify the implementation of the hook further..

However, due to the lack of tests and because this library is not written in TypeScript, and not having much experience with the code base I think it might be better for someone more familiar with it to handle it.

**Comment by ammarahm-ed** [comment]
> I took a quick look and the proper way to fix this would be to rewrite the hook entirely to use `useReducer` because its `dispatch` is stable. Also using `useReducer` would simplify the implementation of the hook further..
> 
> However, due to the lack of tests and because this library is not written in TypeScript, and not having much experience with the code base I think it might be better for someone more familiar with it to handle it.

I will fix it tomorrow.

**Comment by ammarahm-ed** [comment]
Released new version on npm
