### ISSUE TITLE
Add tests to simplify contributing by others in future and prove implementation

### ISSUE THREAD

**Issue by retyui** [ammarahm-ed/react-native-mmkv-storage#159]
- Without test it is difficult to understand what code actually do 
- It is easy to contribute when tests added in project

**Comment by ammarahm-ed** [comment]
in progress

**Comment by retyui** [comment]
so long wip, I will use more contrbuting friendly pkg 
[react-native-mmkv](https://github.com/mrousavy/react-native-mmkv)
