### ISSUE TITLE
Android fails on Circle CI

### ISSUE THREAD

**Issue by mmapplebeck** [ammarahm-ed/react-native-mmkv-storage#166]
React Native 0.65.1 (Also tested on 0.64.2)
react-native-mmkv-storage 0.6.4

Similar to the previously closed App Center issue, Android build fails in Circle CI:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:generateJsonModelDebug'.
> /home/circleci/project/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /home/circleci/project/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv

**Comment by mmapplebeck** [comment]
Actually, my project was still React Native 0.64.2. Trying to see if upgrading to 0.65.1 makes a difference.

**Comment by mmapplebeck** [comment]
Update: It's actually just the clean task that fails. The bundle step succeeds. 

I am using Fastlane's [gradle task](https://docs.fastlane.tools/actions/gradle/) to clean and bundle:

Fastfile:
```
gradle(
      tasks: ["clean", options[:task]],
      project_dir: "./android",
    )
```

CI output:
```Exit status of command '/home/circleci/project/.../android/gradlew clean bundleDebug -p ./android' was 1 instead of 0```

When I skip the clean task, the build succeeds. Any thoughts on why clean might fail?

**Comment by mmapplebeck** [comment]
Debug build succeeds but release build is failing with following error:

```
> Task :react-native-mmkv-storage:externalNativeBuildDebug FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /opt/android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/circleci/project/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/arm64-v8a rnmmkv}
  ninja: Entering directory `/home/circleci/project/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/arm64-v8a'
  [1/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_md5_one.cpp.o
  [2/37] Building ASM object core/CMakeFiles/core.dir/aes/openssl/openssl_aes-armv4.S.o
  [3/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_md5_dgst.cpp.o
  [4/37] Building ASM object core/CMakeFiles/core.dir/aes/openssl/openssl_aesv8-armx.S.o
  ```

**Comment by mmapplebeck** [comment]
Adding a separate command line clean task ```./gradlew clean``` seemed to fix that.

I am unblocked now but I'm still curious why the fastlane clean task fails with the `REACT_NATIVE_JNI_LIB` error. Any ideas?

**Comment by ammarahm-ed** [comment]
> Adding a separate command line clean task ```./gradlew clean``` seemed to fix that.
> 
> I am unblocked now but I'm still curious why the fastlane clean task fails with the `REACT_NATIVE_JNI_LIB` error. Any ideas?

It will need more investigation.  Probably because when the clean task runs, it runs this part in build.gradle of library:

Line 161:
```
tasks.whenTaskAdded -> 
```
The task copies react native aar files that are used to build the library. For app center what I did was call the task before `generateJsonModel*` is called. But it seems that maybe we need to call in sooner than that. 

The error with clean task needs to be investigated separately. My guess is that when you run clean, it deletes the build folder which has all the .so files. These files need to be added again when debug build runs but for some reason they are not copied causing the error.

**Comment by retyui** [comment]
Also cannot build a release version of the app (Github actions [environment](https://github.com/actions/virtual-environments/blob/ubuntu20/20211004.1/images/linux/Ubuntu2004-README.md))

- `react-native@0.63.x`
- `react-native-mmkv-storage@0.6.5`

```txt 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'.
> /home/runner/work/therapydiaries-builds/therapydiaries-builds/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "rnmmkv" in directory /home/runner/work/therapydiaries-builds/therapydiaries-builds/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```

JSI_LIB on RN 0.66.x `node_modules/react-native-mmkv-storage/android/build/react-native-0.66.0.aar/jni/armeabi-v7a/libjsi.so`

but

```bash
# RN 0.63.x:
ls -l node_modules/react-native-mmkv-storage/android/build

./react-native-0.63.3.aar/jni/armeabi-v7a/libjsijniprofiler.so
./react-native-0.63.3.aar/jni/armeabi-v7a/libjsinspector.so
./react-native-0.63.3.aar/jni/x86_64/libjsijniprofiler.so
./react-native-0.63.3.aar/jni/x86_64/libjsinspector.so
./react-native-0.63.3.aar/jni/arm64-v8a/libjsijniprofiler.so
./react-native-0.63.3.aar/jni/arm64-v8a/libjsinspector.so
./react-native-0.63.3.aar/jni/x86/libjsijniprofiler.so
./react-native-0.63.3.aar/jni/x86/libjsinspector.so
```

**Comment by retyui** [comment]
I created a test to find out the build status of the last version of 0.6.5: https://github.com/retyui/react-native-mmkv-storage/actions/runs/1326310473

<details>
<summary>RN 0.61.x ⚠️ CMake 3.9.0 or higher is required</summary>

```log
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.9.0 or higher is required.  You are running version 3.6.0-rc2
```
</details>

<details>
<summary>RN 0.62.x ⚠️ CMake 3.9.0 or higher is required</summary>

```log
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.9.0 or higher is required.  You are running version 3.6.0-rc2
```
</details>

<details>
<summary>RN 0.63.x ⚠️ CMake 3.9.0 or higher is required</summary>

```log
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.9.0 or higher is required.  You are running version 3.6.0-rc2
```
</details>

<details>
<summary>RN 0.64.x ⚠️ JSI_LIB => NOTFOUND</summary>

```log
> Task :react-native-mmkv-storage:generateJsonModelRelease FAILED
FAILURE: Build failed with an exception.
47 actionable tasks: 47 executed

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'.
> /home/runner/work/react-native-mmkv-storage/react-native-mmkv-storage/rn64/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "rnmmkv" in directory /home/runner/work/react-native-mmkv-storage/react-native-mmkv-storage/rn64/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```
</details>


<details>
<summary>RN 0.65.x ⚠️ JSI_LIB => NOTFOUND</summary>

```log
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:generateJsonModelRelease'.
> /home/runner/work/react-native-mmkv-storage/react-native-mmkv-storage/rn65/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "rnmmkv" in directory /home/runner/work/react-native-mmkv-storage/react-native-mmkv-storage/rn65/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```
</details>


<details>
<summary>RN 0.65.x ✅ OK</summary>

```log
https://github.com/retyui/react-native-mmkv-storage/pull/1/checks?check_run_id=3852528126
```
</details>

**Comment by mmapplebeck** [comment]
upgrading to 0.6.5 seems to have fixed my problem 👍

**Comment by carl0shd** [comment]
is happening to me but in App Center with React Native 0.66

```> Task :react-native-mmkv-storage:generateJsonModelDebug FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:generateJsonModelDebug'.
> /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "rnmmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /Users/runner/work/1/s/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```

**Comment by retyui** [comment]
I've just created a new react native 0.66.x project and  [added MMKV module](https://github.com/retyui/mmkv-react-native-appcenter-test/commit/e8b6c83ca1e644b117ac9e2089b534491a7078a0) to test build on AppCenter

And it works without any issues: 
![image](https://user-images.githubusercontent.com/4661784/137340233-293dcf13-f241-4864-b7a5-5c07d80e8e8a.png)


@carl0shd could you please provide more info (react-native-mmkv-storage version, or build logs or demo repo ....) ?

**Comment by carl0shd** [comment]
> I've just created a new react native 0.66.x project and [added MMKV module](https://github.com/retyui/mmkv-react-native-appcenter-test/commit/e8b6c83ca1e644b117ac9e2089b534491a7078a0) to test build on AppCenter
> 
> And it works without any issues: ![image](https://user-images.githubusercontent.com/4661784/137340233-293dcf13-f241-4864-b7a5-5c07d80e8e8a.png)
> 
> @carl0shd could you please provide more info (react-native-mmkv-storage version, or build logs or demo repo ....) ?

I am using react-native-mmkv-storage 0.6.5, React Native 0.66.0 and App Center just fails, a pretty fun fact is that in local, using the command `./gradlew app:assembleDebug` the build works.

I am attaching the app center log of the Graddle step.

[10_Gradle Task.txt](https://github.com/ammarahm-ed/react-native-mmkv-storage/files/7347345/10_Gradle.Task.txt)

**EDIT:**

looking the log, appcenter run this command `gradlew -p android clean :app:assembleDebug` to generate the build, looks like app center clean the project, is exactly the same problem that @mmapplebeck had.

**Comment by retyui** [comment]
@mmapplebeck  Why do you bundle debug version?  (that does not include js bundle in `.apk` by default) 

---

Enable `release` should fix it: 

![image](https://user-images.githubusercontent.com/4661784/137349956-8a0d72c5-8620-46c4-8544-f1b23a5d9790.png)

---

But, if you want to **build** debug use a version with a fix:
```bash
yarn add retyui/react-native-mmkv-storage#816cbbf
```

**Comment by carl0shd** [comment]
> @mmapplebeck Why do you bundle debug version? (that does not include js bundle in `.apk` by default)
> 
> Enable `release` should fix it:
> 
> ![image](https://user-images.githubusercontent.com/4661784/137349956-8a0d72c5-8620-46c4-8544-f1b23a5d9790.png)
> 
> But, if you want to **build** debug use a version with a fix:
> 
> ```shell
> yarn add retyui/react-native-mmkv-storage#816cbbf
> ```

Thanks, the build works in release mode, also thanks for the effort of the fork with the fix.

**Comment by ammarahm-ed** [comment]
I think after the work by @retyui this issue should not be resolved for anyone. A new version will be released soon.
