### ISSUE TITLE
[Request] npm publish

### ISSUE THREAD

**Issue by java-james** [ammarahm-ed/react-native-mmkv-storage#173]
Sorry, no discussion section on repo to open this request in.
When do we expect the next release to np of this package to be?
Waiting for a major with android RN <0.66.0 build fix.

Thanks

**Comment by ammarahm-ed** [comment]
> Sorry, no discussion section on repo to open this request in.
> When do we expect the next release to np of this package to be?
> Waiting for a major with android RN <0.66.0 build fix.
> 
> Thanks

I have been waiting to release it after testing on iOS 0.66.0.

If you can test on iOS and let me know if build is passing. I will publish it.
