### ISSUE TITLE
TypeError: _reactNativeMmkvStorage.default.setArray is not a function. (In '_reactNativeMmkvStorage.default.setArray('citiesList', state)', '_reactNativeMmkvStorage.default.setArray' is undefined)

### ISSUE THREAD

**Issue by iqzasm** [ammarahm-ed/react-native-mmkv-storage#174]
The examples used in https://dev.to/ammarahmed/best-data-storage-option-for-react-native-apps-42k are not working.

Tried with both String and Array. getting the below error:

> TypeError: _reactNativeMmkvStorage.default.setArray is not a function. (In '_reactNativeMmkvStorage.default.setArray('citiesList', state)', '_reactNativeMmkvStorage.default.setArray' is undefined)
> _callee2$

**Comment by ammarahm-ed** [comment]
Read the docs to properly install and use the library.
