### ISSUE TITLE
[help wanted] Unexpected identifier 'MMKV'

### ISSUE THREAD

**Issue by consecrate** [ammarahm-ed/react-native-mmkv-storage#177]
Hi, I am a complete newbie to react-native-mmkv-storage, and localstorage in react native in general. I just copied the sample code from the documentation page:

```js
import MMKVStorage from "react-native-mmkv-storage";

const MMKV = new MMKVStorage.Loader()
    .withInstanceID('mmkvInstanceID')
    .setProcessingMode(MMKVStorage.MODES.MULTI_PROCESS)
    // .withEncryption()
    // .encryptWithCustomKey('encryptionKey',true, 'customAlias')
    .initialize()

await MMKV.setStringAsync("string", "string");
let string = await MMKV.getStringAsync("string");
```

I got the error: "Unexpected identifier 'MMKV"

I think it worked before, but when I tried to `console.log(string)` out, it returned "undefined"

Is there any possible fixes to this problem?
(sorry for asking a complete newbie question)

**Comment by ammarahm-ed** [comment]
I have fixed your code. You need to declare a variable properly in JavaScript. In your case `const MMKV`.

**Comment by consecrate** [comment]
Thanks @ammarahm-ed!

After I've plugged in the code, the error was fixed, but there is another problem:
```js
import MMKVStorage from "react-native-mmkv-storage";

const MMKV = new MMKVStorage.Loader().initialize();

MMKV.setString("string", "string");

console.log(MMKV.getString("string"));
```

It end up returning 'undefined', from what I know and from the documentation page, it should return "string". Why is this so? Is there any possible fixes?

**Comment by ammarahm-ed** [comment]
> Thanks @ammarahm-ed!
> 
> After I've plugged in the code, the error was fixed, but there is another problem:
> ```js
> import MMKVStorage from "react-native-mmkv-storage";
> 
> const MMKV = new MMKVStorage.Loader().initialize();
> 
> MMKV.setString("string", "string");
> 
> console.log(MMKV.getString("string"));
> ```
> 
> It end up returning 'undefined', from what I know and from the documentation page, it should return "string". Why is this so? Is there any possible fixes?

Did you follow the installation instructions properly? 
What is your RN version? Are you testing on android or ios? Are you using expo?

**Comment by consecrate** [comment]
I ran `npm install react-native-mmkv-storage`, other than that I didn't modify anything.

React Native version: 0.65.1
I'm testing on android
I'm not using expo

**Comment by ammarahm-ed** [comment]
Follow the installation instructions in documentation.

**Comment by consecrate** [comment]
Ohhhhhhhh.. I see. After I ran `npx mmkv-link` things are fixed. Thanks again!
