### ISSUE TITLE
[Question] Change javax.crypto.Cipher to Conceal

### ISSUE THREAD

**Issue by msvargas** [ammarahm-ed/react-native-mmkv-storage#178]
Hi, thanks for the amazing lib, I have the following issue:

![image](https://user-images.githubusercontent.com/8255332/139453624-ed2fd746-8c08-4983-8cc8-7db4ecd297a1.png)
![image](https://user-images.githubusercontent.com/8255332/139453200-2e2ebf6e-8d1e-4a96-9751-91488f100523.png)

My question: Is it possible to change `javax.crypto.Cipher` in SecureKeystore.java with Facebook Conceal, is recommended? 

https://github.com/facebookarchive/conceal

Thank you so much!

**Comment by ammarahm-ed** [comment]
We have moved away from used Secure Preferences. Instead those are replaced by Encrypted Preferences. Min API Level recommended is 23 but 21 can work too.
