### ISSUE TITLE
Encryption questions

### ISSUE THREAD

**Issue by nikolal** [ammarahm-ed/react-native-mmkv-storage#179]
Hi,

We have a several project security requirements:

 - Data must be encrypted
 - Data must be deleted every 24-72 hours
 - We will have a lot of images so large data size

1) Our initial idea is:
- Create an encrypted database instance on the server
- Fetch it in background and save it in the app

The problem with this approach is that we can't find a way to use the data in mobile app even if we set the same encryption key for both instances. Is there a way to pass the same encryption key to either `withEncryption()` or `decrypt()` so we can achieve this?

2) Is there a better way to fetch data from server and use it in the app. Especially images?

**Comment by ammarahm-ed** [comment]
Storing images in database is not a great idea. You should prefer storing images as files in cache storage instead. Each image can be encrypted and stored and decrypted when required.

All other data should be small enough that when user launches the app, the data can be fetched from server and stored in the app.

**Comment by nikolal** [comment]
@ammarahm-ed  
Yes, we are aware of this. We already did some testing and we noticed mmkv can handle a lot of base64 images without any issues.  
We are still in research phase so we want to see all possible options before we start. 
 
So the only question we currently have is:

Is it possible to create the encrypted instance on server and read it on device using the same encryption key?

**Comment by ammarahm-ed** [comment]
@nikolal I don't think that would be possible. To should instead encrypt individual data and store it on server and fetch it on demand.

**Comment by nikolal** [comment]
Thanks, I will close this.
