### ISSUE TITLE
[Bug] Bad array deserialization - Android only

### ISSUE THREAD

**Issue by CinGiu** [ammarahm-ed/react-native-mmkv-storage#180]
I use this to persist a complex object, something like this: 
```
{
   name: 'giulio',
   store: {
      key: [27, 234, 123, 34, 31, 236, 216, 68, 165, 240, 80, 45, 9, 48, 238, 130, 132, 194, 87, 40, 7, 238, 187, 177, 56, 131, 60, 124, 174, 248, 209, 245]
  }
}

```

i use simply the `setMapAsync` method with that object to save it. 

on Android only, when i read back this value it show up with bad serialization, deserializating the array into an object like below:
```
{
   name: 'giulio',
   store: {
      key:  {"0": 27, "1": 23, "10": 80, "11": 45, "12": 9, "13": 48, "14": 238, "15": 130, "16": 132, "17": 194, "18": 87, "19": 40, "2": 123, "20": 7, "21": 238, "22": 187, "23": 177, "24": 56, "25": 131, "26": 60, "27": 124, "28": 174, "29": 248, "3": 34, "30": 209, "31": 245, "4": 31, "5": 236, "6": 216, "7": 68, "8": 165, "9": 240}
  }
}

```

in iOS all works fine. 

**Moreover**
I had the same application into an Expo project that works fine both for android and ios platform. 
Now i'm switching to pure react-native project and this exact code do not works anymore on android. 

**Platform Information:**
 - OS:Android only
 - React Native Version: 0.66.1
 - Library Version 0.6.6

**Additional context**
Not an Expo project. Pure react-native

**Comment by ammarahm-ed** [comment]
Did you try to run `JSON.stringify` and `JSON.parse` on the object and see the final output after?

**Comment by CinGiu** [comment]
Yes same result.
It seems that the stringify/parse is the main problem. 
I think internally you perform this to save the object, isn't you? 
I can't get why with expo frameworks worked, there is some polyfill performed by expo i don't know?

**Comment by ammarahm-ed** [comment]
> Yes same result.
> It seems that the stringify/parse is the main problem. 
> I think internally you perform this to save the object, isn't you? 
> I can't get why with expo frameworks worked, there is some polyfill performed by expo i don't know? 

Are you using hermes or jsc?

**Comment by CinGiu** [comment]
> > Yes same result.
> > It seems that the stringify/parse is the main problem.
> > I think internally you perform this to save the object, isn't you?
> > I can't get why with expo frameworks worked, there is some polyfill performed by expo i don't know?
> 
> Are you using hermes or jsc?

No, they are not enabled by default with the last react-native version. I just run the react-native init from scratch. 
Sorry i'm not a big expert, i've read into documentation right now 🙈
