### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'. error: package com.ammarahmed.mmkv does not exist

### ISSUE THREAD

**Issue by mikekeehnen** [ammarahm-ed/react-native-mmkv-storage#182]
When I follow the steps on https://rnmmkv.vercel.app/#/gettingstarted I get the following error: 

```
C:\Users\mikek\Documents\Projects\Fancee%20App\android\app\src\main\java\com\artiesten\...\CustomMMKVJSIModulePackage.java:2: error: package com.ammarahmed.mmkv does not exist
import com.ammarahmed.mmkv.RNMMKVModule;
                          ^
C:\Users\mikek\Documents\Projects\Fancee%20App\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:21: error: package com.ammarahmed.mmkv does not exist
import com.ammarahmed.mmkv.RNMMKVPackage;
                          ^
C:\Users\mikek\Documents\Projects\Fancee%20App\android\app\src\main\java\com\project\name\CustomMMKVJSIModulePackage.java:16: error: cannot find symbol
        reactApplicationContext.getNativeModule(RNMMKVModule.class).installLib(
                                                ^
  symbol:   class RNMMKVModule
  location: class com.project.....CustomMMKVJSIModulePackage
C:\Users\mikek\Documents\Projects\Fancee%20App\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:78: error: cannot find symbol
      new RNMMKVPackage(),
          ^
  symbol:   class RNMMKVPackage
  location: class com.facebook.react.PackageList
Note: C:\Users\mikek\Documents\Projects\Fancee%20App\android\app\src\debug\java\com\artiestenapp\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I used the npx mmkv-link command, this resulted in the following files:

- CustomMMKVJSIModulePackage.java
```import com.ammarahmed.mmkv.RNMMKVModule;
import com.facebook.react.bridge.JSIModuleSpec;
import com.facebook.react.bridge.JavaScriptContextHolder;
import com.facebook.react.bridge.ReactApplicationContext;

import java.util.List;

import com.swmansion.reanimated.ReanimatedJSIModulePackage;



public class CustomMMKVJSIModulePackage extends ReanimatedJSIModulePackage {
    @Override
    public List<JSIModuleSpec> getJSIModules(ReactApplicationContext reactApplicationContext, JavaScriptContextHolder jsContext) {
        reactApplicationContext.getNativeModule(RNMMKVModule.class).installLib(
            jsContext,
            reactApplicationContext.getFilesDir().getAbsolutePath() + "/mmkv"
        );

        return super.getJSIModules(reactApplicationContext, jsContext);
    }
}
```

- MainApplication.java
```

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.BV.LinearGradient.LinearGradientPackage;
import io.invertase.firebase.analytics.ReactNativeFirebaseAnalyticsPackage;
import io.invertase.firebase.app.ReactNativeFirebaseAppPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;

import com.project.name.CustomMMKVJSIModulePackage;
import com.facebook.react.bridge.JSIModulePackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected JSIModulePackage getJSIModulePackage() {
            return new CustomMMKVJSIModulePackage();
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();

    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.artiestenapp.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}
```
- build.gradle

```      buildscript {
    ext {
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.2')
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
}
```

Any ideas on where it could go wrong?

**Comment by ammarahm-ed** [comment]
Did you run `yarn add react-native-mmkv-storage@latest`? 

Also in MainApplication.java, `com.project.name` should be replaced with your package name....

**Comment by mikekeehnen** [comment]
I did install the latest version and the package name is shared in both the MainApplication.java as the CustomMMKVJSIModulePackage.java files. I think there was a ndk mismatch, so I installed the "21.4.7075529" ndk. 
Only think now is that a cmake error...

`* What went wrong:
Execution failed for task ':react-native-mmkv-storage:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\mikek\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C C:\Users\mikek\Documents\Projects\Fancee%20App\node_modules\react-native-mmkv-storage\android\.cxx\cmake\debug\armeabi-v7a rnmmkv}
  ninja: Entering directory `C:\Users\mikek\Documents\Projects\Fancee%20App\node_modules\react-native-mmkv-storage\android\.cxx\cmake\debug\armeabi-v7a'
  [1/38] Building CXX object core/CMakeFiles/core.dir/MMKVLog.cpp.o
  [2/38] Building CXX object core/CMakeFiles/core.dir/CodedInputData_OSX.cpp.o
  [3/38] Building CXX object core/CMakeFiles/core.dir/MMKVLog_Android.cpp.o
  [4/38] Building CXX object core/CMakeFiles/core.dir/CodedInputData.cpp.o
  [5/38] Building CXX object core/CMakeFiles/core.dir/CodedInputDataCrypt_OSX.cpp.o
  [6/38] Building CXX object core/CMakeFiles/core.dir/PBUtility.cpp.o
  [7/38] Building CXX object core/CMakeFiles/core.dir/MMKV_Android.cpp.o
  [8/38] Building CXX object core/CMakeFiles/core.dir/CodedInputDataCrypt.cpp.o
  [9/38] Building CXX object core/CMakeFiles/core.dir/MiniPBCoder.cpp.o
  [10/38] Building CXX object core/CMakeFiles/core.dir/MMKV.cpp.o
  [11/38] Building CXX object CMakeFiles/rnmmkv.dir/C_/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp.o
  FAILED: CMakeFiles/rnmmkv.dir/C_/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp.o
  C:\Users\mikek\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi21 --gcc-toolchain=C:/Users/mikek/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/mikek/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Drnmmkv_EXPORTS -IC:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/rnmmkv -IC:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/React -IC:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/React/Base -IC:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi -IC:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/. -IC:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native-mmkv-storage/MMKV/Core -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -O0 -fno-limit-debug-info  -fPIC   -std=c++1z -MD -MT CMakeFiles/rnmmkv.dir/C_/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp.o -MF CMakeFiles\rnmmkv.dir\C_\Users\mikek\Documents\Projects\Fancee%20App\node_modules\react-native\ReactCommon\jsi\jsi\jsi.cpp.o.d -o CMakeFiles/rnmmkv.dir/C_/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp.o -c C:/Users/mikek/Documents/Projects/Fancee%20App/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp
  depfile has multiple output paths[12/38] Building CXX object core/CMakeFiles/core.dir/MMKV_IO.cpp.o
  [13/38] Building CXX object core/CMakeFiles/core.dir/MMKV_OSX.cpp.o
  [14/38] Building CXX object core/CMakeFiles/core.dir/MiniPBCoder_OSX.cpp.o
  [15/38] Building CXX object core/CMakeFiles/core.dir/KeyValueHolder.cpp.o
  [16/38] Building CXX object core/CMakeFiles/core.dir/MMBuffer.cpp.o
  [17/38] Building CXX object core/CMakeFiles/core.dir/InterProcessLock.cpp.o
  [18/38] Building CXX object core/CMakeFiles/core.dir/CodedOutputData.cpp.o
  [19/38] Building CXX object core/CMakeFiles/core.dir/InterProcessLock_Win32.cpp.o
  [20/38] Building CXX object core/CMakeFiles/core.dir/InterProcessLock_Android.cpp.o
  [21/38] Building CXX object core/CMakeFiles/core.dir/MemoryFile_Android.cpp.o
  [22/38] Building CXX object core/CMakeFiles/core.dir/MemoryFile_Win32.cpp.o
  [23/38] Building CXX object core/CMakeFiles/core.dir/MemoryFile.cpp.o
  [24/38] Building CXX object CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o

  ninja: build stopped: subcommand failed.



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s

    at makeError (C:\Users\mikek\Documents\Projects\Fancee%20App\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\mikek\Documents\Projects\Fancee%20App\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\mikek\Documents\Projects\Fancee%20App\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (C:\Users\mikek\Documents\Projects\Fancee%20App\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.`


I've added the cmake dir to my local props and installed cmake via Android Studio, but that didn't seem to fix it:

`cmake.dir=C\:\\Users\\mikek\\AppData\\Local\\Android\\Sdk\\cmake\\3.10.2.4988404`

**Comment by ammarahm-ed** [comment]
The example app is building correctly so there is some issue in your code. Try to compare with it.
