### ISSUE TITLE
[Bug] Upgrade from 0.3.7 to 0.4.4: data cannot be retrieved on iOS

### ISSUE THREAD

**Issue by durac** [ammarahm-ed/react-native-mmkv-storage#183]
**Describe the bug**
After upgrading react-native-mmkv-storage from v0.3.7 to v0.4.4 in my project all data stored by 0.3.7 is lost.

**To Reproduce**
1. Create an app with react-native-mmkv-storage v0.3.7;
2. Save some data using e.g. setString
3. Upgrade to react-native-mmkv-storage v0.4.4;
4. Update your app on iOS
5. Data previously stored cannot be loaded

**Expected behavior**
The data stored with v0.3.7 is also loaded with v0.4.4

**Platform Information:**
 - OS: iOS
 - React Native Version 0.66.2
 - Library Version 0.4.4

**Comment by ammarahm-ed** [comment]
Firstly you should upgrade directly to 0.6.x instead of 0.4.4.

Secondly, there was a breaking change in 0.4.x in which the directory where MMKV files are stored was changed from Documents to Library. You can easily fix that by a simple patch:

1. Install patch-package https://www.npmjs.com/package/patch-package

2. Create a file `patches/react-native-mmkv-storage+0.6.8.patch` and add the following contents:

```
diff --git a/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm b/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm
index 09d3ac5..41eb306 100644
--- a/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm
+++ b/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm
@@ -77,13 +77,14 @@ BOOL functionDiedBeforeCompletion = YES;
     mmkvInstances = [NSMutableDictionary dictionary];
     serviceNames = [NSMutableDictionary dictionary];
     
-    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory,
+    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,
                                                          NSUserDomainMask, YES);
     NSString *libraryPath = (NSString *)[paths firstObject];
     NSString *rootDir = [libraryPath stringByAppendingPathComponent:@"mmkv"];
     rPath = rootDir;
+    
     _secureStorage = [[SecureStorage alloc] init];
-    [MMKV initializeMMKV:rootDir];
+    [MMKV initializeMMKV];
     [self migrate];
     install(*(jsi::Runtime *)cxxBridge.runtime);
 }

```

**Comment by smrubin** [comment]
@ammarahm-ed Is this still the recommended patch? After applying this patch, I am no longer able to build the app (using expo).

**Comment by smrubin** [comment]
It seems that just doing the first part of this patch is what is needed:
```
-    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory,
+    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,
```
