### ISSUE TITLE
[Bug] Upgrade from 0.3.7 to 0.6.6 leads to crash on Android when updating app

### ISSUE THREAD

**Issue by durac** [ammarahm-ed/react-native-mmkv-storage#184]
**Describe the bug**
After upgrading react-native-mmkv-storage from v0.3.7 to v0.6.6 in my project updating the Android production build leads to a crash every time starting the app. When installing the app with react-native-mmkv-storage v0.6.6 without having the old version installed everything works fine.

**To Reproduce**
1. Create an app with react-native-mmkv-storage v0.3.7;
2. Save some data using e.g. setString
3. Upgrade to react-native-mmkv-storage v0.6.6;
4. Update your app on android to the new version
5. App crash

**Expected behavior**
Updating an app using react-native-mmkv-storage v0.3.7 to the newer version 0.6.6 does not lead to a crash

**Platform Information:**
- OS: Android
- React Native Version 0.66.2
- Library Version 0.6.6

**Comment by ammarahm-ed** [comment]
Can you share some crash log? Use `adb logcat`. Also did you follow the upgrading guide and docs? There are some new changes. Please read the docs to properly install v0.6.6.

**Comment by durac** [comment]
Sure! Thanks for looking into it. Also as written in the documentation I added `getJSIModulePackage` and if the old version of my app is not installed everything works fine

[crash-logs.txt](https://github.com/ammarahm-ed/react-native-mmkv-storage/files/7528446/crash-logs.txt)

**Comment by nachozullo** [comment]
Same here

**Comment by ammarahm-ed** [comment]
Will investigate

**Comment by ammarahm-ed** [comment]
@durac @nachozullo Can you guys try the master branch? I have fixed and tested this to be working. The issue seems to be fixed.

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
I am closing this. Let me know if you still face a problem
