### ISSUE TITLE
[Question] How do I completely remove a database instance?

### ISSUE THREAD

**Issue by traviswsims** [ammarahm-ed/react-native-mmkv-storage#185]
**Describe the question**
After creating a database instance, I can clear the contents of the instance with `clearStore` and `clearMemoryCache` but I cannot actually remove the instance.  That is, when I call `getAllMMKVInstanceIDs` the old instances are still there (albeit they are empty).  My app has many instances due to the size of the data, and some of those instances use record ids as their names.  On user logout, I would like to completely remove all instances.

**To Reproduce**
```
import MMKVStorage from "react-native-mmkv-storage";

const MMKVwithID = new MMKVStorage.Loader()
  .withInstanceID("mmkvWithID")
  .initialize();

MMKVwithID.clearStore();
MMKVwithID.clearMemoryCache();

const MMKV = new MMKVStorage.Loader().initialize();

MMKV.getAllMMKVInstanceIDs();  //  ["mmkvWithID", "default"]
```

**Expected behavior**
Remove an instance so that it is no longer on the phone or present in `getAllMMKVInstanceIDs()`.

**Platform Information:**
 - OS: Android
 - React Native Version: 0.64.2
 - Library Version: 0.6.6

Thank you for a great library, and thank you in advance for your comments.

**Comment by ammarahm-ed** [comment]
Hey @traviswsims You cannot completely remove an instance at the moment. However calling `clearMemoryCache` is sufficient to free the memory. And calling `clearStore` clears everything so it's an empty file. If you are sure that you won't be accessing the same instance anytime soon, you can use any storage lib like RNFS and delete the instance file.  `MMKV.getAllMMKVInstanceIDs()` is just for referencing. It does not mean that the instance is still in memory. 

In future I will add a function that will completely remove an instance & delete its file from storage too.

**Comment by traviswsims** [comment]
@ammarahm-ed Thank you very much for your speedy and helpful reply.  I'll check out RNFS.

I greatly appreciate your hard work!  What a maintainer!
