### ISSUE TITLE
[Bug] TypeScript compilation

### ISSUE THREAD

**Issue by hatem-72** [ammarahm-ed/react-native-mmkv-storage#187]
**Describe the bug**
Running `tsc` in a react-native project using this (awsome) lib along TypeScript 4.5 (did not check earlier versions) leads to compilation error because of wrong declarations inside `index.d.ts` (details below).

**To Reproduce**
1. Init RN/TS project: `npx react-native init MyProject --template react-native-template-typescript && cd MyProject && yarn`
2. Install lib: `yarn add react-native-mmkv-storage`
3. Check ts: `npx tsc`
4. See compilation errors

**Expected behavior**
No TS compilation error.

**Screenshots**
Compilation errors:
![image](https://user-images.githubusercontent.com/86654761/143421541-8748597f-b29e-4b52-9fed-05b419134e5d.png)

**Platform Information:**
 - React Native Version 0.66.3
 - Library Version 0.6.6
 - Typescript version 4.5.2

**Additional context**
Enabling flag `skipLibCheck` in `tsconfig.json` may fix this issue but is only a workaround.

On my side I patched the lib for now.

I would be happy to contribute by opening a PR but I didn't quite understand the contribution process so I opened this issue.

Line 54, 55 --> Remove `declare` statement
```ts
export function getAllMMKVInstanceIDs(): string[];
export function getCurrentMMKVInstanceIDs(): Record<string, boolean>;
```

This will prevent error `A 'declare' modifier cannot be used in an already ambient context.` to occur.

Line 370, 490, 538 --> Add `declare` statement
```ts
declare class indexer {}
declare class encryption {}
declare class transcations {}
```

This will prevent error `Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.` to occur.

**Comment by ammarahm-ed** [comment]
It will be great if you can send a PR.
