### ISSUE TITLE
[Bug]Android\Sdk\ndk\21.4.7075529 did not have a source.properties file

### ISSUE THREAD

**Issue by namhihi237** [ammarahm-ed/react-native-mmkv-storage#189]
**Describe the bug**

**To Reproduce**
yarn add react-native-mmkv-storage
npx mmkv-link

![image](https://user-images.githubusercontent.com/39086067/143880522-298fb5aa-32b3-470c-87db-565ba145f177.png)

**Platform Information:**
 - OS: [Android]
 - React Native Version 0.66.2
 - Library Version ^0.6.6

**Comment by frodoe7** [comment]
Hey,

I'm facing the same issue,
if you can share how did you solve it?
