### ISSUE TITLE
[Question] Class Component  problem

### ISSUE THREAD

**Issue by tuncaybahadir** [ammarahm-ed/react-native-mmkv-storage#190]
Hello to everyone,

Maybe my question is very simple, I'm new to react native. I was able to run the package in my const App = () array, but whatever I did in my class xxx extends Component array didn't work. I keep getting {"_U": 0, "_V": 1, "_W": undefined, "_X": null}. I'll be happy if you can help me.

`import React, { Component } from "react";

import { Text} from 'react-native';

import MMKVStorage, { useMMKVStorage } from "react-native-mmkv-storage";

const MMKV = new MMKVStorage.Loader().initialize();

class test extends Component {

      constructor(props) {
        super(props);

        MMKV.setStringAsync('asd', 'AAAA');
        MMKV.setIntAsync("number", 33);

      }

      

    render() {

      let aaa = MMKV.getStringAsync('asd');
      console.log('AAA : ', JSON.stringify(aaa));

      let number =  MMKV.getIntAsync("number");
          console.log('BBB : ', number);

        return ( 

      <Text>Test</Text>
         
        )
    }

};

export default test;`

**Comment by ammarahm-ed** [comment]
Use `async/await` or call synchronous methods like `getString` & `setString`.

**Comment by tuncaybahadir** [comment]
Hi Ahmed,

Thanks for your answer, Unfortunately the only answer I get at the moment is undefined. Thanks for your help.

![resim](https://user-images.githubusercontent.com/1303432/145273242-668483f4-9e96-455a-99e6-0228665e4439.png)
