### ISSUE TITLE
Using deprecated lib for encrypting Android shared prefs (for older versions of Android)

### ISSUE THREAD

**Issue by dougkeen** [ammarahm-ed/react-native-mmkv-storage#191]
I noticed [this secure-preferences lib](https://github.com/scottyab/secure-preferences) is used to implement encrypted SharedPreferences, but the lib is no longer maintained and the author is recommending Google's own `androidx` implementation.

> Please use EncryptedSharedPreferences from androidx.security in preferenced to secure-preference. (There are no active maintainers Secure-preferences)

**Comment by ammarahm-ed** [comment]
> I noticed [this secure-preferences lib](https://github.com/scottyab/secure-preferences) is used to implement encrypted SharedPreferences, but the lib is no longer maintained and the author is recommending Google's own `androidx` implementation.
> 
> > Please use EncryptedSharedPreferences from androidx.security in preferenced to secure-preference. (There are no active maintainers Secure-preferences)

Its only for older android versions. For newer keychain is used. Newer impl is not available on older androids.

**Comment by dougkeen** [comment]
Right, I mention it because the androidx implementation of EncryptedSharedPreferences (`androidx.security.crypto.EncryptedSharedPreferences`) provides the same backwards compatibility for older Android versions that `scottyab/secure-preferences` does, but it's still maintained by Google, which is why the lib author posted the deprecation notice.

[It seems like the androidx lib also has all the fallback behavior for older Android versions already built in](https://developer.android.com/topic/security/data), so you may be able to simplify the `react-native-mmkv-storage` Android implementation by using that single lib rather than doing your own version detection.

Edit: Looks like the Androidx lib only supports API level 21+, so I supposed the deprecated lib may still be the only option if  this lib is still targeting API 16+ 🤔

**Comment by ammarahm-ed** [comment]
Its the only option below android 21. The deprecated lib words for android 16-21.
