### ISSUE TITLE
Android Build Running failed

### ISSUE THREAD

**Issue by rishavdebroy-gloify** [ammarahm-ed/react-native-mmkv-storage#192]
Execution failed for task ':react-native-mmkv-storage:generateJsonModelDebug'.
> java.nio.file.FileSystemException: C:\Users\ACER\Desktop\mobile\node_modules\react-native-mmkv-storage\android\.cxx\cmake\debug\armeabi-v7a\android_gradle_build_stderr_rnmmkv_armeabi-v7a.txt: The process cannot access the file because it is being used by another process.

Every time I run the app I face the above issue. How Can I fix this.Please help me

**Comment by ammarahm-ed** [comment]
Closing because this seems to be an issue with your operating system. restarting/clearing node_modules folder may help.
