### ISSUE TITLE
[Question] Class Component problem, Not Fix

### ISSUE THREAD

**Issue by tuncaybahadir** [ammarahm-ed/react-native-mmkv-storage#193]
I guess it's a new tradition to close requests without seeing if the problem is solved.

![resim](https://user-images.githubusercontent.com/1303432/145273242-668483f4-9e96-455a-99e6-0228665e4439.png)

_Originally posted by @tuncaybahadir in https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/190#issuecomment-989138078_

**Comment by 8BallBomBom** [comment]
Try initialising MMKV in the component constructor.
You might find the render function is being called before MMKV has finished initialising.
Which would result in things being undefined for a little while.

**Comment by tuncaybahadir** [comment]
> 

Thanks a lot for your reply,

I will try and write the answer. I hope the ticket doesn't close before it's done...

**Comment by tuncaybahadir** [comment]
> 
Right now I think it has written the data. But I am having trouble accessing the data.

I also tried this.prop.MMKV but I always get an error.

As I wrote before, I'm new to react native, thanks for your help.

One : 

![resim](https://user-images.githubusercontent.com/1303432/145613486-abfb17de-44fc-4a97-bcee-9403f9d50a75.png)

Two : 

![resim](https://user-images.githubusercontent.com/1303432/145613747-4bde502c-2ec7-458d-b55d-832f6e092413.png)

**Comment by ammarahm-ed** [comment]
Hey, have you followed the installation steps properly? Please check the docs. I think you have missed linking the library after installing. @tuncaybahadir

**Comment by ammarahm-ed** [comment]
> Try initialising MMKV in the component constructor.
> You might find the render function is being called before MMKV has finished initialising.
> Which would result in things being undefined for a little while.

Mmkv inits instantly. Its synchronous.

**Comment by tuncaybahadir** [comment]
@ammarahm-ed thanks for your answer. I will re-install from scratch and I will write the answer here.

**Comment by 8BallBomBom** [comment]
From what it seems you have created the variable inside the constructor function and thus it will also only be accessible within that function.

But from that point you didn't appear to experience any errors setting the variables.
What you should do is create a var outside the component, not a const, then set the var as the MMKV Initialise function inside the constructor or a componentDidMount function.
Then after that in the render function which gets called pretty quickly you should prevent rendering entirely if the var isn't defined or use conditional rendering for that purpose.

You could also use the async functions to get a better result.
Or convert the component into a functional component and use the hooks [here](https://rnmmkv.vercel.app/#/usemmkvstorage).
If you need an example i could throw something together 👍🏻

**Comment by tuncaybahadir** [comment]
Sorry for replying so late.

Unfortunately, I haven't been able to make any progress. I rebuilt the project. I also did the link process, but the result is still the same.

@8BallBomBom I would be very happy if you could send a sample.

**Comment by tuncaybahadir** [comment]
Sometimes a solution can be found with stubbornness. I'm adding the code below so that no one messes with it like me. 

Thank you all.

```js 
import React, { Component } from "react";

import { Text} from 'react-native';

import MMKVStorage from "react-native-mmkv-storage";

const MMKV = new MMKVStorage.Loader().initialize();

const setData = () => {
    MMKV.setString("testKey", "test value");
  }
  
  const getData = () => {
    let data = MMKV.getString('testKey');
    console.log('Data : ',data);
    return data;
  }

class test extends Component {

  constructor(props) {
    super(props);

    setData();
 

  }

render() {
  
  let finalData = getData();

    return ( 

        <Text>Get Data : {finalData}</Text>
     
    )
}

};

export default test;
```
