### ISSUE TITLE
dispatch queue usage is not safe

### ISSUE THREAD

**Issue by esprehn** [ammarahm-ed/react-native-mmkv-storage#2]
Each operation is making a new dispatch queue which means they're all running in a random concurrent order. See also: 
https://stackoverflow.com/questions/7923800/dispatch-queue-create-multiple-invocations-with-same-label/7923834

You need to use the same queue instance across all operations otherwise all the JS operations are happening in a random order and doing:

removeItem()
setItem()

Can result in the item being removed after it's set.

**Comment by esprehn** [comment]
Btw this is also true when calling the same operation. 

setString("a", "b")
setString("a", "c")

The value can end up "b".

**Comment by ammarahm-ed** [comment]
Thank you for pointing this out. I will look into it ASAP.

**Comment by ammarahm-ed** [comment]
I have made an attempt to fix the dispatch queue issue as you mentioned.
