### ISSUE TITLE
[Question] How to invert value using custom useStorage hook?

### ISSUE THREAD

**Issue by maarten-22** [ammarahm-ed/react-native-mmkv-storage#201]
I made a custom useStorage hook as described in the docs that wraps useMMKVStorage:

```ts
const MMKV: MMKVStorage.API = new MMKVStorage.Loader().initialize();

export const useStorage = <Type>(key: string, defaultValue: Type): [Type, (value: Type | ((prevState: Type) => void)) => void] => {
    const [value, setValue] = useMMKVStorage(key, MMKV, defaultValue);
    return [value, setValue];
};
```

and use it in my component like this:
```tsx
const [warning, setWarning] = useStorage(Storage.WARNING, false);

<CustomButton
   onPress={() => setWarning(!warning)}
/>
```
However, when I press the button I get an error:
`Component Exception. null is not an object (evaluating 'Storage.WARNING')`

`Storage.WARNING` is just a simple enum with a `string` value.

I can't figure out why this happens.

**Comment by ammarahm-ed** [comment]
Check if `Storage` is null. I think you have forgotten to import `Storage` object in the component imports in your file. 

```js
export const Storage = {
       WARNING:"warning"
}
```
Then import it in your component file and use.

**Comment by maarten-22** [comment]
Hi @ammarahm-ed, thanks a lot for your quick reply! Storage is not null, it's pretty much the same as your example.
```ts
export enum Storage {
    WARNING = 'notification.warning',
}
```

**Comment by ammarahm-ed** [comment]
Does putting the key directly without an enum work? `useStorage("warningkey", false)` 

In my example Storage is an MMKV instance. Here you are using Storage for some other purpose. Try putting the Storage object in the same file outside your component and see if that is working.

**Comment by maarten-22** [comment]
Hmm, using a key directly like this `const [warning, setWarning] = useStorage('notification.warning', false);` does work. Why does this matter?

**Comment by maarten-22** [comment]
Whoops! I accidentally had another call with the same key in a different file which was resetting the state...
Thanks for the help tho, really appreciated!
