### ISSUE TITLE
[Bug] mmkv-link shouldn't change Gradle distribution in react native 0.67

### ISSUE THREAD

**Issue by pnthach95** [ammarahm-ed/react-native-mmkv-storage#204]
**Describe the bug**
React native 0.67 just released. It uses gradle 7.2. `mmkv-link` command changes it to 6.9

**To Reproduce**
1. Create new project with react native 0.67
2. Install  `react-native-mmkv-storage`
3. Run `npx mmkv-link`

**Expected behavior**
Gradle distribution shouldn't be changed

**Platform Information:**
 - OS: Android
 - React Native Version 0.67
 - Library Version 0.6.9

**Comment by ammarahm-ed** [comment]
@pnthach95 Will address this

**Comment by ammarahm-ed** [comment]
Can you try now with master? I have fixed it:

```
npm install https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by pnthach95** [comment]
Tested on RN 0.67 and 0.64, it runs well.

**Comment by ammarahm-ed** [comment]
Okay great. I will release a new version.
