### ISSUE TITLE
[Question] Expo compatibility

### ISSUE THREAD

**Issue by fobos531** [ammarahm-ed/react-native-mmkv-storage#207]
Hello - first of all, thanks for the awesome library, I'm using it in multiple projects and it's always worked very reliably for me. I scoured the repo for information on Expo support and noticed that it's suggested to eject from Expo to use this library. While this makes perfect sense, with the advent of Expo dev clients and Expo config plugins, it's been increasingly possible to use previously-incompatible libraries with Expo managed workflow. Is that something you think this project and the ecosystem would benefit from? A similar library - react-native-mmkv - has implemented a way to automate the setup of the library in a way that it makes it compatible with Expo - see https://github.com/mrousavy/react-native-mmkv/commit/d0c6f016d6eaca47e7f517413c64d658ba09fbc9

Is that something that would possible here as well?

Thanks in advance!

**Comment by ammarahm-ed** [comment]
@fobos531 I will work on this. Seems like this should fix #195

**Comment by ammarahm-ed** [comment]
@fobos531 give it a try with an expo project:

install from master:
```
 https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
then run `expo prebuild`

**Comment by fobos531** [comment]
Thank you for the prompt response! I'm currently a bit busy with real-life stuff but I'll try it as soon as possible

**Comment by Wyctus** [comment]
> install from master:
> 
> ```
>  https://github.com/ammarahm-ed/react-native-mmkv-storage.git
> ```
> 
> then run `expo prebuild`

Hello @ammarahm-ed ,

we tried in our project and seems working fine, thank you for your work!
Is there any plan to publish this version to npm?

**Comment by ammarahm-ed** [comment]
@Wyctus i think the version on npm already published. The master branch is for next release.

**Comment by Wyctus** [comment]
@ammarahm-ed 
Thank you, it works perfectly!
Could you please update the docs, so everybody can know about this great improvement?

**Comment by ammarahm-ed** [comment]
@Wyctus  I have updated the docs.

**Comment by Wyctus** [comment]
Thank you very much!
