### ISSUE TITLE
[Bug] Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by pnthach95** [ammarahm-ed/react-native-mmkv-storage#208]
**Describe the bug**

I upgraded 0.4.4 to 0.6.10 and release new version of the app. While I don't have any issue, I see this crash report from users:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

com.ammarahmed.mmkv.RNMMKVModule.migrate RNMMKVModule.java:98
com.ammarahmed.mmkv.RNMMKVModule.installLib RNMMKVModule.java:66
[package name here].CustomMMKVJSIModulePackage.getJSIModules CustomMMKVJSIModulePackage.java:16
com.facebook.react.ReactInstanceManager.createReactContext ReactInstanceManager.java:1376
com.facebook.react.ReactInstanceManager.access$1200 ReactInstanceManager.java:138
com.facebook.react.ReactInstanceManager$5.run ReactInstanceManager.java:1104
java.lang.Thread.run Thread.java:923

```
Affected devices are Galaxy Note10+ and Galaxy A50.
Affected OS is Android 11.

**To Reproduce**
1. Create new project using version 0.4.4 and save some data
2. Upgrade version 0.4.4 to 0.6.10
3. Build, install and open, see if it crashes or not

Sadly, I can't reproduce it. Maybe you can or understand what happened

**Expected behavior**
App doesn't crash in production.

**Screenshots**

**Platform Information:**
 - OS: Android 11
 - React Native Version 0.67.1
 - Library Version 0.6.10

**Comment by ammarahm-ed** [comment]
@pnthach95 i will look into this asap.

**Comment by ammarahm-ed** [comment]
@pnthach95  Hey I have fixed the bug. Can you try: 

```
npm install https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
Let me know if everything gets okay. I will publish a new version.

**Comment by pnthach95** [comment]
No issues for me. I'll release it for users and wait a day and see if anyone report bug.

**Comment by unfernandito** [comment]
Hi @ammarahm-ed!

We had the same issue within our app in production. So many users with specific models(Samsung S10e, Samsung S10+, OnePlus) after the new update of the lib(github directly) continue experiment a crash at the initial boot.

I will check the logcat stacktrace from one mobile in which can be reproduce the issue and attach it to this thread soon.

**Comment by ammarahm-ed** [comment]
@unfernandito Send me some logs. Even from your crash reports. That might be useful.

**Comment by unfernandito** [comment]
![image](https://user-images.githubusercontent.com/6326186/151174853-25108235-de7a-43ef-94b1-08266c37bb7e.png)

Right now this the only crash which i can see, our codebase it's obfuscated so is complicated detect some kind of native crash

**Comment by unfernandito** [comment]
Update: Solved in a Samsung S20 ultra with the latest git version.

**Comment by ammarahm-ed** [comment]
@unfernandito The logs seem to not mention anything related to this library. Maybe you have missed the log which is causing the crash?

**Comment by unfernandito** [comment]
@ammarahm-ed That's a crash from play console, i have not any plain crash in our sentry project, but the issue it's the same  which was reported, this library was the only updated in our native codebase, previous version not crash

**Comment by ammarahm-ed** [comment]
@unfernandito The current fix from master should solve this issue I think. If not we can investigate more.

**Comment by unfernandito** [comment]
@ammarahm-ed Thanks, i will try to provide you more information of any crash.

I got a question, how many contributors are working with you in this lib?

**Comment by ammarahm-ed** [comment]
@unfernandito At the moment it is just myself. However any PRs are welcome You can see a number of people have contributed to this library.

**Comment by unfernandito** [comment]
@ammarahm-ed update: The fix resolved the issue in many devices, just one need to reset the data storage of the app, our incident is marked as resolved and now we are deploying new version of the app.

Thanks for the fix and if you need help with something like publish new versions, security deps resolution or any kind of help we are open to contribute you

**Comment by ammarahm-ed** [comment]
@unfernandito I am glad your app is working as expected now. Regarding help, it would be great if you can contribute in any way possible. I am open to ideas and things that can be done. Please let me know how you can help.

**Comment by ammarahm-ed** [comment]
Hey @pnthach95 was your issue resolved?

**Comment by pnthach95** [comment]
There is no reports so far. I guess it was resolved.
