### ISSUE TITLE
[Question] Docs for encryption.

### ISSUE THREAD

**Issue by KJ-GM** [ammarahm-ed/react-native-mmkv-storage#210]
**Question:**

I don't fully understand the encryption usage process, I am creating only one instance of encryption for the whole app,

``` js
const MMKVwithEncryption = new MMKVStorage.Loader()
  .withEncryption()
  .initialize();

// Can I just store and retrieve values from the `MMKVwithEncryption` instance and that's it?

MMKVwithEncryption.setBool("encryptedBoool", true)

const value = MMKVwithEncryption.getBool("encryptedBoool")
```
Do I have to do anything else ? Because I have seen some encrypt and decrypt methods in docs which I am not sure I understand their usage when the library handles all the encryption process.

A simple  example would be helpful.

**Comment by ammarahm-ed** [comment]
@KJA-Tsx yes that's it. You don't need to do anything else. Everything is encrypted and secure.

Use the library and all the methods. Everything works the same for encrypted and non-encrypted instances
