### ISSUE TITLE
[Talk] Should useMMKVStorage default value be automatically stored?

### ISSUE THREAD

**Issue by maarten-22** [ammarahm-ed/react-native-mmkv-storage#211]
I really like the library so far, especially the useMMKVStorage hook as you might have noticed :). It's been a great addition to my app. I was wondering about a possible feature I need, and if I should implement it myself or if it could be an feature in the library.

So let's say I have a custom `useStorage` hook:
```js
const useStorage = (key, defaultValue) => {
    const mmkv = useRef(MMKVService.getInstance()).current;
    const [value, setValue] = useMMKVStorage(key, mmkv, defaultValue);

    return [value, setValue];
};
```

This works fine, but for a feature I need to access the `defaultValue` even when there have been no changes made using the hook (it just doesn't know if there was a value set before). So when I use `mmkv.getItem('key')` somewhere outside of the component and the value has never changed, it finds `null` as result. This only happens the first time for a value, because when `setValue` has been called it will store as expected.

I can easily solve this by adding a check in my custom hook, something like this:
(this is a simplified version ofcourse. Would need to check the value type of `defautlValue` to call right `mmkv.set()`)
```js
const useStorage = (key, defaultValue) => {
    const mmkv = useRef(MMKVService.getInstance()).current;
    const [value, setValue] = useMMKVStorage(key, mmkv, defaultValue);
   
    // also check in storage to prevent `null` value
    const storedValue = useRef(mmkv.getItem('key'));
    if (storedValue === null) {
        mmkv.setItem('key', defaultValue);
    }    

    return [value, setValue];
};
```
This results in the value being set, even when the  `setValue` was never called. This way I can get `defaultValue` outside the component.
Do you think the `useMMKVStorage()` hook should automatically set it's value to the storage when initialized, or is it too specific for my use case?

**Comment by ammarahm-ed** [comment]
I like the idea. Initially i also had thought about this the same way as you are thinking. The only issue is that what happens when the value gets deleted. So lets say you delete the default value from storage with `removeItem`. The hook will add the value back again into storage. This would be nice for some people but some people would be frustrated that even after removing the value. It is not removed? What do you 🤔 think?

**Comment by maarten-22** [comment]
Ah, didn't think of that when writing the post. I've been thinking about this for a bit now and maybe one of these are a solution?
1. Add another hook; `usePersistedMMKVStorage()`. This hook would re-initialize the defaultValue every time it's null. The value can still be set to null using `setValue` or be deleted via `removeItem` but it would reset to the default value when the hook is 'mounted' again.

2. Add another parameter to existing `useMMKVStorage` hook, either:
`useMMKVStorage(key: string, mmkv: mmkvStorage.api, defaultvalue: any, persistStorage?: boolean)`. Setting this value to `true` would make the hook always re-initialize the value when it's null (only when called again, so it can still be deleted outside of the component). Making the parameter optional makes sure there are no breaking changes with backwards compatibility. Leaving the value undefined just makes the hook act normal.

Or add an optional `options` parameter, so that it can be expanded in the future if more options would be needed. E.g:
```
useMMKVStorage(
   key, 
   mmkv, 
   defaultValue, 
   { 
      persistStorage: true,
      // some other fields that might be added in the future, so it stays backwards compatible
   }
)
```

**Comment by ammarahm-ed** [comment]
I will think about this. Any app would follow one pattern, either all defaultValues are persisted or none are. So maybe defining it globally makes sense somewhat and keeps everything neat and clean. 

```js
new MMKVStorage.Loader().withPersistedDefaultValues().initialize()
```

**Comment by maarten-22** [comment]
That’s also a good idea. Makes more sense if it was defined globally indeed. I’ll just build a custom hook for now, but if you decide to implement a feature please ping me so I can use it in the future :)

**Comment by ammarahm-ed** [comment]
This is wip. Will come in v0.7.0
