### ISSUE TITLE
[Bug] Using this lib with React Native Reanimated 2

### ISSUE THREAD

**Issue by 7dp** [ammarahm-ed/react-native-mmkv-storage#212]
**Describe the bug**
I want to use this lib along with Reanimated 2. On Reanimated 2 installation guide I have to add some code to `MyApplication.java` file. The problem is that's the same code from this lib was already have been there.

Reanimated 2 installation guide:
https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation#android

<img width="991" alt="Screen Shot 2022-02-03 at 16 44 02" src="https://user-images.githubusercontent.com/49138064/152319968-2ccba925-77cb-4eb3-888d-c12aae3ce16f.png">

Result when I try to add above function to `MyApplication.java` :

<img width="698" alt="Screen Shot 2022-02-03 at 16 51 20" src="https://user-images.githubusercontent.com/49138064/152320124-10d8e5cf-bc8a-4253-a824-24ef31e4b628.png">

So when i try to run on android, of course the build fails with error:

```
android/app/src/main/java/com/starter/MainApplication.java:47: error: method getJSIModulePackage() is already defined in class <anonymous com.starter.MainApplication$1>
        protected JSIModulePackage getJSIModulePackage() {
```

**Platform Information:**
 - OS: Android
 - React Native Version: 0.66.4
 - Library Version: 0.6.8

So, how to overcome the build fails in android?

Thanks for this amazing lib!

**Comment by ammarahm-ed** [comment]
Upgrade to the latest version of library. It does not require editing MainApplication.java file

**Comment by 7dp** [comment]
Wow! thanks for your quick reply. I will try it.

**Comment by ammarahm-ed** [comment]
> Upgrade to the latest version of library. It does not require editing MainApplication.java file

Delete node_modules folder
Install v0.6.12 with `npm install react-native-mmkv-storage@latest`.

**Comment by 7dp** [comment]
okay

**Comment by 7dp** [comment]
Okay, now it works perfectly on android. Thanks @ammarahm-ed !
