### ISSUE TITLE
Geting cmake error

### ISSUE THREAD

**Issue by harensarma** [ammarahm-ed/react-native-mmkv-storage#214]
in android:

BUILD FAILED in 48s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/src/main/java/com/ammarahmed/mmkv/SecureKeystore.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/src/main/java/com/ammarahmed/mmkv/RNMMKVModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/fullmad/Projects/dollse/app/dollseRider/android/app/src/debug/java/com/dollserider/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt: Build command failed.
  Error while executing process /Users/fullmad/Library/Android/sdk/cmake/3.18.1/bin/cmake with arguments {-H/Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=21 -DANDROID_PLATFORM=android-21 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/fullmad/Library/Android/sdk/ndk/21.4.7075529 -DCMAKE_ANDROID_NDK=/Users/fullmad/Library/Android/sdk/ndk/21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=/Users/fullmad/Library/Android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/fullmad/Library/Android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_CXX_FLAGS=-fexceptions -frtti -std=c++1y -DONANDROID -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/build/intermediates/cxx/Debug/l81y322e/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/build/intermediates/cxx/Debug/l81y322e/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/.cxx/Debug/l81y322e/arm64-v8a -GNinja -DANDROID_STL=c++_shared -DNODE_MODULES_DIR=/Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/../../../node_modules}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/fullmad/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/fullmad/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The ASM compiler identification is Clang
  -- Found assembler: /Users/fullmad/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
  -- Configuring done
  -- Generating done
  
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as
  
      project(ProjectName)
  
    near the top of the file, but after cmake_minimum_required().
  
    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /Users/fullmad/Projects/dollse/app/dollseRider/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by ammarahm-ed** [comment]
Can you share the react native version you are using? Also which command did you use to build your project?

**Comment by vanhungoz** [comment]
i have the same issue on react native 0.67

**Comment by vanhungoz** [comment]
i just run `npx react-native run-android`

**Comment by mozamelkohestani** [comment]
I get the same error after upgrading Android Gradle Plugin Version to 7.1.0.

**Comment by ammarahm-ed** [comment]
Build in CI is passing with gradle 7.x.x. 

Run `./gradlew clean` in android folder
Delete node_modules folder. 
Then run `yarn install`
Then run the app again

**Comment by ammarahm-ed** [comment]
Can you try the master branch:

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by brobin002** [comment]
Yes this is working with Gradle 7.0.4, thank you !!

**Comment by ammarahm-ed** [comment]
@brobin002 Thanks for testing. Fix will be available in upcoming v0.7.0 release.

**Comment by antFrancon** [comment]
@ammarahm-ed I had a similar issue after upgrading to `react-native 0.68`.
Switching to `0.7.0` fixed it.

Do you plan to publish `0.7.0` ?

**Comment by ammarahm-ed** [comment]
@antFrancon Soon
