### ISSUE TITLE
[Question] Debugger for storage

### ISSUE THREAD

**Issue by KJ-GM** [ammarahm-ed/react-native-mmkv-storage#216]
**Question**

Is there any available  plugin that can be used to view the storage changes/values using flipper debugger?

**Comment by ammarahm-ed** [comment]
@KJ-GM You cannot view all key/values stored at once. However you can log all changes in the storage using `Transactions`. You can go to docs to read more about them

**Comment by KJ-GM** [comment]
Alright thank you. One more question, I read your blog about the react native `JSI`, is this new architecture for react native ready now ? if not how long do you think until everything setup?

**Comment by ammarahm-ed** [comment]
@KJ-GM The new architecture will be out in RN 0.68 officially. This library already uses it.

**Comment by KJ-GM** [comment]
Great, thanks for info!
