### ISSUE TITLE
[Bug] UI API called on a background thread

### ISSUE THREAD

**Issue by rosem** [ammarahm-ed/react-native-mmkv-storage#218]
Getting this error anytime I'm trying to access a value from storage.

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 596, TID: 61581, Thread name: com.facebook.react.JavaScript, Queue name: com.apple.root.default-qos.overcommit, QoS:

**Comment by ammarahm-ed** [comment]
@rosem Does this cause a crash or comes out as a warning?

**Comment by rosem** [comment]
Comes out as a warning and seemingly locks the app for 10 seconds or so. I'm using MMKV to keep track of a counter (int) value to assign to some photos that were selected from the Photo Library.

**Comment by ammarahm-ed** [comment]
@rosem Okay I will fix this asap. Thanks for reporting.

**Comment by rosem** [comment]
OK. Thank you. One thing I noticed is that it happens once. Like the first time, I select a set of photos. If I open the picker again and select photos it doesn't happen again.

**Comment by ammarahm-ed** [comment]
@rosem Is your instance encrypted or a normal one?

**Comment by rosem** [comment]
@ammarahm-ed Normal.
`_storage = new MMKVStorage.Loader().withInstanceID("userProfile").initialize()`

**Comment by ammarahm-ed** [comment]
@rosem I have fixed it.. Can you give it a try:

```bash
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
Run `pod install`

**Comment by ammarahm-ed** [comment]
Fixed. Closing.

**Comment by rosem** [comment]
I did:
```
npm install react-native-mmkv-storage
cd ios
pod install
```

Still getting the same error.

**Comment by ammarahm-ed** [comment]
Use this command to install instead:

```
npm install https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
Then 
```
cd ios && pod install
```

**Comment by rosem** [comment]
OK. That did it. Thanks!
