### ISSUE TITLE
[Bug] MMKV build failed in Android

### ISSUE THREAD

**Issue by frodoe7** [ammarahm-ed/react-native-mmkv-storage#219]
**Describe the bug**
I just try to build the app after installing the library in my project

* What went wrong:
A problem occurred configuring project ':react-native-mmkv-storage'.
> com.android.builder.errors.EvalIssueException: NDK at /Users/Mac/Library/Android/sdk/ndk/21.4.7075529 did not have a source.properties file

**Screenshots**
Error details

* Exception is:

> org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':react-native-mmkv-storage'.
>         at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
>         at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
>         at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:51)
>         at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:195)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
>         at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
>         at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:105)
>         at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$0(DefaultProjectStateRegistry.java:325)
>         at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$withProjectLock$3(DefaultProjectStateRegistry.java:385)
>         at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:211) ....

**Platform Information:**
 - OS: Android
 - React Native Version : 0.67.2
 - Library Version : 0.67.2

**Additional context**
I think this issue is related **189**
#189

**Comment by ammarahm-ed** [comment]
@frodoe7 You must install NDK from Android Studio SDK Manager first before using this library.

**Comment by frodoe7** [comment]
@ammarahm-ed
It's already installed
because the other projects are working normally
