### ISSUE TITLE
[Question] - Couple of questions to ask

### ISSUE THREAD

**Issue by alz10** [ammarahm-ed/react-native-mmkv-storage#220]
**1. Update in Google Playstore**
- Can i still get the data from previous version of the app after a new update in Google Playstore? I'm developing a quiz app, it has levels and every correct answer are saved in `MMKV`. What if I suddenly made an update for the app and then users decided to update it in the Google Playstore. Will the users be able to restore the data from previous version of the app? Let say user1 is in level 50 and user2 is in level 100. Are they still on those levels after the update?

**2. Maximum total storage size?**
- What is the default total storage size? AsyncStorage has 6 MB of storage by default. Tried searching on `https://rnmmkv.vercel.app/` but no info provided

**3. How to know the device current MMKV storage size?**
- How do i know how much MMKV size I've stored already in my device? Is there a way to get that information? Let say on my quiz app, my current level is 200 (already stored 200 array of objects for example). How much device storage was used already to save that?

**4. Need advice**
- As mentioned above, I'm developing a quiz app. The app is expected to have 1000+ levels or 5000+ if the app became viral/hit. Would you recommend this library for saving such a huge amount of levels/data in the long run? The application is pure offline and no intention in making it online. I'm only saving array of objects. If you can't recommend this library for this type of application, what database would you recommend? Is `react-native-sqlite-storage` good for this app?

**Comment by ammarahm-ed** [comment]
> 1. Update in Google Playstore

When a user updates from a previous version of the app to a newer version. The data will be retained just like it is retained with AsyncStorage. However **if** the user **uninstalls the app** and reinstalls it, the data will be deleted. You can also test this **(and should)** before releasing a new version of the app to playstore.

 1. Install old version of the app locally from an older commit/release tag.
 2. Update to the version of the app you want to release on playstore. Data should be retained.

> 2. Maximum total storage size?

There is no limit of maximum storage size. You can store GBs of data and be fine as long as the system has space left on the phone.

> 3. How to know the device current MMKV storage size?

At the moment you can't know how much space is taken by to storage but I will consider adding it in future.  You should be fine storing information.

**Comment by alz10** [comment]
@ammarahm-ed Thank you so much!
