### ISSUE TITLE
[Bug] Unable to load app in chrome debugger

### ISSUE THREAD

**Issue by djkirby** [ammarahm-ed/react-native-mmkv-storage#221]
**Describe the bug**
Can't debug app in chrome

**To Reproduce**
- Launch react native app
- cmd + d to debug in chrome
--> fails, says MMKVNative bindings not installed

Upon investigation this is from this line,
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/master/src/mmkv/init.ts#L21

throws this error,

```
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```

**Expected behavior**
App should be debuggable in chrome

**Platform Information:**
 - OS: ios
 - React Native Version 0.66.3
 - Library Version 0.6.12

**Comment by ammarahm-ed** [comment]
@djkirby Chrome debugging is not supported by this library at the moment.

**Comment by alimohi** [comment]
@ammarahm-ed Is there any chance to have chrome debugging in this version? it would be too difficult to debug the app. I've upgraded the library in my current project in order to prevent Play Store from alerting about encryption method.

**Comment by ammarahm-ed** [comment]
@alimohi at the moment it is not possible to debug on chrome with JSI based libraries at the moment. 

You can use Flipper to debug the app if needed. 

If you need debug the app in chrome you can try using the memory adapter in `jest` folder on main branch.

Just copy the code in it and call `mock` at the root index.js point in your app. This will only work in memory, so if you reload the app, all values we be lost.

**Comment by djkirby** [comment]
> @alimohi at the moment it is not possible to debug on chrome with JSI based libraries at the moment.
> 
> You can use Flipper to debug the app if needed.
> 
> If you need debug the app in chrome you can try using the memory adapter in `jest` folder on main branch.
> 
> Just copy the code in it and call `mock` at the root index.js point in your app. This will only work in memory, so if you reload the app, all values we be lost.

Hm, I tried calling `mock()` as soon as my index.ts starts, and changed this line to return `true` if the bindings aren't installed https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/master/src/mmkv/init.ts#L32

But I still see in the console,

```
 LOG  JavaScript logs will appear in your browser console
Error: Unable to resolve module ./debugger-ui/ui.e31bb0bc.js from ///

None of these files exist:
  * debugger-ui/ui.e31bb0bc.js(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.cjs|.cjs|.native.svg|.svg)
  * debugger-ui/ui.e31bb0bc.js/index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.cjs|.cjs|.native.svg|.svg)
    at ModuleResolver.resolveDependency (.../ModuleResolution.js:107:15)
```

**Comment by ammarahm-ed** [comment]
@djkirby i will check and report a working version.

**Comment by djkirby** [comment]
@ammarahm-ed wondering if you had a chance to look all, I'm happy to help with a pr if you point me in the right direction :)

**Comment by ammarahm-ed** [comment]
@djkirby It might not be possible to debug with chrome debugger while this library is installed. Mainly due to some limitations of JSI and the native and JS code running on a single thread.

**Comment by ammarahm-ed** [comment]
Hey @djkirby I was actually able to get it to work in memory. You can test it out by trying the master branch. 

```
npm install https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
Support for remote debugging with memory adapter is built in now so you don't need to take the steps I mentioned above. When you switch to remote debugging, it will automatically switch to memory adapter.

**Comment by ammarahm-ed** [comment]
This will ship in v0.7.2

**Comment by djkirby** [comment]
Thanks for the update @ammarahm-ed !

**Comment by alexstock1** [comment]
still not working, @ammarahm-ed  what should be done to make it working?

**Comment by HumayounBaig** [comment]
any update on this? its really becoming a pain to debug
