### ISSUE TITLE
UseIndex does not allow for generics and only return unknown

### ISSUE THREAD

**Issue by delfu** [ammarahm-ed/react-native-mmkv-storage#223]
**Describe the bug**
When using the library with typescript, `useIndex` seems to not allow for generics and will only return `unknown` as return types.

**To Reproduce**
1. use `useIndex` in typescript
2. check the type of the return

**Expected behavior**
first element of the return result should be typed

**Platform Information:**
 - Library Version 0.6.12

**Comment by ammarahm-ed** [comment]
@delfu The library has been fully migrated to typescript with type generics but not released yet. You can try the master branch if you need it.
