### ISSUE TITLE
[Bug] Jest directory in not bundled in the npm package

### ISSUE THREAD

**Issue by francois-pasquier** [ammarahm-ed/react-native-mmkv-storage#224]
The [documentation about jest](https://github.com/ammarahm-ed/react-native-mmkv-storage/tree/master/jest) is wrong:

The `react-native-mmkv-storage/jest` directory is not bundled in the npm package.

Checked on version `0.6.12`

**Comment by ammarahm-ed** [comment]
Its not released yet. You can use the master branch if you need jest for now. It will be release in v0.7.0
