### ISSUE TITLE
[Bug] Error: MMKVNative bindings not installed

### ISSUE THREAD

**Issue by aazam476** [ammarahm-ed/react-native-mmkv-storage#229]
**Describe the bug**
Getting "Error: MMKVNative bindings not installed"

**To Reproduce**
1. Install "react-native-mmkv-storage" using the command "expo install react-native-mmkv-storage"
2. Use "react-native-mmkv-storage" as shown below3. 
``` JS
import MMKVStorage, { useMMKVStorage } from "react-native-mmkv-storage";
const storage = new MMKVStorage.Loader().initialize();
const username = "";
const password = "";
async function temp(){
      const [username, setUsername] = useMMKVStorage("username", storage, username);
      const [password, setPassword] = useMMKVStorage("password", storage, password);
}
```

**Expected behavior**
I expect "react-native-mmkv-storage" to run like normally and save the items as shown in the code

**Screenshots**
<img width="1015" alt="Screen Shot 2022-04-06 at 11 39 56 AM" src="https://user-images.githubusercontent.com/78570129/162013881-a8169afb-be4c-46df-b77a-0c88728a4139.png">

**Platform Information:**
 - OS: iOS
 - Expo Version: 5.3.0

**Additional context**
N/A

**Comment by ammarahm-ed** [comment]
Use expo managed workflow to make mmkv work.

**Comment by alexstock1** [comment]
@ammarahm-ed why this bug is closed if issue is not resolved?

Highly unprofessional from your side, please re-open it
