### ISSUE TITLE
[Bug] Typescript problem - Cannot find namespace 'MMKVStorage'

### ISSUE THREAD

**Issue by unfernandito** [ammarahm-ed/react-native-mmkv-storage#236]
**Describe the bug**

Hello @ammarahm-ed how are you?

The latest version broke my typescript build, looks like cannot find the index.d.ts file in the package.

**To Reproduce**
1. Install the latest version (0.7.1)
2. Run the tsc command

**Expected behavior**
Build my typescript code.

**Screenshots**
![image](https://user-images.githubusercontent.com/6326186/163810742-ee3f4172-784c-49b3-b7c5-585e30445699.png)

**Platform Information:**
 - React Native Version 0.67.1
 - Library Version 0.7.1

**Additional context**
I tried with the 0.7.0 version and got the same error.

**Comment by ammarahm-ed** [comment]
That's strange because the latest version comes with pre built js and d.ts files in dist folder. Try deleting node_modules folder then run npm install again.

**Comment by unfernandito** [comment]
i'll try

**Comment by unfernandito** [comment]
After run a fresh install i got the same behavior, my tsc continue broken, looks like something related to my tsconfig, i'll try update typescript to 4.5 version

**Comment by unfernandito** [comment]
i've updated to typescript 4.5.5 and continue failing me, i'll try some other stuff and if i find something, i'll send you a PR

**Comment by unfernandito** [comment]
@ammarahm-ed i can't make a fork to try to fix it, but i think is broken the reference to the declaration files. I think this problem it's related to my config. but i can't figure out which could be the issue.

In other way, i think the dist folder should only exist while is running the publish action, right now your dist folder is outdated, if you run the `npm run build` script, the files changed and maybe something is failing.

**Comment by ammarahm-ed** [comment]
I think the type MMKVStorage.API does not exist in the latest typings which is why you are getting this error

**Comment by unfernandito** [comment]
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/master/dist/index.d.ts#L9

Seems exist in the declaration file, it's so weird.

**Comment by ammarahm-ed** [comment]
@unfernandito Can you try the master branch? I have fixed this.

Use `import {API} from "react-native-mmkv-storage"` instead for types

**Comment by unfernandito** [comment]
i'll try it

**Comment by unfernandito** [comment]
Ok, API namespace it's fixed, but all the others are no exported, how can i contribute you with this changes?

The repo seems to be reach the maximum forks allowed

**Comment by ammarahm-ed** [comment]
@unfernandito You have already forked it I think. Check your repositories list. Which others are you using?

**Comment by unfernandito** [comment]
🕺  i'm so dumb, you are right, i've already forked this repo

**Comment by unfernandito** [comment]
https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/239

**Comment by ammarahm-ed** [comment]
Hey @unfernandito Can you try the master again and see if it resolves all errors? The PR you have sent is a breaking change and I am looking for a way to not break the API. You can now export `MMKVStorageInterface` for any types you need.

**Comment by unfernandito** [comment]
I'll try, thanks you

**Comment by unfernandito** [comment]
![image](https://user-images.githubusercontent.com/6326186/164247489-369e4d2f-e76d-4f39-ba7a-f8dbf667d5ac.png)

Same behavior :/

**Comment by unfernandito** [comment]
![image](https://user-images.githubusercontent.com/6326186/164253293-c6851532-a2fb-4e53-98c0-3c642b2b57e7.png)

i've change the code to this and seems work again.

**Comment by unfernandito** [comment]
@ammarahm-ed could you publish this version in npm plz?

The latest commit can be applied as a fix to this issue 😄

**Comment by unfernandito** [comment]
Hi @ammarahm-ed how are you?

Could you publish the 0.7.3 version with the latests changes?

If you need some help, i'm available to contribute you in this repository.

**Comment by ammarahm-ed** [comment]
@unfernandito I will merge the changes after undoing my last commits

**Comment by unfernandito** [comment]
Thanks you

**Comment by ammarahm-ed** [comment]
@unfernandito Check the latest master branch. Use `import {MMKVLoader} from "react-native-mmkv-storage"`. I have renamed exports to more readable forms. 

API is renamed to MMKVInstance
Loader is renamed to MMKVLoader

**Comment by unfernandito** [comment]
Thanks friend. I'll try tomorrow and come back with the results.

**Comment by unfernandito** [comment]
All it's working well, this change will be breaking change?

**Comment by unfernandito** [comment]
My fault :(

**Comment by ammarahm-ed** [comment]
@unfernandito No it won't be a breaking change. Only deprecating previous  API but it still works the same way.

**Comment by ammarahm-ed** [comment]
I will close this. Will ship it in 0.7.2

**Comment by unfernandito** [comment]
Thanks for all this work!
