### ISSUE TITLE
Update MMKV to 1.2.0

### ISSUE THREAD

**Issue by ammarahm-ed** [ammarahm-ed/react-native-mmkv-storage#24]

**Comment by kyle-ssg** [comment]
@ammarahm-ed https://github.com/Tencent/MMKV/releases/tag/v1.2.0 as of yesterday.

**Comment by ammarahm-ed** [comment]
@kyle-ssg I will update this in a couple of hours hopefully

**Comment by ammarahm-ed** [comment]
new version **v0.3.3** released
