### ISSUE TITLE
[Request] Throwing assertions errors on Javascript side

### ISSUE THREAD

**Issue by focux** [ammarahm-ed/react-native-mmkv-storage#240]
Hey! Today I spent some time trying to figure out why my app was crashing on the native side.  When inspecting the Sentry logs, I found that the error that was making my app crash was this one:

> Assertion failed: (isNumber()), function getNumber, file jsi.h, line 1044

After some time I found out that in some special cases, I was trying to set a value that was not a number using the `setIntAsync`. Obviously, this was my mistake but I was wondering if we could handle those errors on the javascript side instead of crashing the app when that happens.

**Comment by ammarahm-ed** [comment]
@focux I agree. Will add those

**Comment by ammarahm-ed** [comment]
Added. will ship in v0.7.2
