### ISSUE TITLE
[Bug] AppCenter builds fail with ^0.7.1 > C/C++: rnmmkv/CMakeLists.txt release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by kyle-ssg** [ammarahm-ed/react-native-mmkv-storage#242]
**Describe the bug**
Previously, to get builds on AppCenter working we had to uninstall cmake, see https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/132.

After upgrading it seems that maybe we should not do this, running a build results in the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:configureCMakeRelWithDebInfo'.
> C/C++: /Users/runner/work/1/s/mobile/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt release|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  REACT_NATIVE_JNI_LIB
      linked by target "rnmmkv" in directory /Users/runner/work/1/s/mobile/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```

Doing a bit of digging I can see that the runners have 3.10.2.4988404  and 3.18.1 of cmake. I tried adding the following pre-build

```
echo "cmake.dir=$ANDROID_HOME/cmake/3.10.2.4988404" >> android/local.properties
```

However that didn't seem to resolve the issue. 

**To Reproduce**
1. Upgrade to 0.7x from 0.6x
2. Attempt to build with AppCenter

**Expected behavior**
The Build Passes 

**Screenshots**
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/8608314/164466041-ac31a6d7-189b-47d4-a0d0-a4ca745fb5a9.png">

**Platform Information:**
 - OS: Android
 - React Native Version 0.68
 - Library Version 0.71.0

**Comment by rares-lupascu** [comment]
same here

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
REACT_NATIVE_JNI_LIB
linked by target "rnmmkv" in directory /.../node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```

**Comment by ammarahm-ed** [comment]
Can you tell me which build command are you using for the project. on App center

**Comment by ammarahm-ed** [comment]
Hey @kyle-ssg I have written a new fix for build issue. Can you test it:

`npm install https://github.com/ammarahm-ed/react-native-mmkv-storage.git`

I have tested with AppCenter build command locally and it is working. @rares-lupascu It should work for you too.

I will publish a new version on NPM once you confirm.
