### ISSUE TITLE
[Bug] RN 0.68.1 - fresh project not compiling in android

### ISSUE THREAD

**Issue by rares-lupascu** [ammarahm-ed/react-native-mmkv-storage#243]
**Describe the bug**
cannot compile android

**To Reproduce**
1. created a new project
2. add the library
3. tried to compile android2. Click on '....'

**Expected behavior**
to work :) aka ... compile without errors

**Screenshots**
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
REACT_NATIVE_JNI_LIB
linked by target "rnmmkv" in directory /Users/xxx/Projects/ideomaker/TestMMKV/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv
```

**Platform Information:**
 - OS: Android
 - React Native Version: 0.68.1
 - Library Version: 0.7.1

**Additional context**
created a repo for this => https://github.com/rares-lupascu/test-mmkv

**Comment by ammarahm-ed** [comment]
Which command are you using to build project

**Comment by rares-lupascu** [comment]
i am starting the app from android studio

**Comment by ammarahm-ed** [comment]
@rares-lupascu Run `yarn react-native run-android` once before building from android studio
