### ISSUE TITLE
[Bug] Some functions are not working

### ISSUE THREAD

**Issue by pnthach95** [ammarahm-ed/react-native-mmkv-storage#264]
**Describe the bug**
- I try to create Flipper plugin for your repo, but some functions are not working
- [Transaction manager document](https://rnmmkv.vercel.app/#/transactionmanager) is wrong about `mutator` (`mutator({key: string, value: any})` -> `mutator(key: string, value: any)` and examples)

**To Reproduce**
1. Clone [mmkvtest](https://github.com/pnthach95/mmkvtest) branch `main`
2. Clone [my flipper plugin](https://github.com/pnthach95/flipper-plugin-react-native-mmkv-storage), read [this doc](https://fbflipper.com/docs/extending/loading-custom-plugins/) to add plugin to flipper
3. Open terminal on flipper plugin folder, run `yarn` to install dependencies, run `yarn watch` to build plugin
4. Launch Flipper, run app, enable `RN MMKV Storage` plugin
5. On app, press buttons, see console logs and Flipper logs

**Expected behavior**
Flipper shows every logs when press buttons on app

**Screenshots**

[Video](https://drive.google.com/file/d/1oH-Old2xvs_gwRVLmMvcegSI1bWtYik6/view?usp=sharing)

**Platform Information:**
 - OS: iOS 15.5 and Android 11
 - React Native Version 0.68.2
 - Library Version 0.7.6

**Additional context**

| Function    | Async API          | Sync API           | transactions                      |
| ----------- | ------------------ | ------------------ | --------------------------------- |
| Set boolean | ✅                  | ✅                  | ✅                                 |
| Get boolean | ✅                  | ✅                  | `'boolean', 'onread'` not working |
| Set string  | ✅                  | ✅                  | ✅                                 |
| Get string  | Return `undefined` | Return `undefined` | ✅                                 |
| Set int     | ✅                  | ✅                  | ✅                                 |
| Get int     | ✅                  | ✅                  | `'number', 'onread'` not working  |
| Set map     | ✅                  | ✅                  | `'object', 'onwrite'` not working |
| Get map     | ✅                  | ✅                  | `'object', 'onread'` not working  |
| Set array   | ✅                  | ✅                  | ✅                                 |
| Get array   | ✅                  | ✅                  | `'array', 'onread'` not working   |

**Comment by ammarahm-ed** [comment]
@pnthach95 Thanks for working on a flipper plugin. Well it's strange that some methods are working and others are not? If you build the app and run without flipper plugin and try to get/set values, that works as usual? it's just not working with flipper? Am i correct?

**Comment by ammarahm-ed** [comment]
@pnthach95 I have fixed the bug you mentioned. Transactions were not properly implemented. Can you try the master branch, for me all the above methods are now working after the fix. 

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```

**Comment by pnthach95** [comment]
Tested on master branch, all good.
Wait for your release.

**Comment by ammarahm-ed** [comment]
@pnthach95 I will make the release soon.
