### ISSUE TITLE
App wide access to storage

### ISSUE THREAD

**Issue by dcassese** [ammarahm-ed/react-native-mmkv-storage#273]
I can't seem to figure out the best way to access my mmkv instance from other screens and files in my app?   Do I use context? What's recommend way to do this.  I create my instance in app.js but need to write to it from various Functional components.

**Comment by douugdev** [comment]
You don't need to create MMKV instances inside components, you can load MMKV at a global scope, such as in the docs: 
```ts
import { MMKVLoader, useMMKVStorage } from 'react-native-mmkv-storage';

const storage = new MMKVLoader().initialize();

const App = () => {
  const [user, setUser] = useMMKVStorage('user', storage, 'robert');
  const [age, setAge] = useMMKVStorage('age', storage, 24);

  return (
    <View style={styles.header}>
      <Text style={styles.headerText}>
        I am {user} and I am {age} years old.
      </Text>
    </View>
  );
};
```
just be careful as you need to use hooks such as `useMMKVStorage` inside components (as per [the rules of hooks](https://reactjs.org/docs/hooks-rules.html))

---
I usually create a separate file to hold such instance:
```ts
// storage.ts

const storage = new MMKVLoader().initialize();
export default storage;
```
