### ISSUE TITLE
[Request] Support a setMultipleItems function in the API

### ISSUE THREAD

**Issue by TristanH** [ammarahm-ed/react-native-mmkv-storage#287]
There are many usecases where bulk writes of data _should_ be more efficient than multiple setItems calls.

Maybe the way mmkv works this isn't the case... but if it is, would love `setMultipleItems` and `setMultipleItemsAsync` methods!

As an example, react-native-async-storage supports a method like this: https://react-native-async-storage.github.io/async-storage/docs/api#multiset

**Comment by ammarahm-ed** [comment]
If it's added, should by async on a separate thread so it doesn't block.

**Comment by ammarahm-ed** [comment]
This has been added in v0.10.0

**Comment by TristanH** [comment]
@ammarahm-ed great news!!
