### ISSUE TITLE
[Bug] v0.8.0 doesn't work with RN 0.71

### ISSUE THREAD

**Issue by pnthach95** [ammarahm-ed/react-native-mmkv-storage#300]
**Describe the bug**
RN 0.71 has a lot of change in android folder, so I try to run it with mmkv-storage and it is failed.

**To Reproduce**
1. Generate a new project `npx react-native init RN0710RC4 --version 0.71.0-rc.4`
2. Install mmkv-storage
3. `yarn run android`

**Expected behavior**
Build success and install app to phone and run.

**Screenshots**
I have log
```bash
❯ yarn run android
yarn run v1.22.19
$ react-native run-android
info Starting JS server...
info Installing the app...
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/code/Projects/RN0710RC4/node_modules/react-native-mmkv-storage/android/build.gradle' line: 138

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv-storage'.
> Expected directory '/Volumes/code/Projects/RN0710RC4/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/android' to contain exactly one file, however, it contains no files.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/code/Projects/RN0710RC4/node_modules/react-native-mmkv-storage/android/build.gradle' line: 138

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv-storage'.
> Expected directory '/Volumes/code/Projects/RN0710RC4/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/android' to contain exactly one file, however, it contains no files.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

    at makeError (/Volumes/code/Projects/RN0710RC4/node_modules/execa/index.js:174:9)
    at /Volumes/code/Projects/RN0710RC4/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Volumes/code/Projects/RN0710RC4/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:85:5)
    at async Command.handleAction (/Volumes/code/Projects/RN0710RC4/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Platform Information:**
 - OS: Android
 - React Native Version 0.71.0-rc.4
 - Library Version 0.8.0

**Additional context**
The log is same as #165
Although it is RC release, things may be changed in official release, you should have future-proof solution.

**Comment by pnthach95** [comment]
[Note for library author about android folder](https://github.com/facebook/react-native/blob/main/android/README.md)

**Comment by focux** [comment]
There's an open PR that fixes this: #305

**Comment by VitalyMih** [comment]
+1
The same error

**Comment by robrechtme** [comment]
If you use [patch-package](https://github.com/ds300/patch-package) you can apply this patch in the mean time:

<details>
  <summary>react-native-mmkv-storage+0.8.0.patch</summary>
  
  ```diff
diff --git a/node_modules/react-native-mmkv-storage/android/build.gradle b/node_modules/react-native-mmkv-storage/android/build.gradle
index a806e23..56035e7 100644
--- a/node_modules/react-native-mmkv-storage/android/build.gradle
+++ b/node_modules/react-native-mmkv-storage/android/build.gradle
@@ -1,79 +1,75 @@
-import groovy.json.JsonSlurper
-
 buildscript {
-
   repositories {
-    google()
-    mavenCentral()
-
     maven {
       url "https://plugins.gradle.org/m2/"
     }
+    mavenCentral()
+    google()
   }
   dependencies {
-    classpath 'com.android.tools.build:gradle:4.2.1'
+    classpath 'com.android.tools.build:gradle:7.2.2'
   }
 }
 
-apply plugin: 'com.android.library'
+def resolveBuildType() {
+    Gradle gradle = getGradle()
+    String tskReqStr = gradle.getStartParameter().getTaskRequests()['args'].toString()
 
-def getExtOrDefault(name, defaultValue) {
-  return rootProject.ext.has(name) ? rootProject.ext.get(name) : defaultValue
+    return tskReqStr.contains('Release') ? 'release' : 'debug'
 }
 
-def found = false
-def reactNativeDir = null
-def androidSourcesName = 'React Native sources'
-def parentDir = rootProject.projectDir
+def isNewArchitectureEnabled() {
+  // To opt-in for the New Architecture, you can either:
+  // - Set `newArchEnabled` to true inside the `gradle.properties` file
+  // - Invoke gradle with `-newArchEnabled=true`
+  // - Set an environment variable `ORG_GRADLE_PROJECT_newArchEnabled=true`
+  return project.hasProperty("newArchEnabled") && project.newArchEnabled == "true"
+}
 
-if (rootProject.ext.has('reactNativeAndroidRoot')) {
-  reactNativeDir = rootProject.ext.get('reactNativeAndroidRoot')
-} else {
-  reactNativeDir = new File(
-          projectDir,
-          '/../../../node_modules/react-native/android'
-  )
+if (isNewArchitectureEnabled()) {
+  apply plugin: 'com.facebook.react'
 }
-if (reactNativeDir.exists()) {
-  found = true
-} else {
-  1.upto(5, {
-    if (found) return true
-    parentDir = reactNativeDir.parentFile
 
-    reactNativeDir = new File(
-            parentDir,
-            'node_modules/react-native/android'
-    )
+apply plugin: 'com.android.library'
+
+def safeExtGet(prop, fallback) {
+  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
+}
 
-    if (reactNativeDir.exists()) {
-      found = true
-    }
-  })
+def reactNativeArchitectures() {
+  def value = project.getProperties().get("reactNativeArchitectures")
+  return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
 }
 
-def reactNative = reactNativeDir.absolutePath;
-def reactNativeManifest = file("$reactNative/../package.json")
-def reactNativeManifestAsJson = new JsonSlurper().parseText(reactNativeManifest.text)
-def reactNativeVersion = reactNativeManifestAsJson.version as String
-def (major, minor, patch) = reactNativeVersion.tokenize('.')
-def rnMinorVersion = Integer.parseInt(minor)
+repositories {
+  mavenCentral()
+}
 
 android {
-  compileSdkVersion getExtOrDefault('compileSdkVersion', 28)
+  compileSdkVersion safeExtGet("compileSdkVersion", 28)
 
-  defaultConfig {
-    minSdkVersion getExtOrDefault('minSdkVersion', 21)
-    targetSdkVersion getExtOrDefault('targetSdkVersion', 28)
-    //ndkVersion "21.1.6352462"
+  buildFeatures {
+    prefab true
+  }
 
+  defaultConfig {
+    minSdkVersion safeExtGet('minSdkVersion', 16)
+    targetSdkVersion safeExtGet('targetSdkVersion', 28)
     externalNativeBuild {
       cmake {
-        cppFlags "-fexceptions", "-frtti", "-std=c++1y", "-DONANDROID"
-        abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
-        arguments '-DANDROID_STL=c++_shared', "-DNODE_MODULES_DIR=${reactNativeDir.parentFile.parentFile.toString()}", "-DRN_VERSION=${rnMinorVersion}"
+        cppFlags "-O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all"
+        arguments "-DANDROID_STL=c++_shared"
+        abiFilters (*reactNativeArchitectures())
       }
     }
+    packagingOptions {
+    doNotStrip resolveBuildType() == 'debug' ? "**/**/*.so" : ''
+    excludes = [
+            "META-INF",
+            "META-INF/**",
+            "**/libjsi.so",
+      ]
+    }
   }
 
   compileOptions {
@@ -81,69 +77,16 @@ android {
     targetCompatibility JavaVersion.VERSION_1_8
   }
 
-  lintOptions{
-    abortOnError false
-    disable 'GradleCompatible'
-  }
-
   externalNativeBuild {
      cmake {
           path "./src/main/rnmmkv/CMakeLists.txt"
       }
   }
-
-  packagingOptions {
-    excludes = ["**/libc++_shared.so","**/libjsi.so","**/libreactnativejni.so", "META-INF/MANIFEST.MF"]
-  }
-}
-
-repositories {
-  mavenCentral()
-  mavenLocal()
-  google()  
-
-  if (reactNativeDir.exists()) {
-    maven {
-      url reactNativeDir.toString()
-      name androidSourcesName
-    }
-    logger.info(":${project.name}:reactNativeAndroidRoot ${reactNativeDir.canonicalPath}")
-  }
-
-  if (!found) {
-    throw new GradleException(
-            "${project.name}: unable to locate React Native android sources. " +
-                    "Ensure you have you installed React Native as a dependency in your project and try again."
-    )
-  }
- 
 }
 
 dependencies {
   //noinspection GradleDynamicVersion
-  implementation 'com.facebook.react:react-native:+'
+  implementation 'com.facebook.react:react-android:+'
   implementation "androidx.security:security-crypto:1.1.0-alpha03"
   implementation 'com.google.code.gson:gson:2.8.6'
-  def buildType = "debug"
-    tasks.all({ task ->
-        if (task.name == "buildCMakeRelease") {
-            buildType = "release"
-        }
-    })
-    def rnAarMatcher = "**/react-native/**/*${buildType}.aar"
-    if (rnMinorVersion < 69) {
-        rnAarMatcher = "**/**/*.aar"
-    }
-
-  def rnAAR = fileTree("$reactNative").matching({ it.include rnAarMatcher }).singleFile
-  files(rnAAR).each {
-      def file = it.absoluteFile
-      def aarFolder = new File("$buildDir/../$file.name");
-      if (aarFolder.exists()) return;
-      copy {
-        from zipTree(file)
-        into "$buildDir/../$file.name"
-        include "jni/**/*"
-      }
-    }
 }
diff --git a/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt b/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt
index df79f03..c916c92 100644
--- a/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt
+++ b/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt
@@ -1,56 +1,23 @@
 cmake_minimum_required(VERSION 3.9.0)
 
+
 set (PACKAGE_NAME "rnmmkv")
 project(PACKAGE_NAME)
 set (BUILD_DIR ../../../)
+set(CMAKE_VERBOSE_MAKEFILE ON)
+set(CMAKE_CXX_STANDARD 17)
 
 add_subdirectory(../../../../MMKV/Core core)
 
 include_directories(
         ${PACKAGE_NAME}
-        "${NODE_MODULES_DIR}/react-native/React"
-        "${NODE_MODULES_DIR}/react-native/React/Base"
-        "${NODE_MODULES_DIR}/react-native/ReactCommon/jsi"
         "./"
 )
 
-file (GLOB LIBRN_DIR "${BUILD_DIR}/react-native-0*/jni/${ANDROID_ABI}")
-
-if (${RN_VERSION} LESS 65)
- # React Native 0.65.x and below
-  add_library(
-          ${PACKAGE_NAME}
-          SHARED
-          ../../../../../react-native/ReactCommon/jsi/jsi/jsi.cpp
-          ./rnmmkv-adapter.cpp
-  )
- 
-else()
-  # React Native 0.66.x and above
-  add_library(
-          ${PACKAGE_NAME}
-          SHARED
-          ./rnmmkv-adapter.cpp
-  )
-
-  find_library(
-        JSI_LIB
-        jsi
-        PATHS ${LIBRN_DIR}
-        NO_CMAKE_FIND_ROOT_PATH
-  )
-endif()
-
-find_library(
-        LOG_LIB
-        log
-)
-
-find_library(
-        REACT_NATIVE_JNI_LIB
-        reactnativejni
-        PATHS ${LIBRN_DIR}
-        NO_CMAKE_FIND_ROOT_PATH
+add_library(
+        ${PACKAGE_NAME}
+        SHARED
+        ./rnmmkv-adapter.cpp
 )
 
 set_target_properties(
@@ -60,11 +27,13 @@ set_target_properties(
         POSITION_INDEPENDENT_CODE ON
 )
 
+find_package(ReactAndroid REQUIRED CONFIG)
+find_library(log-lib log)
+
 target_link_libraries(
         ${PACKAGE_NAME}
-        ${LOG_LIB}
-        ${REACT_NATIVE_JNI_LIB}
-        ${JSI_LIB}
         core               
+        ${log-lib}         
+        ReactAndroid::jsi  
         android 
 )
\ No newline at end of file

  ```
</details>

**Comment by jkepps** [comment]
@robrechtme thanks for the patch. i'm getting the following errors when running yarn
```sh
**ERROR** Failed to apply patch for package react-native-mmkv-storage

  This happened because the patch file patches/react-native-mmkv-storage+0.8.0.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    patch -p1 -i patches/react-native-mmkv-storage+0.8.0.patch
    npx patch-package react-native-mmkv-storage

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

```

and then when i try to run the patch command
```sh
> patch -p1 -i patches/react-native-mmkv-storage+0.8.0.patch
patching file 'node_modules/react-native-mmkv-storage/android/build.gradle'
patch: **** malformed patch at line 8: buildscript {
```

**Comment by robrechtme** [comment]
@jkepps Make sure to already have `react-native-mmkv-storage@0.8.0` installed and make sure you don't change anything to the patch file. If it still doesn't work, you can manually apply the changes in `node_modules/react-native-mmkv-storage` and then run `npx patch-package react-native-mmkv-storage`.

**Comment by warrenfalk** [comment]
Looks like github comments mangles the format... I went to the pull request and got the two files in robrechtme's patch and created it myself. Here's a gist:

https://gist.github.com/warrenfalk/97702b3908fdb23b6ae8d1bdcdf62316

**Comment by japhet247** [comment]
After applying the patch I am still getting the error below. Please help.
Using react-native v0.71.3

`error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-mmkv-storage:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/CMakeLists.txt: -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/jshewiyo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/jshewiyo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The ASM compiler identification is Clang
  -- Found assembler: /Users/jshewiyo/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
  -- Configuring done
  -- Generating done
  
  C++ build system [configure] failed while executing:
      /Users/jshewiyo/Library/Android/sdk/cmake/3.18.1/bin/cmake \
        -H/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=21 \
        -DANDROID_PLATFORM=android-21 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/Users/jshewiyo/Library/Android/sdk/ndk-bundle \
        -DCMAKE_ANDROID_NDK=/Users/jshewiyo/Library/Android/sdk/ndk-bundle \
        -DCMAKE_TOOLCHAIN_FILE=/Users/jshewiyo/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/Users/jshewiyo/Library/Android/sdk/cmake/3.18.1/bin/ninja \
        "-DCMAKE_CXX_FLAGS=-O2 -frtti -fexceptions -Wall -Wno-unused-variable -fstack-protector-all" \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/react-native-mmkv-storage/android/build/intermediates/cxx/Debug/6b5w7110/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/react-native-mmkv-storage/android/build/intermediates/cxx/Debug/6b5w7110/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/react-native-mmkv-storage/android/.cxx/Debug/6b5w7110/arm64-v8a \
        -GNinja \
        -DANDROID_STL=c++_shared
    from /Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/react-native-mmkv-storage/android
  CMake Warning at /Users/jshewiyo/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
    Using custom NDK path (ANDROID_NDK is set):
    /Users/jshewiyo/Library/Android/sdk/ndk-bundle
  Call Stack (most recent call first):
    /Users/jshewiyo/Library/Android/sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:5 (project)
  
  
  CMake Error at CMakeLists.txt:17 (add_library):
    Target "rnmmkv" links to target "ReactAndroid::jsi" but the target was not
    found.  Perhaps a find_package() call is missing for an IMPORTED target, or
    an ALIAS target is missing?
  
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

    at makeError (/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/execa/index.js:174:9)
    at /Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/jshewiyo/Desktop/PROJECTS/otr/otr-app/otr/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.`

**Comment by ammarahm-ed** [comment]
Fixed in 0.9.0.

**Comment by japhet247** [comment]
Unfortunately, the update did not work for me using react native v0.71.3. I am therefore forced to resort to the other plugin.

**Comment by ammarahm-ed** [comment]
> Unfortunately, the update did not work for me using react native v0.71.3. I am therefore forced to resort to the other plugin.

Hmmm strange 🤔 i tested on a clean android project and everything worked and app is built. React Native version is latest.

**Comment by pnthach95** [comment]
I can confirm v0.9.1 work on RN 0.71.4
https://github.com/pnthach95/mmkvtest/tree/rn71
