### ISSUE TITLE
iOS crashing using encryption on 0.3.5

### ISSUE THREAD

**Issue by kyle-ssg** [ammarahm-ed/react-native-mmkv-storage#31]
The library currently does not seem to work with encryption.

```
2020-07-18 16:13:45.028175+0100 TheApp[4657:690803] [javascript] 'STORAGE', 'SET OBJECT', '2', { data: [Getter/Setter] }
Assertion failed: (data.m_data == nil), function KeyValueHolderCrypt, file /Users/kyle/ssg-frontend-boilerplate/mobile/ios/Pods/MMKVCore/Core/KeyValueHolder.cpp, line 69.
```

Reproduction

     MMKV = new MMKVStorage.Loader()
            // uncommenting this breaks the app
            // .withEncryption()
            .initialize();

**Comment by ammarahm-ed** [comment]
I have tested it, its working normally. RN 0.63 and latest library.

**Comment by ammarahm-ed** [comment]
The issue seems to be with MMKV itself, It has been fixed i think in the latest version of **MMKV v1.2.2**

**Comment by kyle-ssg** [comment]
Ah ok thanks! I will re-open if this becomes an issue
