### ISSUE TITLE
Could there be a speed benefit of using the RNNA Cxx Turbo Modules?

### ISSUE THREAD

**Issue by krystofwoldrich** [ammarahm-ed/react-native-mmkv-storage#311]
In the 0.71 release of React Native, I noticed a simplified interface for [pure Cpp Turbo Modules](https://reactnative.dev/docs/the-new-architecture/cxx-cxxturbomodules).

Could there be some speed gained by removing the Android and iOS middle parts and using the new Cpp interface?

As the whole DB is written in Cpp I would imagine it working pretty well.

**Comment by Bruce-zxy** [comment]
Good idea.

**Comment by ammarahm-ed** [comment]
I don't think it would result in any speed gains. Might help with DX  but migrating to this new way of turbo modules is a pain.
