### ISSUE TITLE
Build failed error

### ISSUE THREAD

**Issue by Vishujain1** [ammarahm-ed/react-native-mmkv-storage#317]
My project is on latest version i.e 0.71.3 it's working fine but when i install react-native-mmkv-storage then i got this error

![Screen Shot 2023-03-01 at 10 15 40 AM](https://user-images.githubusercontent.com/125362603/222047444-c3094ee1-f3ab-4912-8b6f-97cceb7e2fc8.png)

**Comment by XantreDev** [comment]
Duplicate of #316

**Comment by ammarahm-ed** [comment]
Fixed in 0.9.0.
