### ISSUE TITLE
Running slower than Async Storage but only for set/getObject

### ISSUE THREAD

**Issue by kyle-ssg** [ammarahm-ed/react-native-mmkv-storage#32]
Please let me know if I'm doing something wrong here, however..

My intension would be to use this for local storage app state, almost certainly always with encryption.

However, even without encryption I'm seeing consistent performance deficit over the standard AsyncStorage library, my understanding is that maybe this might be faster?

https://github.com/kyle-ssg/mmkv-performance

Average results on iPhone XR

MMKV 63ms
Async Storage 18ms

**Comment by kyle-ssg** [comment]
I have a feeling it's the set that's the issue here, getting is fine. I'm going to split the test up into get and set and rename the issue.

**Comment by kyle-ssg** [comment]
Updated results, the tests were a bit unfair initially in that I wasn't JSON.parsing the results from AsyncStorage.

MMKV
Set: 31ms
Get: 25ms

Async Storage
Set: 17ms
Get: 13ms

**Comment by kyle-ssg** [comment]
Some even more interesting results, if I always do a set/getString rather than object, things get a lot faster and indeed MMKV is faster than AsyncStorage..

MMKV String
Set: 16ms
Get: 11ms

Async Storage
Set: 17ms
Get: 13ms


I think if this is unavoidable it's definitely worth noting that setString with a JSON.stringify/parse can be significantly faster than set/getObject.

Also I'd want to ask the question, is there even a usecase for object storage if it's slower than JSON.parse/stringify? I'm only guessing here but I bet the latency is just it reconverting the string back to an object in native code.

**Comment by ammarahm-ed** [comment]
You are probably right, well this will change once **Fabric comes out next year** and then it might be useful. @kyle-ssg

**Comment by kyle-ssg** [comment]
Oh cool! Good to know @ammarahm-ed
