### ISSUE TITLE
[Bug] TypeScript types for synchronous getters do not include null or undefined

### ISSUE THREAD

**Issue by frw** [ammarahm-ed/react-native-mmkv-storage#320]
**Describe the bug**
TypeScript types for synchronous getters are missing the null or undefined types.

**To Reproduce**
1. Check mmkvinstance.d.ts

**Expected behavior**
Since the value might not have been set yet, TypeScript types for synchronous getters and setters should include the null or undefined types, similar to how the asynchronous version do include the null or undefined types.

**Screenshots**
![image](https://user-images.githubusercontent.com/1888212/224522239-a00e0cf0-c6b3-4e14-9527-f4edd7494872.png)

**Platform Information:**
 - OS: any
 - React Native Version: any
 - Library Version: 0.9.1

**Comment by ammarahm-ed** [comment]
This has been fixed in v0.10.0
