### ISSUE TITLE
[Bug] Duplicate symbol for architecture x86_64 issue due to conflict of same method name as another library

### ISSUE THREAD

**Issue by Alka1703** [ammarahm-ed/react-native-mmkv-storage#323]
**Describe the bug**
Add [react-native-secure-key-store](https://www.npmjs.com/package/react-native-secure-key-store) and [react-native-mmkv-storage](https://www.npmjs.com/package/react-native-mmkv-storage) to a project and compile it for iOS. 

When running the project we get the error: 
› Linking   injiexpo2 » injiexpo2

❌  duplicate symbol '_secureKeyStoreError' in
┌─ libreact-native-mmkv-storage.a(SecureStorage.o)
└─ libreact-native-secure-key-store.a(RNSecureKeyStore.o)

❌  ld: 1 duplicate symbol for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

 
**To Reproduce**
1. Create a empty react native project. 
2. Add [react-native-secure-key-store](https://www.npmjs.com/package/react-native-secure-key-store) and [react-native-mmkv-storage](https://www.npmjs.com/package/react-native-mmkv-storage) to a project. 
3. Run the command `npm run`
4. See the error
<img width="1000" alt="Screenshot 2023-04-18 at 12 54 30 PM" src="https://user-images.githubusercontent.com/28667452/232702634-f24347ef-870c-4180-a926-973bc2020cde.png">

**Platform Information:**
 - OS: [iOS]
 - React Native Version [0.64.4]
 - MMKV Storage Version [0.8.0]
 - Secure key store version [2.0.10]

**Additional context**
The error is due to the conflicting method name `secureKeyStoreError` in both the libraries. The same method is present in SecureStorage.m file in mmkv-storage library and in RNSecureKeyStore.m file in secure-key-store library. We have tried to understand the usage of this method in the mmkv-storage code and couldn't find any usages/references for the same. 

In order to resolve the issue, we tried removing the method and also tried renaming it, both seems to work. 
1. Can you confirm if this is an unused method, if so, do you have plans to remove it in the upcoming releases.
2. If this is a method used somewhere which we couldn't figure out as of now. We would like understand about it and a way to resolve this conflict.

**Comment by ravikp** [comment]
Or are there any other solutions to resolve name conflicts when building react native app with different libraries?

**Comment by ammarahm-ed** [comment]
This has been fixed in v0.10.0
