### ISSUE TITLE
Error: MMKVNative bindings not installed

### ISSUE THREAD

**Issue by jchesne** [ammarahm-ed/react-native-mmkv-storage#324]
**Describe the bug**
Sometimes this error appeared ONLY on Android 13 devices on Crashlitics report.

**Fatal Exception: com.facebook.react.common.JavascriptException: Error: MMKVNative bindings not installed, js engine: hermes**

Do i have to add :
 _implementation 'com.tencent:mmkv:1.2.16'_
 In my build.gradle ?

"react-native-mmkv-storage": "0.8.0"
"react": "18.1.0",
"react-native": "0.70.8"

**Comment by abdullahIsa** [comment]
Hello how was this solved ?
