### ISSUE TITLE
this package itself specifies a `main` module field that could not be resolved

### ISSUE THREAD

**Issue by ohheyitskartik** [ammarahm-ed/react-native-mmkv-storage#335]
I just upgraded from 0.8.0 to 0.9.0 on an RN 71.0 project, got the following error - 
While trying to resolve module `react-native-mmkv-storage` from file `app/utils/mmkv.js`, the package `/node_modules/react-native-mmkv-storage/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-mmkv-storage/dist/index.js`. Indeed, none of these files exist:
`

went to ./dist/index.js as mentioned in package.json, no index.js exists in the .dist directory, where else it does in 0.8.0. Can someone shed a light on this?

**Comment by ohheyitskartik** [comment]
upon waiting a day for a response I dived into it, seems like the pipeline failed for 0.9.0 (https://github.com/ammarahm-ed/react-native-mmkv-storage/actions/runs/4385789963) yet still published a package 

logs are not available for this run, so i can't diagnose the issue.

**Comment by ammarahm-ed** [comment]
Update to v0.9.1. It seems v0.9.0 missed the dist folder by accident.
