### ISSUE TITLE
Build failed react-native 0.73 mmkv-storage android contains no files

### ISSUE THREAD

**Issue by briantes** [ammarahm-ed/react-native-mmkv-storage#345]
When I run npx react-native run-android It throws the next error:
```
A problem occurred evaluating project ':[react-native-mmkv-storage]'.
Expected directory '...\node_modules\react-native-mmkv-storage\android' to contain exactly one file, however, it contains no files.

```
The error is on line 138 of the build.gradle file:
`  def rnAAR = fileTree("$reactNative").matching({ it.include rnAarMatcher }).singleFile`

I have upgraded all modules with yarn upgrade and I'm using the latest react-native version. I have tried to create a fresh new project, add all my sources, and then run yarn install to install all required modules, but with the same result.

**Platform Information:**
 - React Native Version [e.g. 0.73]
 - Library Version [latest]

**Comment by fordat** [comment]
same issue for me

**Comment by ammarahm-ed** [comment]
This has been fixed.
