### ISSUE TITLE
[Bug] Published version is different from `master` branch

### ISSUE THREAD

**Issue by andreialecu** [ammarahm-ed/react-native-mmkv-storage#348]
I'm not sure how this happened, but I'm running into some issues building Detox, which seem to have been fixed by various PRs such as #336 and #340 

However, those changes don't seem to exist in version 0.9.1 - see: https://yarnpkg.com/package?q=react-native-mmkv-storage&name=react-native-mmkv-storage&file=%2Fandroid%2Fbuild.gradle

Compare https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/master/android/build.gradle with the published package above.

@ammarahm-ed any ideas?

**Comment by andreialecu** [comment]
Ok, I see now, npm shows the last release as being 3 months ago, but that's for some alpha version. It appears there were no releases in 1 year, hence the `master` branch diverted.

**Comment by MSE99** [comment]
Hello, any updates on this ?, i really need to setup detox & react native mmkv storage is giving me build errors that were fix in 0.10 alpha which is not available on npm.

**Comment by ammarahm-ed** [comment]
v0.10.3 is released on github and npm.
