### ISSUE TITLE
Memory Leak in IOS | Update to MMVK 1.2.2

### ISSUE THREAD

**Issue by AyushAppin** [ammarahm-ed/react-native-mmkv-storage#35]
Was saving around ~5Mb of data but the device memory usage reached more than 1.4GB and resulted in crash.

**Comment by AyushAppin** [comment]
https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/libMMKV.mm has been updated 4 days ago for the same fix. Please check

Update it to MMVK 1.2.2

**Comment by ammarahm-ed** [comment]
I will update the library

**Comment by ammarahm-ed** [comment]
updated
