### ISSUE TITLE
View database data

### ISSUE THREAD

**Issue by lenovouser** [ammarahm-ed/react-native-mmkv-storage#36]
It would be nice if you could add a method to view all keys / entries currently present in the database

**Comment by ammarahm-ed** [comment]
You can, check the docs.

**Comment by lenovouser** [comment]
Sorry, didn't find it in the docs. Just searched again, is it `await MMKV.indexer.getKeys()`?

**Comment by ammarahm-ed** [comment]
Yes! @lenovouser

**Comment by lenovouser** [comment]
Alright, thank you. Awesome library by the way 👍🏻
