### ISSUE TITLE
[Bug] Build not running on android after new architecture enabled by default on 0.76.  Target "rnmmkv" links to target "ReactAndroid::turbomodulejsijni" but the C/C++:   target was not found.

### ISSUE THREAD

**Issue by alexkey89** [ammarahm-ed/react-native-mmkv-storage#364]
**Describe the bug**
After upgrading to react native 0.76 with new architecture on the build fails

**To Reproduce**
- Upgrade to RN 0.76
- cd android -> run ./gradlew clean (it works)
- Then -> run ./gradlew assembleRelease and the following happens:

**> Task :react-native-mmkv-storage:configureCMakeRelWithDebInfo[arm64-v8a] FAILED**
C/C++: CMake Error at CMakeLists.txt:11 (add_library):
C/C++:   Target "rnmmkv" links to target "ReactAndroid::turbomodulejsijni" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:11 (add_library):
C/C++:   Target "rnmmkv" links to target "ReactAndroid::react_nativemodule_core" but
C/C++:   the target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly. 

**Expected behavior**
The build should run without issues and produce the APK.

**Platform Information:**
 - OS: Android
 - React Native Version 0.76 (which new architecture is enabled by default)

**Comment by alexkey89** [comment]
any chance of quick fixing this? @ammarahm-ed

**Comment by ammarahm-ed** [comment]
> any chance of quick fixing this? @ammarahm-ed 

I will check what I can do to fix this.

**Comment by alexkey89** [comment]
@ammarahm-ed much appreciated! I also tried to modify the CMakeLists.txt but couldn't get it to work.. I'm not familiar with it.

**Comment by masarbazi** [comment]
Any updates?

**Comment by alexkey89** [comment]
issue persists on RN 0.76.1. I'm considering switching to https://github.com/mrousavy/react-native-mmkv

**Comment by iotnoshennyi** [comment]
it seems, for RN 76, in CMake you need to link  ReactAndroid::reactnative instead of  ReactAndroid::turbomodulejsijni and  ReactAndroid::reactnativejni

[here's the fix for the similar issue in Realm lib](https://github.com/realm/realm-js/pull/6912/files#diff-03057ce567d5ff903af3f32ecf9370700841d6f731829872bfbb586b4637877cR71)

**Comment by masarbazi** [comment]
Fixed. As there are some native libraries that are no longer available in RN 76 and react-native-mmkv-storage makes use of them, the build fails. 
You'll need to modify two files
In CMakeLists.txt: remove `ReactAndroid::turbomodulejsijni` and `ReactAndroid::react_nativemodule_core` and then add `ReactAndroid::reactnative`
![image](https://github.com/user-attachments/assets/3f911065-498c-4305-960f-23a211be234c)

also in `build.gradle` add highlighted line:
![image](https://github.com/user-attachments/assets/69f568a9-9fd7-4052-a5d3-43867a9e816d)

**Comment by alexkey89** [comment]
> Fixed. As there are some native libraries that are no longer available in RN 76 and react-native-mmkv-storage makes use of them, the build fails. You'll need to modify two files In CMakeLists.txt: remove `ReactAndroid::turbomodulejsijni` and `ReactAndroid::react_nativemodule_core` and then add `ReactAndroid::reactnative` ![image](https://private-user-images.githubusercontent.com/29546473/381934393-3f911065-498c-4305-960f-23a211be234c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODMxMjcsIm5iZiI6MTczMDM4MjgyNywicGF0aCI6Ii8yOTU0NjQ3My8zODE5MzQzOTMtM2Y5MTEwNjUtNDk4Yy00MzA1LTk2MGYtMjNhMjExYmUyMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEzNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMmFmODhmNWY5YjY3MWRlYmVkZDhmOTQ4YTRmM2E2ODVkYWU1NTcyMTViYzExY2IwZTg2MjY5Y2FiMjQzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6R3scYFlxwiAXiN-Q1BDi7rBffGwdmTKpGaRZVlt4Bc)
> 
> also in `build.gradle` add highlighted line: ![image](https://private-user-images.githubusercontent.com/29546473/381934220-69f568a9-9fd7-4052-a5d3-43867a9e816d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODMxMjcsIm5iZiI6MTczMDM4MjgyNywicGF0aCI6Ii8yOTU0NjQ3My8zODE5MzQyMjAtNjlmNTY4YTktOWZkNy00MDUyLWE1ZDMtNDM4NjdhOWU4MTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEzNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZTUzMmU2YTU2N2I4ZDUzZjk3MzAzMDk1NGRiMzRiOWM4ODA1OTY5NTk1Nzk4YTJlY2JlZmYzNDMwMGMyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dzwU58QeE_HVSn1LV-YKDHmzyDE5_Ocv0h7dFFenfYw)

this seemed to have fixed it. Hopefully a new release will come out soon with this fix so I won't have to do these types of hacks again.

**Comment by alexkey89** [comment]
> > Fixed. As there are some native libraries that are no longer available in RN 76 and react-native-mmkv-storage makes use of them, the build fails. You'll need to modify two files In CMakeLists.txt: remove `ReactAndroid::turbomodulejsijni` and `ReactAndroid::react_nativemodule_core` and then add `ReactAndroid::reactnative` ![image](https://private-user-images.githubusercontent.com/29546473/381934393-3f911065-498c-4305-960f-23a211be234c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODMxMjcsIm5iZiI6MTczMDM4MjgyNywicGF0aCI6Ii8yOTU0NjQ3My8zODE5MzQzOTMtM2Y5MTEwNjUtNDk4Yy00MzA1LTk2MGYtMjNhMjExYmUyMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEzNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMmFmODhmNWY5YjY3MWRlYmVkZDhmOTQ4YTRmM2E2ODVkYWU1NTcyMTViYzExY2IwZTg2MjY5Y2FiMjQzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6R3scYFlxwiAXiN-Q1BDi7rBffGwdmTKpGaRZVlt4Bc)
> > also in `build.gradle` add highlighted line: ![image](https://private-user-images.githubusercontent.com/29546473/381934220-69f568a9-9fd7-4052-a5d3-43867a9e816d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODMxMjcsIm5iZiI6MTczMDM4MjgyNywicGF0aCI6Ii8yOTU0NjQ3My8zODE5MzQyMjAtNjlmNTY4YTktOWZkNy00MDUyLWE1ZDMtNDM4NjdhOWU4MTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEzNTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZTUzMmU2YTU2N2I4ZDUzZjk3MzAzMDk1NGRiMzRiOWM4ODA1OTY5NTk1Nzk4YTJlY2JlZmYzNDMwMGMyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dzwU58QeE_HVSn1LV-YKDHmzyDE5_Ocv0h7dFFenfYw)
> 
> this seemed to have fixed it. Hopefully a new release will come out soon with this fix so I won't have to do these types of hacks again.

my bad.. so now it builds, it creates the apk and runs for development on the emulator ,but.. it crashes and causes this issue:  (NOBRIDGE) ERROR  Error: MMKVNative bindings not installed [Component Stack]. 

Which from what I see was caused when new architecture was enabled. So it's a known issue. https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/266

**Comment by weese** [comment]
See here https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/365

**Comment by alexkey89** [comment]
@ammarahm-ed can you approve the https://github.com/ammarahm-ed/react-native-mmkv-storage/pull/365 pull request? I guess @weese fixed it.

**Comment by ammarahm-ed** [comment]
The PR above doesn't work when i run the example app. i am working on adding support for old and new arch.

**Comment by ammarahm-ed** [comment]
A new version has been released with support for new and old arch.
