### ISSUE TITLE
FR: Biometric auth

### ISSUE THREAD

**Issue by kyle-ssg** [ammarahm-ed/react-native-mmkv-storage#38]
In order to cover every scenario we've been asked to secure storage against a fingerprint unlock to prevent accessing data from an unlocked phone.

Previous secured storage libraries I'd used allowed this, I think it would make sense for a library like this to support that.

The only other way I could see this working is using two libraries, one just to generate and retrieve the encryption key with this library.

**Comment by ammarahm-ed** [comment]
We will have to look into that and how it will be implemented. I will do some research and update on this.
