### ISSUE TITLE
warning " > react-native-mmkv-storage@0.3.7" has incorrect peer dependency "react-native@^0.56.3".

### ISSUE THREAD

**Issue by sayem314** [ammarahm-ed/react-native-mmkv-storage#39]
Workaround:

https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/45afecf306af3da0f8d539f431168335a908e480/package.json#L35-L37

Change to:

```
  "peerDependencies": {
    "react-native": ">=0.56.3"
  }
```

**Comment by amk-cb** [comment]
I am also getting this warning.
Is there any permanent solution instead of a work around?

**Comment by sayem314** [comment]
@amk-cb you can safely ignore this. Author should fix it tho!
