### ISSUE TITLE
Question about chat-like apps

### ISSUE THREAD

**Issue by ftzi** [ammarahm-ed/react-native-mmkv-storage#40]
Hey, just found out this package, nice one!

I am making a Message Logs system for my app, which works very similarly to a messaging app. I came to an issue that I hope someone can point me a faster solution than me creating a new from the scratch.

I will have a Flatlist to display the messages, and the messages may be added to the end of the array/object or somewhere in the middle, on demand if the client doesn't own it.

This package looks to solve part of my issue, but I still don't know how to handle the FlatList data, that may be really long. I want to have some sort of pagination, so I won't have a 10000 length array in the RAM and a long time to update it on new data fetched.

Does any one here have experience on that? Thanks!

**Comment by ftzi** [comment]
@ammarahm-ed I had the idea of having an object of
`{ [logId: string]: { logData: Log } }`, which in Log I have a server timestamp property.
When fetching new data from the server, besides adding the data to this object, I thought of having an array of the order of those messages `[logId, logId...]`.

To know if I own or not a fetched data, I lookup on the object. To know the order and position of it (to add a new log), I compare the timestamps using the array and the expected position. If they have the same timestamp, I will then order it by logId.

This looks good, but, as it uses an array, looks bad having to use setArray for an entire array of 10000 items, for example, for each new data fetched, even if using an timeout to write in batches.

How could I finish this system to have the best performance? Could be there a way to smartly work with this array without having to rewrite it entirely the time?

I saw that there is a Query system. Could it help?

**Comment by nikolal** [comment]
@ammarahm-ed  How did you solve this?
