### ISSUE TITLE
Are multi object writes performant?

### ISSUE THREAD

**Issue by ftzi** [ammarahm-ed/react-native-mmkv-storage#41]
If I want to write 50 objects, like with

```ts
    const promises: Promise<any>[] = [];
    for (const params of paramsArray)
      promises.push(this.MmkvData.setMapAsync(params.logId, params.logData));

    await Promise.all(promises);
```

Does it have a good performance? Are the writes somehow "batched"? Or, if each write takes 10ms, it will take 500ms?

If not, could you add this functionality?

**Comment by ammarahm-ed** [comment]
yes
