### ISSUE TITLE
Add fallback value if data doesn't exist

### ISSUE THREAD

**Issue by ftzi** [ammarahm-ed/react-native-mmkv-storage#44]
Instead of having to wrapping with try/catches, the .getXYZ sync or async should have another parameter of options, having it the prop of fallback, to use it if the value doesn't exists, instead of throwing "Value for key does not exist"

**Comment by ammarahm-ed** [comment]
I will make the changes for this

**Comment by ftzi** [comment]
Shouldn't the return type of getAsync have a union with the null type?

**Comment by ftzi** [comment]
Also, to not open a new issue, what is the behaviour of getMultipleItemsAsync if one value of a key isn't found?

**Comment by ammarahm-ed** [comment]
@SrBrahma I have added fallback value 'null' in the latest version.

Incase value for a key is not found it will return this:

```js
[["yourkey",null], ...otherItems]
```

**Comment by ftzi** [comment]
Yes, my current question is about the Return Type of e.g. getBoolAsync. It is currently Promise\<boolean\>. Shouldn't it be changed to Promise<boolean | null> ? Isn't improbable that the value doesn't exist.

Thanks for the quick reply!

**Comment by ammarahm-ed** [comment]
Yes! I got you now. We need to update types defs. I think I forgot to make the changes.
