### ISSUE TITLE
Persist storage

### ISSUE THREAD

**Issue by ylahssini** [ammarahm-ed/react-native-mmkv-storage#45]
Hi,

I was wondering if react-native-mmkv-storage is backing up the data. Because when I close the app, the data (ex: user data) that I set in mmkv storage is gone. I know the plugin uses memory to store data but how to persist because in my case I am not using redux. Also the data is often very large in terms of size.

thank you in advance

**Comment by ylahssini** [comment]
I created a user MMKV instance and linked it to withEncryption, it worked, but the data is not stored. when i deleted with encryption, the data is perfectly preserved.

I did not find any bug in this matter.

Is there something that i don't understand?

**Comment by ammarahm-ed** [comment]
send the code here of how you are initialising MMKV instance. It's working normally for me.

**Comment by ylahssini** [comment]
after i logged, i save the user data in instance like that:
```
const UserMMKV = new MMKVStorage.Loader().withInstanceID('user').withEncryption().initialize();

await UserMMKV.setMapAsync('data', {
   ...responseUserInfos.data,
   token: responseLogin.data.token,
});
```
and after i force to close the app, i execute a function to check if data is stored or not to do redirections (this code is in another file):
```
const UserMMKV = new MMKVStorage.Loader().withInstanceID('user').withEncryption().initialize();

await UserMMKV.encryption.decrypt();


try {
    const userStorage = await UserMMKV.getMapAsync('data');
   navigation.navigate('Home');
} catch (e) {
   navigation.navigate('Login');
}
```

I hope this example is sufficent to do test. By the way, i use version 0.3.7

**Comment by ammarahm-ed** [comment]
You don't need to call `decrypt`. It's only for the case where you want to convert an encrypted MMKV instance to an unencrypted one. 

You should do this simply:

```js
const UserMMKV = new MMKVStorage.Loader().withInstanceID('user').withEncryption().initialize();

try {
    const userStorage = await UserMMKV.getMapAsync('data');
   navigation.navigate('Home');
} catch (e) {
   navigation.navigate('Login');
}
```

**Comment by ylahssini** [comment]
Yes, you're right, it's working now.
Thank you for your support and also making this amazing plugin.
