### ISSUE TITLE
How to keep the data in the keychian after reinstall app?

### ISSUE THREAD

**Issue by dcuti8** [ammarahm-ed/react-native-mmkv-storage#46]
When I uninstall the app, the data is disapear in ios.
I want to keep the data after uninstall the app.

🙏🙏🙏

**Comment by dcuti8** [comment]
this is my setting
const MMKV = new MMKVStorage.Loader()
	.setProcessingMode(MMKVStorage.MODES.SINGLE_PROCESS)
	.withEncryption()
	.initialize();

**Comment by alessioemireni** [comment]
@ammarahm-ed we are migrating from another Database and when the ecnryption is enabled we encountered this issue (snippet code is the same above). Why is the keychain deleted during startup if encryption is enabled?

```
- (void)clearSecureKeyStore
{
    NSArray *secItemClasses = @[(__bridge id)kSecClassGenericPassword,
                                (__bridge id)kSecAttrGeneric,
                                (__bridge id)kSecAttrAccount,
                                (__bridge id)kSecClassKey,
                                (__bridge id)kSecAttrService];
    for (id secItemClass in secItemClasses) {
        NSDictionary *spec = @{(__bridge id)kSecClass: secItemClass};
        SecItemDelete((__bridge CFDictionaryRef)spec);
    }
}

- (void)handleAppUninstallation
{
    if (![[NSUserDefaults standardUserDefaults] boolForKey:@"RnSksIsAppInstalled"]) {
        [self clearSecureKeyStore];
        [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"RnSksIsAppInstalled"];
        [[NSUserDefaults standardUserDefaults] synchronize];
    }
}
```

**Comment by tamagokun** [comment]
Experiencing the same thing here, and it's a bit unexpected and was frustrating it took so long to figure out what was happening.

Old version of an app was using `react-native-sensitive-info` which uses keychain, and when switching to use this library, I was noticing that all of the data stored using the other library was gone. It took awhile to realize this was happening because I was enabling encryption in this library.

Is there a way to use encryption and not have it clear everything?

**Comment by ammarahm-ed** [comment]
@tamagokun You are facing the problem because this library does not use SharedPrefrences, instead it uses MMKV for storing data, so if you are migrating from another database, you need to first take out all of data from old database and put it in MMKV before removing the old library you were using.

**Comment by tamagokun** [comment]
Right, that part I understand. So, I have both libraries installed, and fetch the data from rn-sensitive-info, and store it into MMKV. It works GREAT as long as I don't enable encryption. As soon as I include `withEncryption()` all of the data that was in the rn-sensitive-info database is missing.

Seems like that above native code `clearSecureKeyStore` is the reason.

**Comment by ammarahm-ed** [comment]
@tamagokun can you test using this branch, I have removed the keychain clearing code I think. Test and let me know.

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage#fix-keychain-ios
```
