### ISSUE TITLE
Assertion failed: (0), function +[MMKV mmkvWithID:cryptKey:rootPath:mode:]

### ISSUE THREAD

**Issue by zeeshanwarriach93** [ammarahm-ed/react-native-mmkv-storage#47]
App Crashing on IOS, It is stuck on Splash screen,
I get following error also screenshot is attached.
Assertion failed: (0), function +[MMKV mmkvWithID:cryptKey:rootPath:mode:], file /Users/zeeshanwarriach/Documents/ChatApp/ios/Pods/MMKV/iOS/MMKV/MMKV/libMMKV.mm, line 174

![Screen Shot 2020-11-09 at 1 45 57 PM](https://user-images.githubusercontent.com/74134024/98518955-edca6a00-2291-11eb-960e-8c75c5a5d4ef.png)

**Comment by zeeshanwarriach93** [comment]
Is there any body who can help me with this?

**Comment by mateosilguero** [comment]
Seems multiprocess mode doesnt work on ios

**Comment by zeeshanwarriach93** [comment]
Yes its not working on IOS, I disabled it and it worked.
