### ISSUE TITLE
FR: Potential for secured storage?

### ISSUE THREAD

**Issue by kyle-ssg** [ammarahm-ed/react-native-mmkv-storage#5]
I'd love to start trying this out, however one requirement we have on almost all of our projects requiring PEN testing is for all data to be encrypted either through standard keystore, and potentially an access control like pin/biometrics.

This leads us to using an approach quite similar to https://www.npmjs.com/package/react-native-secure-storage.

Is encrypted storage something that would / could be on the roadmap?

**Comment by ammarahm-ed** [comment]
Encryption is one or two releases away but in the works. MMKV supports encryption built in (I think AES-256) so it could be implemented easily. You can check #1  issue to see what has been implemented and what is coming in the future releases.

**Comment by kyle-ssg** [comment]
Awesome! In that case I guess I'l close this and watch the roadmap
