### ISSUE TITLE
Can not co-existence with react-native-keychain

### ISSUE THREAD

**Issue by palmithor** [ammarahm-ed/react-native-mmkv-storage#52]
Tested on react-native version 0.63.2

I already use react-native-keychain in our project and we've been really happy with that. 

But now I am looking in to the possibility of backing my Apollo (graphql) cache with react-native-mmkv-storage but I get a compilation error on iOS:

```
duplicate symbol '_accessibleValue' in 
> libRNKeychain.a(RNKeychainManager.o)
> libreact-native-mmkv-storage.a(SecureStorage.o)
```

Something that has come up before or do you have any solution to it?

**Comment by ammarahm-ed** [comment]
fixed it in v0.4.3
