### ISSUE TITLE
Android RAM <= 2.0 GB Throws Error

### ISSUE THREAD

**Issue by wegory** [ammarahm-ed/react-native-mmkv-storage#55]
Thanks for the library. Had issues with users in production that have RAM <= 2.0GB.

After getting hold of an Android phone with 2.0GB RAM, I debugged the issue.

I learnt that the methods from the mmkv library produce the following error:
"Wrong password or storage corrupt"

Is there a requirement that I missed? Can this library accommodate users with RAM <= 2.0GB?

Cheers!

**Comment by ammarahm-ed** [comment]
@wegory What version of the library are you using in production? And how often does it occur? provide more detail. what is the android version etc.

**Comment by wegory** [comment]
I'm using lib 0.3.7.

From the reviews on Play Store, I can say that at least 5 users had the issue. Some of them had Android 10. They had RAM <= 2.0GB.

The device that I tested was Android 7.

**Comment by ammarahm-ed** [comment]
The current latest version of the lib is 0.4.2. You should test using the latest version and see if the error is there.

**Comment by wegory** [comment]
Will do. Thanks. Are there any breaking changes? Couldn't find the changelog.

**Comment by awinograd** [comment]
@wegory you can find the release notes here: https://github.com/ammarahm-ed/react-native-mmkv-storage/releases

Curious what you find! I'm just starting to investigate mmkv for my app as well
