### ISSUE TITLE
[bug] indexer crashes on ios

### ISSUE THREAD

**Issue by sayem314** [ammarahm-ed/react-native-mmkv-storage#57]
On ios when running `await storage.indexer.maps.getAll()` it crashes if there is nothing saved before instead of returning `[]` while android is working as expected.

Even with try/catch, it's crashing anyway.

**Comment by ammarahm-ed** [comment]
I will fix it

**Comment by ammarahm-ed** [comment]
It is fixed on master, can you test again with the master branch

**Comment by alberto115** [comment]
Hi @ammarahm-ed,

I just found myself having the same issue described above. It seems to be fixed using the master branch.

Cheers
