### ISSUE TITLE
[0.5.0] Missing StorageSetters.m

### ISSUE THREAD

**Issue by iwater** [ammarahm-ed/react-native-mmkv-storage#61]
error: Build input file cannot be found: '/node_modules/react-native-mmkv-storage/ios/StorageSetters.m' (in target 'react-native-mmkv-storage' from project 'Pods')

this file reference in ios/MMKVStorage.xcodeproj/project.pbxproj but not in source code

react-native-mmkv-storage@0.5.1
react-native@0.63.4

**Comment by ammarahm-ed** [comment]
I will fix this

**Comment by ammarahm-ed** [comment]
Did you run pod install after updating? These files have been removed.

**Comment by iwater** [comment]
yes, pod install  after updated

**Comment by ammarahm-ed** [comment]
@iwater can you try adding master branch. I have fixed the issue:

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage#master
```
if its fixed, let me know so I can push a new version with fix.

**Comment by iwater** [comment]
that problem was gone, but it seems the data saved by the old version can not be read by the new version 0.5+ after upgraded

**Comment by ammarahm-ed** [comment]
On Android or iOS? @iwater and are you using encryption?

**Comment by iwater** [comment]
on iOS with encryption, not test android

**Comment by ammarahm-ed** [comment]
> on iOS with encryption, not test android

@iwater Can you test again with master. I have fixed the issue

**Comment by iwater** [comment]
not fix the new problem with commit 50791c9c88e44d138d111d1da36fe0158f28d398

**Comment by ammarahm-ed** [comment]
@iwater try  updating to 0.5.2 and test

**Comment by iwater** [comment]
not fix the new problem with 0.5.2

**Comment by ammarahm-ed** [comment]
ahh ok.. I think I know why this is happening. I will fix it

**Comment by ammarahm-ed** [comment]
@iwater I have fixed it. can you test master branch and see if it works

**Comment by iwater** [comment]
upgrade from 0.4.4 to master branch, the data can be read now
if downgrade to the old version app, the saved data was gone

**Comment by ammarahm-ed** [comment]
You cannot downgrade.

**Comment by ammarahm-ed** [comment]
Adding to that, however, strings & booleans should be readable as before. But arrays and objects will not be, if you downgrade. 

They are stored as Json strings in the new version so you can simply fetch and call `JSON.parse` on them to get your data in 0.4.0 and it should work.
