### ISSUE TITLE
[0.5.2][Android] Could not determine the dependencies of task ':react-native-mmkv-storage:mergeDebugNativeLibs'.

### ISSUE THREAD

**Issue by ravi-poonia** [ammarahm-ed/react-native-mmkv-storage#62]
On app run in debug mode getting the following error:

Could not determine the dependencies of task ':react-native-mmkv-storage:mergeDebugNativeLibs'.
> CMake '3.10.2' was not found in PATH or by cmake.dir property.

RN:0.63.4
OS: windows

**Comment by ammarahm-ed** [comment]
Can you check what cmake version you have in android studio? @ravi-poonia

**Comment by haroldwaste** [comment]
Same hrere, using cmake v 3.18.0 which I think is the latest version, probably need to downgrade it.

**Comment by ammarahm-ed** [comment]
Can you @haroldwaste try to go to `/node_modules/react-native-mmkv-storage/android/build.gradle` and remove the `version:'3.10.2'` from cmake and see if it builds for you?

**Comment by alessandro-bottamedi** [comment]
Same here, i can confirm that changing the version of `cmake` in `/node_modules/react-native-mmkv-storage/android/build.gradle` to `version:'3.17.3'` (the version I currently have installed) works without any problems.

**Comment by ammarahm-ed** [comment]
@alessandro-bottamedi does it work if you completely remove it?

.. 
I put a fixed version because I had 2 versions of cmake installed and it was defaulting to the old 3.6 version for me. Try removing version completely and build again

**Comment by alessandro-bottamedi** [comment]
@ammarahm-ed Without the version line:

```
  externalNativeBuild {
      cmake {
          path "./src/main/rnmmkv/CMakeLists.txt"
      }
  } 
```
I get this error, I don't know where it gets that old version of cmake (i'm running 3.17.3):
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.9.0 or higher is required.  You are running version 3.6.0-rc2
```

**Comment by ammarahm-ed** [comment]
Try defining the cmake version in app/build.gradle file

While keeping it removed from the library and see if that works.


Actually android studio keeps 2 versions of cmake. One is 3.6 and other is 3.10.2 or higher by default. It says it defaults to 3.10.2 but it seems that's not the case here.

You can open Android Studio > SDK Manager > and see what cmake versions you have installed and maybe disable the old version. But first try the initial solution.

```
externalNativeBuild  {
cmake {
 version:"your cmake version" 
} 
} 
```
@alessandro-bottamedi

**Comment by alessandro-bottamedi** [comment]
> Try defining the cmake version in app/build.gradle file
> 
> While keeping it removed from the library and see if that works.
> 
> Actually android studio keeps 2 versions of cmake. One is 3.6 and other is 3.10.2 or higher by default. It says it defaults to 3.10.2 but it seems that's not the case here.
> 
> You can open Android Studio > SDK Manager > and see what cmake versions you have installed and maybe disable the old version. But first try the initial solution.
> 
> ```
> externalNativeBuild  {
> cmake {
>  version:"your cmake version" 
> } 
> } 
> ```
> 
> @alessandro-bottamedi

Same error with both solution...

I've added this to my `app/build.gradle`:

```
    externalNativeBuild  {
      cmake {
        version "3.17.3"
      } 
    } 
```

I then checked the SDK manager and the old version 3.6 was installed. I updated to 3.10 from the SDK manager but still got the same error:

```
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.9.0 or higher is required.  You are running version 3.6.0-rc2
```

PS. i'm on MacOs 10.15.7

**Comment by ammarahm-ed** [comment]
What is your version of Android Studio?

**Comment by alessandro-bottamedi** [comment]
@ammarahm-ed Android Studio 4.0.1

**Comment by ammarahm-ed** [comment]
Maybe for now simply install cmake `3.10.2` in Android Studio SDK Manager and the problem will go away. I will look into a proper solution tomorrow.

**Comment by haroldwaste** [comment]
@ammarahm-ed on my side, I can confirm that without version:'3.10.2 in build gradle', the build works for both v 3.18.1 and v3.10.2

![image](https://user-images.githubusercontent.com/41142426/110365452-5a3d5600-8045-11eb-8d05-3798016587ca.png)

**Comment by ammarahm-ed** [comment]
@haroldwaste what's the version of Android Studio and NDK you are using. How many cmake versions do you have installed

**Comment by ammarahm-ed** [comment]
Do you have cmake 3.6 installed too or no?

**Comment by haroldwaste** [comment]
NDK version: 22.0.7026061
android studio version: 4.1.2

**Comment by haroldwaste** [comment]
nope, 3.6 is not installed, I have both 3.10 and 3.18

**Comment by ammarahm-ed** [comment]
Seems like updating and removing cmake 3.6 will solve this problem

**Comment by ammarahm-ed** [comment]
Fixed on master.
