### ISSUE TITLE
[0.5.2][IOS] Use of undeclared identifier 'kindOf'

### ISSUE THREAD

**Issue by nghiatv** [ammarahm-ed/react-native-mmkv-storage#63]
When i run app in release mode on real device getting the following error:

> /Users/nghia/Desktop/workingSpace/RNClientApp/ios/Pods/Headers/Public/React-jsi/jsi/jsi.h:933:43: Use of undeclared identifier 'kindOf'
> /Users/nghia/Desktop/workingSpace/RNClientApp/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm:2:9: In file included from /Users/nghia/Desktop/workingSpace/RNClientApp/node_modules/react-native-mmkv-storage/ios/MMKVNative.mm:2:

RN:0.63.4
OS: MacOS

**Comment by ammarahm-ed** [comment]
Try setting the minimum deployment version to 11.0 instead of 10 in podfile and project

**Comment by nghiatv** [comment]
Can i use it with version 10? @ammarahm-ed

**Comment by ammarahm-ed** [comment]
I don't think so. It won't work in release mode. The library uses very new technologies from react native that are still in development and hence can not support older platforms. If you still want to support older versions, you can use 0.4 version of this library.  

@nghiatv i will look into why the variables are missing.

**Comment by ammarahm-ed** [comment]
@nghiatv Can you test using the master branch? I have fixed it and for me it is building now on version 10

**Comment by nghiatv** [comment]
It seems working for me now but i got some warnings  while pod install. Thanks a lot @ammarahm-ed

**Comment by ammarahm-ed** [comment]
@nghiatv ignore the warnings. Everything seems to work normally. let me know if you come across any issues again
