### ISSUE TITLE
[0.5.2][Expo + Android] global.getStringMMKV is not a function

### ISSUE THREAD

**Issue by arkabase** [ammarahm-ed/react-native-mmkv-storage#64]
react-native 0.63.2
react-native-mmkv-storage 0.5.2
---
My code :

`const Storage = new MMKVStorage.Loader().initialize()`

The error :

`TypeError: global.getStringMMKV is not a function. (In 'global.getStringMMKV(id, STORE_ID)', 'global.getStringMMKV' is undefined)`

in src/mmkv/IDStore.js line 53 :

`let storeUnit = global.getStringMMKV(id, STORE_ID);`

Seems like `global` object is not initialized !
Is there a dependency i'm not aware of ?

Thanks for your help

**Comment by ammarahm-ed** [comment]
Are you using it in debug mode?@arkabase. Did you get the same error with debug mode off?

**Comment by halykon** [comment]
I'm getting the same error, disabling debug mode still produces the error.

Using expo SDK 40 and iOS.
Here's the complete stack trace:
```
TypeError: global.getStringMMKV is not a function. (In 'global.getStringMMKV(id, STORE_ID)', 'global.getStringMMKV' is undefined)

Stack trace:
  node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
  node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
  node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
  node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
  node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
  node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
  node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
  node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
  node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  node_modules/regenerator-runtime/runtime.js:293:29 in invoke
  node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
  node_modules/regenerator-runtime/runtime.js:154:27 in invoke
  node_modules/regenerator-runtime/runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
  node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
  node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
  [native code]:null in flushedQueue
  [native code]:null in invokeCallbackAndReturnFlushedQueue
  ...
  ```

**Comment by 0xc22b** [comment]
I think it's because of calling initialize() too early, JSI hasn't completed its task yet i.e. calling it right after the import.

I fix it by initialize it the first time of use.
```javascript
import MMKVStorage from "react-native-mmkv-storage";

let _instance = null;

const getInstance = () => {
  if (!_instance) _instance = new MMKVStorage.Loader().initialize();
  return _instance;
};
```

**Comment by hitsthings** [comment]
Haven't tried the workaround yet, but a heads up that I'm also seeing this in the iOS simulator (so presumably nothing to do with Expo or Android).

**Comment by focux** [comment]
For the record, I'm getting also that error on RN 0.63.3 using the iOS simulator. I also tried the workaround posted above but it didn't work either.

Do someone found another solution?

**Comment by ammarahm-ed** [comment]
> For the record, I'm getting also that error on RN 0.63.3 using the iOS simulator. I also tried the workaround posted above but it didn't work either.
> 
> Do someone found another solution?

Hey, does it happen every time or sometimes? Also make sure that you are not debugging in Chrome etc because JSI doesn't work when debugger is connected.

On iOS when reloading the bundle by shaking device or pressing "R" in terminal, occasionally the bridge is not initialized  with JSI and so the memory reference to JSI is lost. I think this problem does not happen in release mode because bundle is loaded only once in the app life cycle.

**Comment by ammarahm-ed** [comment]
update to 0.5.4 to resolve these issues. Follow the updated steps in installation

**Comment by ammarahm-ed** [comment]
@focux I have fixed the problem for iOS specifically. Can you test using the master branch. I have tested on RN 0.64 with and without hermes enabled.

**Comment by focux** [comment]
@ammarahm-ed I already tested and it worked like charm, changing the deployment target did it, thank you so much. The only issue that I see is that when you change the deployment target version of the Pod, that change isn't present on Git—there's no change detected—I assume that's because you are changing the package which is ignored and not committed to Github, so that causes a problem if others pull the project and try to install it without making changes those changes. It's not a big deal but just letting you know in case there's something you can do on the library side to fix that in the package.

**Comment by ammarahm-ed** [comment]
The minimum ios version of the library is set to 11.0 on the latest lib version. The changes you make to your podfile  commit to github. So you don't need to edit the library .podspec anymore

**Comment by ammarahm-ed** [comment]
I am closing this issue since the problem is resolved. Reopen if you face issue again after updating to `0.5.5` version once I publish it.
