### ISSUE TITLE
initialize method does not return a promise

### ISSUE THREAD

**Issue by laffed** [ammarahm-ed/react-native-mmkv-storage#65]
In the docs loaderclass.md, it suggests that the initialize method returns a promise that resolves with the API instance. 
But this is not reflected in the index.d.ts file. The typescript file suggests that this method is synchronous so either the ts module is incorrect or the docs are incorrect. 

I've made a PR correcting the docs.

**Comment by ammarahm-ed** [comment]
Thanks! I have merged it. You are right. It does not return promise
