### ISSUE TITLE
Crash in release build due to java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad

### ISSUE THREAD

**Issue by realprabs** [ammarahm-ed/react-native-mmkv-storage#68]
RN Version: 0.64-rc4

Works fine in debug mode. However, when I run a release build, it crashes with error:

```
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad
```

Goes away if I remove mmkv storage.

**Comment by ammarahm-ed** [comment]
@jaysson I will check. I haven't tested the lib with unreleased version of react-native.

**Comment by ammarahm-ed** [comment]
Cannot reproduce on a new project using rn 0.64-rc4 in release build with hermes disabled

**Comment by realprabs** [comment]
We have hermes enabled. Is this library not compatible with it?

**Comment by Johan-dutoit** [comment]
FWIW I'm facing a crash too, but using the latest stable RN, with hermes enabled.

Not the same error, but also only on release build and not debug build.

**Comment by Johan-dutoit** [comment]
I simply have this and then interact with instance as usual (i.e. `this.instance.getArrayAsync...`)
```
    this.instance = new MMKVStorage.Loader()
      .withInstanceID('instanceId')
      .withEncryption()
      .initialize();
```

What's really interesting is, is that the app would only crash after a force close.  After about 6 tries the app runs perfectly fine (weird).

To ensure it's mmkv, I removed it completely and no more crashes.

Using 0.5.3

**Comment by chr4ss1** [comment]
Same issue on Android.


Using react-native 0.63.4 as well 0.5.3

```
FATAL EXCEPTION: create_react_context
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/myapp-jvxMvu33QWs5ssAq9-jq7A==/split_config.arm64_v8a.apk!/lib/arm64-v8a/librnmmkv.so": -5
	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at com.ammarahmed.mmkv.RNMMKVModule.<clinit>(RNMMKVModule.java:1)
	at com.ammarahmed.mmkv.a.createNativeModules(RNMMKVPackage.java:1)
	at com.facebook.react.v.a(ReactPackageHelper.java:7)
	at com.facebook.react.e.b(NativeModuleRegistryBuilder.java:8)
	at com.facebook.react.q.Q(ReactInstanceManager.java:6)
	at com.facebook.react.q.R(ReactInstanceManager.java:8)
	at com.facebook.react.q.q(ReactInstanceManager.java:6)
	at com.facebook.react.q.c(ReactInstanceManager.java:1)
	at com.facebook.react.q$e.run(ReactInstanceManager.java:12)
	at java.lang.Thread.run(Thread.java:919)

```

Looks like error is -5, but am not sure where to locate it exactly.

**Comment by chr4ss1** [comment]
I believe it started working after throwing this into  my proguard rules file:


```
# Keep all native methods, their classes and any classes in their descriptors
-keepclasseswithmembers,includedescriptorclasses class com.tencent.mmkv.** {
    native <methods>;
    long nativeHandle;
    private static *** onMMKVCRCCheckFail(***);
    private static *** onMMKVFileLengthError(***);
    private static *** mmkvLogImp(...);
    private static *** onContentChangedByOuterProcess(***);
}
```

**Comment by ammarahm-ed** [comment]
@ChrisEelmaa Hey, thanks for posting the solution. I will see if this fixes the issue since i am also getting crash in release build

**Comment by ammarahm-ed** [comment]
update to 0.5.4 to resolve these issues. Follow the updated steps in installation
