### ISSUE TITLE
React Native crashes at runtime with JSI error

### ISSUE THREAD

**Issue by arkabase** [ammarahm-ed/react-native-mmkv-storage#69]
react-native@0.63.4
react-native-mmkv-storage@0.5.3

My code :
```
import MMKVStorage from 'react-native-mmkv-storage'

const Storage = new MMKVStorage.Loader().withInstanceID('myapp').initialize()

const getStoredHost = async _ => {
    if (Storage.hasKey('host')) {
        return await Storage.getStringAsync('host')
    }
    return null
}

let host = getStoredHost()
```
the app crashes at runtime in Android Studio and ADV Emulator

`A/libc: [PATH_TO_APP]/node_modules/react-native-mmkv-storage/android/src/main/rnmmkv/../../../../../react-native/ReactCommon/jsi\jsi/jsi.h:1073: facebook::jsi::String facebook::jsi::Value::getString(facebook::jsi::Runtime &) const &: assertion "isString()" failed`

**Comment by ammarahm-ed** [comment]
I will check.

**Comment by ammarahm-ed** [comment]
```
import MMKVStorage from 'react-native-mmkv-storage'

const Storage = new MMKVStorage.Loader().withInstanceID('myapp').initialize()

const getStoredHost = async () => {
    if (await Storage.indexer.hasKey('host')) {
        return await Storage.getStringAsync('host')
    }
    return null
}

let host = await getStoredHost()
```
Did you read the docs before implementing this, try this code above.

**Comment by ammarahm-ed** [comment]
cannot reproduce this error in Emulator. Please share more details. ndk version, android studio version, android sdk version in android/build.gradle file

**Comment by chr4ss1** [comment]
Same error on iPhone 8, latest iOS

I used to have "react-native-mmkv-storage": "0.3.7" and it worked fine, but now that I updated to "react-native-mmkv-storage": "0.5.3" AS well upgraded react native from 0.62 to 0.63.4, it started crashing.


Code that crashed:


```
    auto clearMMKV = jsi::Function::createFromHostFunction(jsiRuntime,
                                                           jsi::PropNameID::forAscii(
                                                                                     jsiRuntime,
                                                                                     "clearMMKV"),
                                                           1,
                                                           [](jsi::Runtime &runtime,
                                                              const jsi::Value &thisValue,
                                                              const jsi::Value *arguments,
                                                              
                                                              size_t count) -> jsi::Value {
        MMKV *kv = getInstance(convertJSIStringToNSString(runtime, arguments[1].getString(
                                                                                          runtime)));
        if (!kv)
        {
            return Value::undefined();
        }
        
        [kv clearAll];
        
        return Value::null();
    });
 ```
 
 the getString seems to be crashing:
 
 Assertion failed: (isString()), function getString, file /Users/.../src/../../ios/Pods/Headers/Public/React-jsi/jsi/jsi.h, line 1073.
 
 
 How I use it:
 
 ```
        this._genericStorage = new MMKVStorage.Loader()
            .withInstanceID("genericStorage")
            .initialize();
 .......
...... 
            
 await this._genericStorage.clearStore()
 ```
 
I've copied the content of "arguments" as well at the time of exception:

https://imgur.com/FzhpYey

It looks whatever is being passed to isString(), I can see that kind_ is equal to "UndefinedKind"

https://imgur.com/a/D0SBNdB

Am not sure arguments[1] looks right, shouldn't it be [0]? as there is only one argument to be passed?

**Comment by ammarahm-ed** [comment]
@ChrisEelmaa It should be arguments[0]

**Comment by davx1992** [comment]
Hello, having the same issue. When clearStorage called app crashes. 
@ChrisEelmaa how you solved the problem?

**Comment by chr4ss1** [comment]
You can use the latest stable version @0.4.3 that works well

**Comment by rokibulcommit** [comment]
Doesn't seem to be working when started in debug mode, is it anyhow related to this issue?

**Comment by focux** [comment]
I'm also having exactly the same issue as @ChrisEelmaa, the app is crashing each time I try to execute `clearStore`. 

Error:
```
Assertion failed: (isString()), function getString, file /ios/Pods/Headers/Public/React-jsi/jsi/jsi.h, line 1073.
Assertion failed: (isString()), function getString, file /ios/Pods/Headers/Public/React-jsi/jsi/jsi.h, line 1073.
CoreSimulator 732.18.6 - Device: iPhone 11 (3D80BB6F-1551-4B95-A7DA-8D7755E447BD) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 11
```
