### ISSUE TITLE
[Build Android] Task :app:mergeDebugNativeLibs FAILED

### ISSUE THREAD

**Issue by ftzi** [ammarahm-ed/react-native-mmkv-storage#70]
Same code, updated this package, ran `npx react-native-clean-project`, cleaned node_modules, uninstalled app. Error when running `npm run android`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86/libc++_shared.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

rn version: 0.63.4
package version: 0.5.3

**Comment by ammarahm-ed** [comment]
@SrBrahma check installation steps in docs

**Comment by ftzi** [comment]
Thanks for the quick answer (and as always, also for the lib!)!!

I think there should be a tip about that in README, for other previous version users.
