### ISSUE TITLE
[BUILD FAILED] Release Build Failed

### ISSUE THREAD

**Issue by TadsDad** [ammarahm-ed/react-native-mmkv-storage#72]
react-native version : 0.63.4
react-native-mmkv-storage version : 0.5.3

ios release buld Failed -> "Use of undeclared identifier 'kindOf' "

**Comment by henrykuzmick** [comment]
Same issue

**Comment by henrykuzmick** [comment]
ah, ok, solution here https://github.com/mrousavy/react-native-mmkv/issues/10

**Comment by TadsDad** [comment]
@henrykuzmick thank you!  After I changed to 11, there was no problem.
