### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by alexzobi** [ammarahm-ed/react-native-mmkv-storage#74]
I don't know what I'm doing wrong, but I can't seem to get calls to my instance to work. pods show up. Instance of the API logs when I log it, but i noticed it doesn't have any of the Async funcs. figured it didn't matter and I'd just try the regular methods. except they crash too. Your docs make setup seem super basic, so i figure i must be missing something.

```
import MMKVStorage from 'react-native-mmkv-storage';

const init = async () => {
  const MMKV = new MMKVStorage.Loader().initialize();
  console.log('MMKV: ', MMKV);

  await MMKV.setString('tag', 'test', (e) => {
     // never gets here. crashes on call.
     console.log('set e: ', e)
  });

  const string = await MMKV.getString('tag', (e) => console.log('get e: ', e));

  console.log('map: ', map);
};

init();
```

react-native-mmkv-storage: "^0.5.3",
ios: 14
react native: 0.63.4

**Comment by AndrewIsBest69** [comment]
Same problem, please help

**Comment by chr4ss1** [comment]
try this:

```


const init = async () => {

  try {
    const MMKV = new MMKVStorage.Loader().initialize();
    
    console.log(MMKV)
    console.log("global=", global.setStringMMKV)

    await MMKV.setStringAsync('tag', 'test');
    const string = await MMKV.getStringAsync('tag');

  } catch (e) {
    console.log(e)
  }
};

init();

```

does it still crash? 
can you output everything from your console.log?
check that you call these methods AFTER your <App> component has loaded

you register your component with

```
AppRegistry.registerComponent(appName, () => App);
```

and you run the code in the App constructor:


```
export default class App extends React.Component {
constructor() {
  ...all MMKV stuff...
}
```

either way, you should be using 0.3.7 for time being, as 0.5.3 with JSI implementation has bugs (see https://github.com/facebook/react-native/issues/31197)

**Comment by ammarahm-ed** [comment]
update to 0.5.5 to resolve these issues. Follow the updated steps in installation.
