### ISSUE TITLE
Crash in Debug Mode, IOS Simulator

### ISSUE THREAD

**Issue by rodrigoklimberg** [ammarahm-ed/react-native-mmkv-storage#76]
Hi
I have the TypeError: global.getStringMMKV is not a function when i want to dubug my App. 
Are they some special configuration for make Debug?

 **MY CONFIG:**
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-native": "^0.63.4",
"react-native-mmkv-storage": "^0.5.3",

**Comment by ammarahm-ed** [comment]
Debug mode is not available after 0.5.3 due to use of JSI. use Flipper etc for debugging.
