### ISSUE TITLE
Read (getMap) so slow first reading. 2nd+ with the same result are faster (insta)

### ISSUE THREAD

**Issue by gonzalorivasconcepcion** [ammarahm-ed/react-native-mmkv-storage#80]
Version: 0.4.3
Description: When I update the storage with new data (json elements of an array are being inserted in the storage, one by one), the consecuent read of them are so slow and increases exponencially, but only the first read (just after the insert).

I mean:

First insert. 1s
Read: 3s
2nd Read: 1s

2nd insert. 1s
Read: 4s
2nd Read: 1s

3rd insert. 1s
Read: 5.5s
3rd Read: 1s

4th insert. 1s
Read: 8s
4th Read: 1s

Is a reported problem solved in 0.5+?

How could i get ride of this insane bug?

Is not much data, about 200 characters per element in each insert. I tested with getMapAsync and getMap with no good result.

Thank u in advance :)

**Comment by ammarahm-ed** [comment]
That's a limitation of bridge since calls are queued. Updating to 0.5.4 will resolve this.
