### ISSUE TITLE
Error ocour when bundleRelease

### ISSUE THREAD

**Issue by thanhdatpd** [ammarahm-ed/react-native-mmkv-storage#83]
Everything working fine in dev mode (react-native run-android)
When I bundle release by ./gradlew bundleRelease, it will failed with error below. 
I tried run in administrator mode(both bash and cmd), ./gradlew clean, deleted node_modules, use other Cmake version
So what can i do to fix this error?

operating system: windows
react-native: 0.63.4
react-native-mmkv-storage: 0.5.3,
Cmake: 3.10.2.4988404
Ndk: 22.1

```bash
> Task :app:bundleReleaseJsAndAssets
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'C:\project\myapp\node_modules\react-native-mmkv-storage\android\.cxx\cmake\SharedCppRelease\arm64-v8a\Core\libcore.a.temp-archive-bbab348.a'
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.<anonymous> (C:\project\myapp\node_modules\sane\src\node_watcher.js:291:16)
    at callback (C:\project\myapp\node_modules\graceful-fs\polyfills.js:299:20)
    at FSReqCallback.oncomplete (fs.js:183:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\project\\myapp\\node_modules\\react-native-mmkv-storage\\android\\.cxx\\cmake\\SharedCppRelease\\arm64-v8a\\Core\\libcore.a.temp-archive-bbab348.a'
}

> Task :app:bundleReleaseJsAndAssets FAILED
```

**Comment by ammarahm-ed** [comment]
try this https://github.com/oblador/react-native-vector-icons/issues/354

**Comment by thanhdatpd** [comment]
> try this [oblador/react-native-vector-icons#354](https://github.com/oblador/react-native-vector-icons/issues/354)

I tried all but not help at all

Today i disable gradle parallel in ./android/gradle.properties and it working although it so slow:
org.gradle.parallel=false

**Comment by rjuevesano** [comment]
Got this issue. Can anyone help me?

```
externalNativeBuild {
      cmake {
          path "./src/main/rnmmkv/CMakeLists.txt"
          version "3.10.2"
      }
  }

"react-native-mmkv-storage": "0.5.9"
```

Am I missing something?

![image](https://user-images.githubusercontent.com/4033035/123230121-7e944400-d509-11eb-8169-5fb24e6f5b81.png)

**Comment by ammarahm-ed** [comment]
> Got this issue. Can anyone help me?
> 
> ```
> externalNativeBuild {
>       cmake {
>           path "./src/main/rnmmkv/CMakeLists.txt"
>           version "3.10.2"
>       }
>   }
> 
> "react-native-mmkv-storage": "0.5.9"
> ```
> 
> Am I missing something?
> 
> ![image](https://user-images.githubusercontent.com/4033035/123230121-7e944400-d509-11eb-8169-5fb24e6f5b81.png)
> 

Install Cmake 3.10.2 from Android Studio SDK Manager.

**Comment by rjuevesano** [comment]
> > Got this issue. Can anyone help me?
> > ```
> > externalNativeBuild {
> >       cmake {
> >           path "./src/main/rnmmkv/CMakeLists.txt"
> >           version "3.10.2"
> >       }
> >   }
> > 
> > "react-native-mmkv-storage": "0.5.9"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I missing something?
> > ![image](https://user-images.githubusercontent.com/4033035/123230121-7e944400-d509-11eb-8169-5fb24e6f5b81.png)
> 
> Install Cmake 3.10.2 from Android Studio SDK Manager.

I did 
![image](https://user-images.githubusercontent.com/4033035/123231615-f31bb280-d50a-11eb-8ad9-c10e293150d1.png)

**Comment by ammarahm-ed** [comment]
> > > Got this issue. Can anyone help me?
> > > ```
> > > externalNativeBuild {
> > >       cmake {
> > >           path "./src/main/rnmmkv/CMakeLists.txt"
> > >           version "3.10.2"
> > >       }
> > >   }
> > > 
> > > "react-native-mmkv-storage": "0.5.9"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Am I missing something?
> > > ![image](https://user-images.githubusercontent.com/4033035/123230121-7e944400-d509-11eb-8169-5fb24e6f5b81.png)
> > 
> > Install Cmake 3.10.2 from Android Studio SDK Manager.
> 
> I did 
> ![image](https://user-images.githubusercontent.com/4033035/123231615-f31bb280-d50a-11eb-8ad9-c10e293150d1.png)
> 

Then it should build normally I think. Try reinstalling cmake. Also check your ndk version. It should be 21.xx or 20.xx. Clean project etc.

**Comment by rjuevesano** [comment]
Yup. I'm using 21.4.xxx. Will try to clean the project and let you know if it works. Thanks :)

![image](https://user-images.githubusercontent.com/4033035/123233661-cff20280-d50c-11eb-9148-5aa3ba29b69e.png)

**Comment by rjuevesano** [comment]
@ammarahm-ed the problem was in my `circleci.yml`

Was able to fixed it by adding these
```yaml
- run: sdkmanager "ndk;21.4.7075529"
- run: sdkmanager "cmake;3.10.2.4988404"
```
