### ISSUE TITLE
ClearStore disabled the store forever after reloading the app with metro

### ISSUE THREAD

**Issue by msimon** [ammarahm-ed/react-native-mmkv-storage#95]
react-native: 0.64.0
react-native-mmkv-storage: 0.5.7

### Bug:
On IOS dev mode, the clearStore method is disabling the store forever on subsequent app reload.

### Expected behaviour
Reloading the app after a clearStore should allow storage.

### Example

```
import MMKVStorage from 'react-native-mmkv-storage'
 export const localStorage = new MMKVStorage.Loader().withInstanceID("instance2").withEncryption().initialize()
 
const App = () => {
   const isDarkMode = useColorScheme() === 'dark';

   useEffect(async () => {
     localStorage.setString('test', '1234');
     const testStr = localStorage.getString('test');

     localStorage.clearStore();

     const testStr1 = localStorage.getString('test');

     localStorage.setString('test2', '4321');
     const testStr2 = localStorage.getString('test2');

     const currentInstance = await localStorage.getCurrentMMKVInstanceIDs();
     const allInstanceID = await localStorage.getAllMMKVInstanceIDs();
     console.log('Result', testStr, testStr1, testStr2, currentInstance, allInstanceID);
   });
....
```

The first time it runs:
```
Result 1234 null 4321 {"myInstance": true} [ "myInstance" ]
```
After reloading the app (Pressing `r`):
```
Result undefined undefined undefined {"myInstance": false} ["myInstance"]
``` 

Changing the instance name allows to restart the process.

Here is a video of the issue: https://monosnap.com/file/SYk5gw7GyJwaz804PJq0CZ1FNx7cFm

And the project I used to reproduce it: https://github.com/msimon/mmkv-react-clearstore-bug-repro
Run `yarn ios`, once load, reload the app.

**Comment by msimon** [comment]
I think I tracked it down to this code:
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/6f2ada75afd1f46c794aa04d979b742a96c0db22/src/initializer.js#L111

```
function setup(id, mode) {
  global.setupMMKVInstance(id, mode, "", "");
  if (!IDStore.exists(id)) {
    global.setBoolMMKV(id, true, id);
    IDStore.add(id, false, null);
    return true;
  } else {
    if (global.containsKeyMMKV(id, id)) {
      return true;
    } else {
      encryptionHandler(id, mode);
    }
  }
}
```

If `IDStore.exists(id)`, but `global.containsKeyMMKV(id, id)` is false, the function does not return true.

Which result in the `handleAction` never setting the store to be ready:
https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/6f2ada75afd1f46c794aa04d979b742a96c0db22/src/handlers.js#L17
```
let ready = initialize(opts);
  if (ready) {
    currentInstancesStatus[id] = true;
  }
```

Since the store is present, but has been cleared, the `global.containsKeyMMKV(id, id)` is returning false. Resulting in the store never being initialised.

**Comment by msimon** [comment]
A possible solution would be to re-add the store id to itself after the clear.
```
  clearStore() {
    const a = handleAction(global.clearMMKV, this.instanceID);
    global.setBoolMMKV(id, true, id);
    return a
  }
```

It works when I do it manually in my code:
```
....
    localStorage.clearStore();
    global.setBoolMMKV("myInstance", true, "myInstance");
....
```

I still don't have a very good grasp of your library. But if you think this is a good way to fix it, I'm more than happy to do a PR.

Let me know!

**Comment by ammarahm-ed** [comment]
I think you are right and what you suggest is the correct solution to this. Since you are loading an encrypted instance of the library, the method here being called is `setupWithEncryption`. `global.containsKeyMMKV` checks if the instance we have loaded is the one we are trying to access or not by reading a key that should always be present, one that is removed when calling `clearStore`. If it does not exist, it calls the `encryptionHandler` method which should return true after rechecking the key in secure storage and unlocking mmkv instance with it. So the bug is actually that we are not returning the result after calling `encryptionHandler`

https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/6f2ada75afd1f46c794aa04d979b742a96c0db22/src/initializer.js#L136
and 

https://github.com/ammarahm-ed/react-native-mmkv-storage/blob/6f2ada75afd1f46c794aa04d979b742a96c0db22/src/initializer.js#L121

it should be like this: 

```js
return encryptionHandler(id, mode)
```
and the solution you proposed, I noticed that you copied the line, here's the one that should be used:

```js
clearStore() {
    const cleared = handleAction(global.clearMMKV, this.instanceID);
    global.setBoolMMKV(this.instanceID, true, this.instanceID);
    return cleared
  }
```


So yes, send in a PR with the fix you proposed along with adding `return` to these two function calls in `setup` and `setupWithEncryption` methods. @msimon

**Comment by gtebbutt** [comment]
I've been investigating a similar issue, and it seems to exist even after updating to v0.5.8.

Using an unencrypted store, clearing, and then trying to use `getAll` e.g. 
```js
export const localStorage = new MMKVStorage.Loader().withInstanceID("instance").initialize();
localStorage.clearStore();
await localStorage.indexer.maps.getAll();
```

Gives the following error: `TypeError TypeError: undefined is not an object (evaluating 'keys.length')`

Any suggestions would be very much appreciated!

**Comment by ammarahm-ed** [comment]
> I've been investigating a similar issue, and it seems to exist even after updating to v0.5.8.
> 
> Using an unencrypted store, clearing, and then trying to use `getAll` e.g. 
> ```js
> export const localStorage = new MMKVStorage.Loader().withInstanceID("instance").initialize();
> localStorage.clearStore();
> await localStorage.indexer.maps.getAll();
> ```
> 
> Gives the following error: `TypeError TypeError: undefined is not an object (evaluating 'keys.length')`
> 
> Any suggestions would be very much appreciated! 

This is a different issue I think. When you call clearAll everything is removed in the storage including indexes. But we need to handle it and send an empty array I think. I will fix this.
