### ISSUE TITLE
[Bug] Cannot save any value into storage, even example App always show andrew & 24 y.o after reloading whenever setString already pressed

### ISSUE THREAD

**Issue by flixyudh** [ammarahm-ed/react-native-mmkv-storage#97]
I'm just update RNMMKV-S from `0.5.3` to `0.5.8` and facing a problem to set value, everytime i `setValue` and reloading app my setter value revert to null

**Comment by ammarahm-ed** [comment]
@zxccvvv Does it happen only when you upgrade from older version? Try to clean the project/node_modules folder and install the new version again.

**Comment by flixyudh** [comment]
I've tried to do

1. yarn add react-native-mmkv-storage ( just to make sure `package.json` use latest version)
2. remove `node_modules` folder
3. remove any lock file (package & yarn)
4. start `yarn install`
5. start `cd android && ./gradlew clean && cd ..`

but the problem still persist @ammarahm-ed

**Comment by ammarahm-ed** [comment]
> I've tried to do
> 
> 1. yarn add react-native-mmkv-storage ( just to make sure `package.json` use latest version)
> 2. remove `node_modules` folder
> 3. remove any lock file (package & yarn)
> 4. start `yarn install`
> 5. start `cd android && ./gradlew clean && cd ..`
> 
> but the problem still persist @ammarahm-ed 

Is it happening on iOS or Android? What if you don't use hook. Instead simply call `setString` and `getString`?

**Comment by ammarahm-ed** [comment]
I have tested on Android now. It is working normally. Even after restarting the app. The values are persisted.

**Comment by flixyudh** [comment]
> Is it happening on iOS or Android? What if you don't use hook. Instead simply call `setString` and `getString`?

Currently i'm try it on Android, last time i've tried using `setString` and `getString` but the problem still persist like what i describe above.

when i just update the packager to newest version without changing any code from `0.5.3` i got an error `Cannot read property .then of undefined`

```
import MMKV from 'react-native-mmkv-storage';

export const HelperMMKVStorage = new MMKV.Loader().withEncryption().initialize();

const firstInstall = "FIRST_INSTALL"
const sentences = "LIST_SENTENCES"
const user = "USER"

/*================== FIRSTINSTALL ================== */
export function DB_ShowOnBoard(){
  return new Promise((resolve, reject)=>{
    HelperMMKVStorage.indexer.hasKey(firstInstall)
    .then(res=>{ // here then is undefined
      if(res){
        HelperMMKVStorage.getBool(firstInstall, (error, result)=>{
          if(error) reject(error)
          else resolve(result)
        })
      } else {
        resolve(true)
      }
    })
    .catch(reject)
  })
}
```

is there any breaking changes from 0.5.3 to 0.5.8 about how do i call the function?

**Comment by ammarahm-ed** [comment]
> > Is it happening on iOS or Android? What if you don't use hook. Instead simply call `setString` and `getString`?
> 
> Currently i'm try it on Android, last time i've tried using `setString` and `getString` but the problem still persist like what i describe above.
> 
> when i just update the packager to newest version without changing any code from `0.5.3` i got an error `Cannot read property .then of undefined`
> 
> ```
> import MMKV from 'react-native-mmkv-storage';
> 
> export const HelperMMKVStorage = new MMKV.Loader().withEncryption().initialize();
> 
> const firstInstall = "FIRST_INSTALL"
> const sentences = "LIST_SENTENCES"
> const user = "USER"
> 
> /*================== FIRSTINSTALL ================== */
> export function DB_ShowOnBoard(){
>   return new Promise((resolve, reject)=>{
>     HelperMMKVStorage.indexer.hasKey(firstInstall)
>     .then(res=>{ // here then is undefined
>       if(res){
>         HelperMMKVStorage.getBool(firstInstall, (error, result)=>{
>           if(error) reject(error)
>           else resolve(result)
>         })
>       } else {
>         resolve(true)
>       }
>     })
>     .catch(reject)
>   })
> }
> ```
> 
> is there any breaking changes from 0.5.3 to 0.5.8 about how do i call the function?

1. The `hasKey` function is not async anymore. 
2. The `getBool` function does not require a callback function. it simply returns the value.

Try this code: 

```jsx
import MMKV from 'react-native-mmkv-storage';

export const HelperMMKVStorage = new MMKV.Loader().withEncryption().initialize();

const firstInstall = "FIRST_INSTALL"
const sentences = "LIST_SENTENCES"
const user = "USER"

/*================== FIRSTINSTALL ================== */
export function DB_ShowOnBoard(){
  return HelperMMKVStorage.getBool(firstInstall); 
}
```
If the value does not exist, it returns `null`.

**Comment by flixyudh** [comment]
Seriously, i just read the installation guide one more time, and i see there's something i didn't followed.

the part i'm missing is:
```
@Override
protected JSIModulePackage getJSIModulePackage() {
    return new CustomMMKVJSIModulePackage();
}
```
IMHO it would be more clear to break the part that needed to add one by one rather than add 1 project with comment

One more question @ammarahm-ed , does RNMMKV-S support default value?
as you see above i have a key `FIRST_INSTALL` and i want to set it to `true` at first time opening the apps

**Comment by ammarahm-ed** [comment]
> Seriously, i just read the installation guide one more time, and i see there's something i didn't followed.
> 
> the part i'm missing is:
> ```
> @Override
> protected JSIModulePackage getJSIModulePackage() {
>     return new CustomMMKVJSIModulePackage();
> }
> ```
> IMHO it would be more clear to break the part that needed to add one by one rather than add 1 project with comment
> 
> One more question @ammarahm-ed , does RNMMKV-S support default value?
> as you see above i have a key `FIRST_INSTALL` and i want to set it to `true` at first time opening the apps

I don't think so, however you can set the value when your app loads the first time. You don't need to you async functions. Just use sync api.
